### ISSUE TITLE
Previewer not displaying files that are not a child of the present working directory tree

### ISSUE THREAD

**Issue by jessevernon** [nvim-telescope/telescope.nvim#2077] opened 2022-07-15 19:06 UTC
### Description

If I open a file `~/foo/bar.txt`, the previewer for `:Telescope buffers` works as expected. If I cd to a directory that is not a parent of `bar.txt` such as `:cd ~/baz/`, the previewer for `:Telescope buffers` no longer displays anything.

Works when pwd is `~`:
![image](https://user-images.githubusercontent.com/13456400/179294159-44210826-0c7e-425e-ab32-87cd6c98645f.png)

Does not work when pwd is not a parent of file (in this case `~/Downloads`):
![image](https://user-images.githubusercontent.com/13456400/179294247-b8ca4f0f-a817-4e32-949d-732a04677255.png)
![image](https://user-images.githubusercontent.com/13456400/179294415-11d2813d-912c-4a96-920a-aa0fbb16aa64.png)

### Neovim version

```markdown
NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -ffile-prefix-map=/build/neovim-KoQPuQ/neovim-0.7.0~ubuntu1+git202205061518-d9ec57e16-dd05b3569=. -flto=auto -ffat-lto-objects -fstack-protector-strong -Wf
ormat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -
Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -
Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SO
URCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-KoQPuQ/neovim-0.7.0~ubuntu1+git202205061518-d9ec57e16-dd05b3569/build/config -I/build/neovim-Ko
QPuQ/neovim-0.7.0~ubuntu1+git202205061518-d9ec57e16-dd05b3569/src -I/build/neovim-KoQPuQ/neovim-0.7.0~ubuntu1+git202205061518-d9ec57e16-dd05b3569/.deps/usr/include -I/usr/include -I/build
/neovim-KoQPuQ/neovim-0.7.0~ubuntu1+git202205061518-d9ec57e16-dd05b3569/build/src/nvim/auto -I/build/neovim-KoQPuQ/neovim-0.7.0~ubuntu1+git202205061518-d9ec57e16-dd05b3569/build/include
Compiled by buildd@lcy02-amd64-063

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Ubuntu 22.04 LTS

### Telescope version / branch / rev

0.1.0

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.1

## ===== Installed extensions =====
```

### Steps to reproduce

1. Open a file `e ~/foo/bar.txt`
2. Cd to a different directory `cd ~/baz/`
3. Run telescope `Telescope buffers`

### Expected behavior

Expect preview for `bar.txt`

### Actual behavior

No preview
![image](https://user-images.githubusercontent.com/13456400/179294476-dc01212c-030f-4ad4-832f-94cf77048f71.png)

### Minimal config

```Lua
call plug#begin()
Plug 'nvim-treesitter/nvim-treesitter'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()
lua << END
require('telescope').setup()
END
```

**Comment by Conni2461** [comment] 2022-07-16 18:08
This worked in the past. Might be a recent regressions. I will look into it tomorrow

**Comment by Conni2461** [comment] 2022-07-18 08:30
It is a recent regression. #2030 introduced it.

#2084 might fix it. I still have to clean up

**Comment by fdschmidt93** [comment] 2022-08-09 10:21
Closing since fixed :)

**Comment by jessevernon** [comment] 2022-08-09 19:13
> Closing since fixed :)

I don't think #2084 has been merged yet?

**Comment by fdschmidt93** [comment] 2022-08-09 19:27
Ah my apologies :facepalm: today is not my day, only read it's fixed and thought issue wasn't closed automatically. Of course, you're right :)

**Comment by jessevernon** [comment] 2022-08-09 19:36
> Ah my apologies facepalm today is not my day, only read it's fixed and thought issue wasn't closed automatically. Of course, you're right :)

No worries! I'd love to help get it merged but I'm not familiar with the code base. @Conni2461 is there anything else I can do to help get the fix merged?

**Comment by Conni2461** [comment] 2022-08-09 19:46
I have a paper due tomorrow. I dont like the fix. I come back fixing it tomorrow evening after i handed in my paper

**Closed** 2022-08-10 19:47 UTC
Labels: bug
