### ISSUE TITLE
Telescope grep_string showing list of nil:nil:nil:nil values

### ISSUE THREAD

**Issue by luisiacc** [nvim-telescope/telescope.nvim#614] opened 2021-03-05 16:11 UTC
Got this error when doing `:Telescope grep_string<CR>`, tried also with the test.vim file, same result, other commands are working fine. `grep_string` was working well 10 minutes ago!:
![image](https://user-images.githubusercontent.com/31720261/110141615-5a1e2b80-7da3-11eb-9cb1-526149505601.png)

Also this appears on the error below:
![image](https://user-images.githubusercontent.com/31720261/110142463-30b1cf80-7da4-11eb-97ed-34b4e9b70a7f.png)

OS:
Windows 10 1909, but neovim is running on WSL Ubuntu 18.04.

Nvim version:
```
NVIM v0.5.0-dev+1115-gc1fbc2ddf
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

Latest telescope commit: `6e941e0ecec1ab6a1b4ce40c693ef1272c505abb`

Edit: If I remove `vimgrep_arguments` configuration it works.

**Comment by rudotriton** [comment] 2021-03-06 20:52
I believe this is by design. The picker would expect to get specific results from the grep command in order to be able to carry out its action. In this case it would be `file:line:column:text`. So if you set your own args, the results have a different format.

**Comment by Conni2461** [comment] 2021-03-06 20:59
@luisiacc what was your change in the vimgrep_arguments config, because like @rudotriton said its by design, we need to cut the ripgrep results into its parts so if you change the config in some way it will no longer work.

For example, when doing `color=always`, we will end up with a bunch of term color codes that mess up our parsing.

Can we close this issue?

**Comment by luisiacc** [comment] 2021-03-06 21:30
I have this. However now not even removing the vimgrep_arguments make it work, If I remove the entire `telescope.setup()` block then it works, so there is something wrong there, I just don't know what it is.
```
require('telescope').setup {
    defaults = {
        vimgrep_arguments = {
            'rg',
            '--color=never',
            '--fuzzy',
            '--no-heading',
            '--with-filename',
            '--line-number',
            '--column',
            '--smart-case'
        },
        file_sorter = require('telescope.sorters').get_fzy_sorter,
        prompt_prefix = ' >',
        color_devicons = true,

        file_previewer   = require('telescope.previewers').vim_buffer_cat.new,
        grep_previewer   = require('telescope.previewers').vim_buffer_vimgrep.new,
        qflist_previewer = require('telescope.previewers').vim_buffer_qflist.new,
        borderchars = { '─', '│', '─', '│', '┌', '┐', '┘', '└' },
        mappings = {
            i = {
                ["<C-q>"] = actions.send_to_qflist,
                ["<A-j>"] = actions.move_selection_next,
                ["<A-k>"] = actions.move_selection_previous,
                ["<esc>"] = actions.close,
            },
        }
    },
    extensions = {
        fzy_native = {
            override_generic_sorter = false,
            override_file_sorter = true,
        }
    }
}

require('telescope').load_extension('fzy_native')

**Comment by Conni2461** [comment] 2021-03-06 21:38
`--fuzzy` breaks it for me because `fuzzy` isn't a rg option. At least i can't find it in the man page and running it in the terminal gives me this:

```
[conni@home telescope.nvim]$ rg --fuzzy as                                                                              
error: Found argument '--fuzzy' which wasn't expected, or isn't valid in this context

USAGE:
    
    rg [OPTIONS] PATTERN [PATH ...]
    rg [OPTIONS] [-e PATTERN ...] [-f PATTERNFILE ...] [PATH ...]
    rg [OPTIONS] --files [PATH ...]
    rg [OPTIONS] --type-list
    command | rg [OPTIONS] PATTERN

For more information try --help
```

Thats no valid output :)

**Closed** 2021-03-06 21:51 UTC
Labels: bug

**Comment by steabert** [comment] 2021-03-26 12:52
I have a similar problem, and I traced mine to the lack of `~/.ripgreprc` file. In that case, ripgrep outputs a line

```
/home/steabert/.ripgreprc: No such file or directory (os error 2)
```

but it's sent to `stderr`. I can easily get rid of the problem by just touching `~/.ripgreprc`, and reproduce the problem by removin that file again. So, it seems that the job from plenary includes `stderr` in the results somehow? However, I did not have time to investigate if this is a plenary problem, or if telescope is somehow not taking care of stderr properly (I'm new to both lua and this code base), or maybe it's intentional to inlude this in the results?

**Comment by Conni2461** [comment] 2021-03-26 13:02
I can't comment on `.ripgreprc` because i don't have one. Just searched for it with `fd --hidden -I`. What rg version do you use?
`plenary.job` can distinguished between `stdout` and `stderr`, tj just calls the same function for both in telescope.
https://github.com/nvim-telescope/telescope.nvim/blob/a7fa60411efbfddc0674d65346a5311e33f6deb1/lua/telescope/finders.lua#L96-L97

Maybe we should log `stderr` :thinking: Good catch.

**Comment by steabert** [comment] 2021-03-26 13:59
I was using `ripgrep 0.10.0` (It's debian buster, slightly dated I guess, they went from that to 11.x.x and now 12.x.x).
