### ISSUE TITLE
Re-entering insert mode with `shift-i` causes characters to print backwards

### ISSUE THREAD

**Issue by tapayne88** [nvim-telescope/telescope.nvim#567] opened 2021-02-27 14:54 UTC
### Description

When I launch telescope and exit insert mode and re-enter using `shift-i` my typed characters print backwards and delete removes all typed characters. This seems to occur for all tested pickers (`git_files`, `buffers`, `find_files`).

Re-entering with `i` or `a` or `shift-a` all work as expected.

I found this as I usually start telescope and search for something general and want to scope it to a subdirectory. I escape insert mode, press `shift-i` to get to the beginning of the prompt and type the subfolder which unfortunately appears backwards, i.e. when typing `lua` it appears `aul` 😄 

**Expected Behavior**

Re-entering insert mode with `shift-i` allows me to type forwards

**Actual Behavior**

Characters appear in the reverse order typed

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. `:Telescope git_files`
3. Press escape
4. Press `shift-i` insert mode at the beginning of the line
5. Type and watch characters always insert on the left (typed word appears backwards)
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.5.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by tpa11

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/jp0ax06hb7kfls5jcndz3d15s3iv60mn-neovim-nightly-master/share/nvim"

Run :checkhealth for more info
```
- Operating system: macOS Mojave (10.14.6)
- Telescope commit: `49650f5`

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by tapayne88** [comment] 2021-02-27 14:54
I'm happy to have a look into this but I'm not too sure where to start!

**Comment by Conni2461** [comment] 2021-02-27 15:03
Prompt buffer issues. So neovim issue. 

Neovim is still missing some vim patches for prompt buffer. I can't reproduce it doing: `Telescope find_files propt_prefix=` which basically doesn't set prompt buffertype.

I will keep this issues open for tracking but this is not a telescope issue :) Still thanks for reporting

**Comment by tapayne88** [comment] 2021-02-27 15:10
Yeah, same for me with `Telescope find_files prompt_prefix=`. Thanks for the workaround 👍

**Comment by tapayne88** [comment] 2021-04-20 17:06
This workaround now seems to be causing me issues where telescope is blank on initial open and requires something to be typed in order to display anything. This happens on all my tested uses `git_files`, `find_files`, `file_browser`, `buffers`

**Comment by Conni2461** [comment] 2021-04-21 18:55
Noticed that as well. See https://github.com/nvim-telescope/telescope.nvim/issues/777

**Comment by Conni2461** [comment] 2021-12-08 18:03
This issue is fixed in the latest neovim master: neovim/neovim#16421. Its not part of the 0.6 release

**Closed by Conni2461** 2021-12-08 18:03 UTC
Labels: upstream
