### ISSUE TITLE
shorten_path break any search

### ISSUE THREAD

**Issue by pmizio** [nvim-telescope/telescope.nvim#706] opened 2021-03-30 21:41 UTC
### Description
When I try set `shorten_path` to any telescope function after entering one char nvim scream:
```
Error executing luv callback:
\tmp\plugged\telescope.nvim\lua\telescope\path.lua:38: cannot resolve symbol 'shorten_dir': Nie mo<bf>na odnale<9f><e6> okre<9c>lonej procedury.
```
`Nie mo<bf>na odnale<9f><e6> okre<9c>lonej procedury.` in english is somethig about - `Cannot find given procedure`

**Expected Behavior**
To see search results with shorten path

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. :lua require('telescope.builtin').live_grep({shorten_path = true})
3. type somethig
4. .... bang here is the issue

</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.5.0-dev+1186-g8665a96b9
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -IC:/projects/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Skompilowany przez runneradmin@fv-az152-699

Features: -acl +iconv +tui
See ":help feature-compile"

       vimrc systemu: "$VIM\sysinit.vim"
   odwet dla $VIM-a: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```

- Operating system:  Windows 10
- Telescope commit:  2e03f67

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by Conni2461** [comment] 2021-04-03 13:13
We are using a c function with ffi from neovim maybe that is not possible with windows. There is this PR https://github.com/nvim-lua/plenary.nvim/pull/78 that implements a lua fallback, so we can just disable ffi variant for windows.

CC @anott03

**Comment by anott03** [comment] 2021-04-03 13:18
I'd imagine #473 would fix this as all path shortening is now done through plenary but I don't have a windows machine to test and confirm that that is the case. Maybe you can @Conni2461?

**Comment by Conni2461** [comment] 2021-04-03 13:22
Yeah exactly that why i was CCing you :laughing: But i think you need to add
```lua
if jit and os_sep ~= '\\' then
```
or similar (because he has JIT but windows).

Similar to what we are doing here:
https://github.com/nvim-telescope/telescope.nvim/blob/2c4efc2f8af0575526f7b5dcc35fba9e0f1cc944/lua/telescope/utils.lua#L274

**Comment by pmizio** [comment] 2021-04-03 14:48
Just for curiosity, I read a little bit on ffi and it is supported on windows, why digging to this C function od not possible it is something about windows itself or neovim not enabling this for Windows?

**Comment by Conni2461** [comment] 2021-04-03 15:10
Yes ffi is supported on windows but we get `symbol not found` for neovim functions. I am not sure why tho? The functions, we are using for ffi, are in core and we can call them on unix systems(linux, mac and bsd) apparently just not on windows.

Why we using c functions? Tested, faster and it was already implemented :rofl: 

https://github.com/neovim/neovim/blob/abdda664108646a8f1bd3112abb8083d721d38e6/src/nvim/path.c#L249-L274

**Comment by anott03** [comment] 2021-04-04 01:39
@Conni2461 this should be good right?

https://github.com/nvim-lua/plenary.nvim/pull/78/commits/d8f03bec523ed5cd5533f6eeed6f9b1cd4803ce7

**Comment by l-kershaw** [comment] 2021-12-14 21:43
I can't reproduce this on my Windows machine, so I think this has now been resolved.
Closing now, but feel free to reopen if you can still reproduce 🙂

**Closed by l-kershaw** 2021-12-14 21:43 UTC
Labels: bug
