### ISSUE TITLE
Horizontal scrolling for previewer

### ISSUE THREAD

**Issue by fmorroni** [nvim-telescope/telescope.nvim#2211] opened 2022-10-26 03:53 UTC
**Is your feature request related to a problem? Please describe.**
There doesn't seem to be a way to scroll horizontally in the preview window, this sometimes gets annoying, especially in smaller screens.

**Describe the solution you'd like**
I'd like to have a function like preview_scrolling_up/down() but for horizontal scrolling. Something like the keybinds zl/zL/zh/zH for horizontal scrolling in regular buffers, but for the preview window.

**Describe alternatives you've considered**
Another solution would be being able to move the cursor into the preview window and be able to navigate normally that way (no idea if this is possible).

**Comment by l-kershaw** [comment] 2022-12-19 22:19
I think that #2243 is a duplicate of this issue.

I've just [answered](https://github.com/nvim-telescope/telescope.nvim/issues/2243#issuecomment-1358474060) there before I saw this issue.

>  I think that left/right scrolling could be (partially) implemented by sending zL and zH to the preview buffer (this is similar to how vertical scrolling is implemented).
However, you would run into issues when you have a mixture of very long and very short lines in the file you are previewing.
>
> In a normal buffer (outside telescope) using zL zH (and variants) while your cursor is on a short line, you won't move at all horizontally.
Since the cursor is not shown in the telescope preview buffer, this is likely to cause confusion.
>
> I can't think of another way to implement horizontal scrolling that avoids this problem 😕

**Comment by martin-braun** [comment] 2022-12-20 00:14
@l-kershaw You are right, my issue was a duplicate to this one, I didn't saw this issue either. I closed my issue, since this issue is older.

Regarding the issue, it should be possible to scroll vertically on all lines by [setting virtualedit](https://vi.stackexchange.com/questions/9372/how-to-make-horizontal-scrolling-easier-when-the-cursor-is-not-ideally-located). The additional `autocmd`s seem only relevant if the cursor can be moved, which is not the case for the previewer.

It might be worth to give the user a way to always run `:set wrap` on previewers to avoid the necessity for vertical scrolling altogether.

Thanks a lot!

**Comment by zanuarmirza** [comment] 2023-03-02 08:38
dealing with long horizontal code by using scroll-x is going to be nice. It can reduce the work amount to find the exact file I want.
my current workflow is by using telescope `builtin.resume` . So instead of reading the code in preview section, I select one of the results then if I want to look at another result then show the previous results.

**Comment by Chloe-H** [comment] 2023-09-29 16:52
[This](https://github.com/nvim-telescope/telescope.nvim/pull/2437) claims to add horizontal scrolling in the previewer, but I have yet to see it work. I've tried the default keymaps for scrolling the previewer and results on multiple machines and operating systems. I also tried to add the mappings myself, but I keep getting "Key does not exist" errors for the actions.

`init.lua` snippet:
```lua
local telescope = require('telescope')
telescope.setup({
    mappings = {
        n = {
            ['<C-b>'] = require('telescope.actions').preview_scrolling_left,
            ['<C-f>'] = require('telescope.actions').preview_scrolling_right,
        },
    },
    pickers = {
        find_files = {
            hidden = true,
        },
    },
})

```

Error:
![image](https://github.com/nvim-telescope/telescope.nvim/assets/10136444/cd23a336-0e35-46dc-b1de-9c11e5b7e69f)

Does anyone know what's going on?

**Comment by jamestrew** [comment] 2023-09-29 17:22
@Chloe-H are you on the master branch? I can confirm it's working.

**Closed** 2023-10-01 01:13 UTC
Labels: enhancement

**Comment by Chloe-H** [comment] 2023-10-04 15:09
> @Chloe-H are you on the master branch? I can confirm it's working.

@jamestrew 

Good question! I'm on `0.1.x`, per the recommended installation instructions.

I temporarily checked out `master`, and...yep! It works! Thanks for the pointer.

Per the README, this change will eventually find its way to the release branch (`0.1.x`), right?

**Comment by Chloe-H** [comment] 2023-10-04 22:15
Honestly, I so rarely remember to `PlugUpdate`, and I typically snapshot before I do...I'm making a note to switch to `master` this week.

**Comment by Conni2461** [comment] 2023-10-06 06:46
We somewhat follow semver, meaning we will not backport features to 0.1.x, its a stable branch meaning you get a stable version + bugfixes on top. no breakage nothing, thats enough for 90+% of users and everyone who can live with more or less breaking changes can follow master.

Upside new features, downside not stable

**Comment by jamestrew** [comment] 2023-10-06 14:04
> new features on master will eventually make their way down to more stable branches/tags

I meant _new_ stable branches.
