### ISSUE TITLE
Can't enter insert mode in a .MDX file -- throws `E523: Not allowed here` error

### ISSUE THREAD

**Issue by dakahn** [nvim-telescope/telescope.nvim#838] opened 2021-05-11 22:37 UTC
### Description
Recently switched from FZF to Telescope. Love it, but I can't enter insert mode in [a .MDX file](https://mdxjs.com/). After going through my whole config commenting/uncommenting every plugin, set (etc) I narrowed it down to my Telescope remaps. Kinda funny -- no clue why that might be the case. These remaps were copied out of the docs. 

```lua
nnoremap <C-p> <cmd>lua require('telescope.builtin').find_files()<cr>                             
nnoremap <C-f> <cmd>lua require('telescope.builtin').live_grep()<cr>
nnoremap <C-b> <cmd>lua require('telescope.builtin').buffers()<cr>
```

**Expected Behavior**
I expect to be able to enter insert mode while editing an .MDX file ✌🏽 

**Actual Behavior**
when the `i` key is pressed a `E512: Not allowed here` error is thrown. My understanding is that this could be due to conflicting commands or functions, but I'm a little out of depth here admittedly. MDX files contain JSX (technically strings) in them though so this could be crossing wires somewhere. 

### Details

<details><summary>Reproduce</summary>

1. with the remaps set open a .MDX file
2. hit the `i` key
</details>

<details><summary>Environment</summary>

- nvim --version output: nvimNVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-s6G3gz/neovim-0.5.0+ubuntu2+git202105030108-a0da4c3a4-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-s6G3gz/neovim-0.5.0+ubuntu2+git202105030108-a0da4c3a4-d569569c9/build/config -I/build/neovim-s6G3gz/neovim-0.5.0+ubuntu2+git202105030108-a0da4c3a4-d569569c9/src -I/build/neovim-s6G3gz/neovim-0.5.0+ubuntu2+git202105030108-a0da4c3a4-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-s6G3gz/neovim-0.5.0+ubuntu2+git202105030108-a0da4c3a4-d569569c9/build/src/nvim/auto -I/build/neovim-s6G3gz/neovim-0.5.0+ubuntu2+git202105030108-a0da4c3a4-d569569c9/build/include
Compiled by buildd@lcy01-amd64-024

- Operating system: WSL Ubuntu on Windows 10 latest
- Telescope commit: latest

</details>

<details><summary>Configuration</summary>
<p>

My Telescope is stock -- except for the remaps in question 😉

**Comment by dakahn** [comment] 2021-05-12 04:37
Added the minimum config -- still can't enter insert mode though

If I run `nvim file.mdx` I don't have the issue. It's only if I use `find_files` inside of vim -- didn't notice that before but confirmed it's the case 👍🏽 

Full output of --version is as follows
```
nvimNVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-s6G3gz/neovim-0.5.0+ubuntu2+git202105030108-a0da4c3a4-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-s6G3gz/neovim-0.5.0+ubuntu2+git202105030108-a0da4c3a4-d569569c9/build/config -I/build/neovim-s6G3gz/neovim-0.5.0+ubuntu2+git202105030108-a0da4c3a4-d569569c9/src -I/build/neovim-s6G3gz/neovim-0.5.0+ubuntu2+git202105030108-a0da4c3a4-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-s6G3gz/neovim-0.5.0+ubuntu2+git202105030108-a0da4c3a4-d569569c9/build/src/nvim/auto -I/build/neovim-s6G3gz/neovim-0.5.0+ubuntu2+git202105030108-a0da4c3a4-d569569c9/build/include
Compiled by buildd@lcy01-amd64-024
```

**Comment by smithbm2316** [comment] 2021-05-12 06:52
Hmm I see. I can't reproduce on my end at the moment unfortunately, how did you install neovim? Did you use an Ubuntu PPA, build from source, the appimage, or some other method? Perhaps there's some weirdness with WSL that's going on. Do you know if you're opening a read-only file by any chance? You could check by running `ls -l` in the directory that file is in on your command line and checking what the read/write/execute permissions for it look like. That at my moment is my best guess, otherwise I might be able to try and install neovim and WSL on the Windows partition of my machine and see if I can reproduce there.

**Comment by dakahn** [comment] 2021-05-12 14:21
Yeah, installed via the Ubuntu PPAs. The file isn't read only. It's one of _many_ in a large project I'm a part of. Also worth noting is that this problem only started after installing Telescope. I could make updates to .MDX files fine when finding via FZF previously. Also to reiterate If I disable the Telescope rebinds mentioned above I can enter insert mode and edit as usual. 

You can see [my whole init.vim here](https://github.com/dakahn/dotfiles/blob/master/.config/nvim/init.vim). I don't have much customization (prefer not to tinker with unstable software).

**Comment by smithbm2316** [comment] 2021-05-16 07:29
From looking at your init.vim, I think it could be an issue possibly with that `:inoremap jk <Esc>` mapping. First of all, you should be able to remove the colon at the beginning in order to map that properly afaik. Second, any insert mode mappings you create could possibly cause an issue with what happens in telescope as you'd be in insert mode there. Try commenting out that mapping and testing the Telescope mappings without that there perhaps? 

The next thing I'd do is run the `:verbose imap` and `:verbose map` commands to try and see if there are any normal mode or insert mode mappings that are being set that you're not expecting, as the `verbose` part will show you _where_ those mappings were set from on top of showing you the existence of them. 

Let me know if anything I've mentioned here helps debug this issue a bit. I'm sorry to kinda be sending you on a bit of a wild goose chase, I honestly have no idea why an `mdx` file of all things would be the cause of this issue. Could be something with the mdx syntax plugin as well causing an issue, as great as plugins are they can have some unintentional side effects sometimes unfortunately :rofl: . I've had to debug many a weird plugin affecting another plugin issue in the 10 months I've used Neovim lol.

**Comment by dakahn** [comment] 2021-05-18 14:47
Hey, I appreciate you trying to figure this out with me, friend 🕊️. Good news, courtesy of `:verbose imap` I have found the culprit 🕵🏽

It seems to be Deoplete -- in particular these bindings seem to be breaking entering insert mode after `find_files`:
![image](https://user-images.githubusercontent.com/40970507/118672364-cbc02000-b7bd-11eb-9cbe-8ba6e7ed1954.png)

For future debuggers reference:
- unmapped my exit insert mappings and that had no positive effect
- entered find_files with `:Telescope find_files` and that had no positive effect
- disabled my MDX syntax package to no positive effect

**Comment by smithbm2316** [comment] 2021-05-18 18:38
Ah! I think that I can help you fix 😃. Try adding this to your init.vim:

```vim
autocmd FileType TelescopePrompt call deoplete#custom#buffer_option('auto_complete', v:false)
```

A lot of completion plugins and Telescope don't play nicely because of those insert mode mappings. You likely don't want to have deoplete offer completions to you anyways when you're in a Telescope picker. This autocommand should disable deoplete's auto completion whenever you enter a Telescope buffer. Hopefully this might fix your issue. We should probably add something to our readme warning about this issue with completion plugins and to go check their respective docs for the way they disable themselves on certain filetypes.

**Comment by twnaing** [comment] 2021-09-13 11:34
In my case, it is `completion-nvim` binding. Changing to load the completion only for lsp-enabled buffers does the trick for me.

**Comment by pitbuster** [comment] 2021-12-19 14:28
I wanted to have completion on all buffers with `completion-nvim`, so I just excluded `TelescopePrompt` with the following line (if you are not using Lua for config files, just drop the surrounding `cmd [[...]]`)

```` lua
cmd [[autocmd FileType *\(TelescopePrompt\)\@<! lua require'completion'.on_attach()]]
````

**Comment by Conni2461** [comment] 2022-01-14 18:44
From reading thought this issue it seems that it is resolved. Closing feel free to reopen if i am wrong

**Closed by Conni2461** 2022-01-14 18:44 UTC
Labels: bug

**Comment by HiPhish** [comment] 2022-06-17 15:48
> I wanted to have completion on all buffers with `completion-nvim`, so I just excluded `TelescopePrompt` with the following line (if you are not using Lua for config files, just drop the surrounding `cmd [[...]]`)
> 
> ```lua
> cmd [[autocmd FileType *\(TelescopePrompt\)\@<! lua require'completion'.on_attach()]]
> ```

This did not work for me. I had to create a wrapper function which aborts if the file type contains `Telescope.*`.

```vim
function! s:on_attach()
	if 'Telescope.*' =~# &ft 
		return
	endif
	lua require('completion').on_attach()
endfunction

augroup completion
	autocmd!
	autocmd BufEnter * call s:on_attach()
augroup END

```

I was not able to find anything about exclusion in `:h autocmd-pattern`, so I have no idea how the above pattern was even supposed to work in the first place.
