### ISSUE TITLE
Missing preview window

### ISSUE THREAD

**Issue by feedoom** [nvim-telescope/telescope.nvim#1070] opened 2021-08-01 17:30 UTC
when i use `:Telescope live_grep`, `:Telescope find_files` or other commands.it all missing preview window
i has install bat, fd, ripgrep, nvim-treesitter
my config
```
local actions = require('telescope.actions')
require('telescope').setup{
    defaults = {
        layout_strategy = "horizontal",
        vimgrep_arguments = {
            'rg',
            '--color=never',
            '--no-heading',
            '--with-filename',
            '--line-number',
            '--column',
            '--smart-case',
            '--ignore',
            '--hidden'
        },
        file_ignore_patterns = {
            ".git",
            "node_modules"
        },
        prompt_prefix = "🔎 ",
        mappings = {
            i = {
                ["<C-k>"] = actions.move_selection_previous,
                ["<C-j>"] = actions.move_selection_next,
                ["<esc>"] = actions.close
            }
        }
    },
}

```
![image](https://user-images.githubusercontent.com/37018475/127778524-9a8571d1-bc58-49f3-ae3c-0e10fdf7dc38.png)

**Comment by l-kershaw** [comment] 2021-08-01 20:05
I think that this is caused by the size of your window.
It looks like (I haven't counted) you have <120 columns in your window, which is the default value for disabling the preview in the `horizontal` layout strategy.

---

You can avoid this issue by tweaking the defaults in your config, for example:
``` lua
require('telescope').setup{
    defaults = {
        layout_strategy = "horizontal",
        layout_config = {
            horizontal = { preview_cutoff = 100, },
        },
        ⁝
    },
}
```

Let me know if this fixes your issue 🙂

**Comment by feedoom** [comment] 2021-08-02 03:05
> I think that this is caused by the size of your window.
> It looks like (I haven't counted) you have <120 columns in your window, which is the default value for disabling the preview in the `horizontal` layout strategy.
> 
> You can avoid this issue by tweaking the defaults in your config, for example:
> 
> ```lua
> require('telescope').setup{
>     defaults = {
>         layout_strategy = "horizontal",
>         layout_config = {
>             horizontal = { preview_cutoff = 100, },
>         },
>         ⁝
>     },
> }
> ```
> 
> Let me know if this fixes your issue 🙂

ok，you are right。my terminal font too big😂。thanks you。

**Comment by l-kershaw** [comment] 2021-08-02 08:35
Glad you got this sorted 👍 

Closing now

**Closed by l-kershaw** 2021-08-02 08:35 UTC
Labels: bug
