### ISSUE TITLE
Popup list of keymaps for current picker

### ISSUE THREAD

**Issue by fedoranvar** [nvim-telescope/telescope.nvim#1114] opened 2021-08-13 12:37 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by clason** [comment] 2021-08-13 12:38
The template is there for a reason... (Don't make me turn this into a form, too!)

**Comment by clason** [comment] 2021-08-13 12:39
I suspect that this is a duplicate of https://github.com/nvim-telescope/telescope.nvim/pull/1084 anyway. If it's not, please edit the issue to describe in detail what you want.

**Closed by clason** 2021-08-13 12:38 UTC
Labels: enhancement

**Comment by fedoranvar** [comment] 2021-08-13 13:51
sorry for bad searching
