### ISSUE TITLE
can't get path_display working for specific picker

### ISSUE THREAD

**Issue by darzok0914** [nvim-telescope/telescope.nvim#1658] opened 2022-01-05 21:10 UTC
### Description

hello :), I made a custom picker and I'm trying to display the tail of file path but only for that specific picker. I looked a bit at the documentation and some PRst and it seems like there is several options. I can use the 'tail' options or I can also provide a callback to the display_path options. however in all examples provided it is always for the defaults options and my understanding is that it will be applied to everything not just the picker I want. 

### Neovim version

```markdown
NVIM v0.7.0-dev+716-g9a0196d24
```

### Operating system and version

Ubuntu 20.04

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 12.1.1 (rev 7cb211378a)
  - OK: fd: found fd 7.4.0

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

this is the code I'm trying to get working, I can't figure out what I do wrong (everything works except the path_display
```lua
....
    local opts = {}
    opts.finder = finders.new_table(files)
    opts.sorter = sorters.get_generic_fuzzy_sorter({})
    opts.previewer = previewers.vim_buffer_cat.new({})
    opts.prompt_title = "<C-e> display/edit, <C-x> delete, <C-t> toggle review status"
    opts.results_title = results_titles[results_titles_idx]
    opts.attach_mappings = telescope_mappings(cards_file_path, deck, results_titles_idx)
    opts.defaults = {
        path_display = function(opts, path)
            local tail = require"telescope.utils".path_tail(path)
            return string.format("%s (%s)", tail, path)
        end
    }

    pickers.new(opts):find()

```

### Expected behavior

having only the file names displayed but only for a specific picker

### Actual behavior

the full path is being displayed

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by l-kershaw** [comment] 2022-01-05 21:16
I **_think_** this should work if you don't put the `path_display` in the `defaults` table here.
Just `opts.path_display` should work.

**Comment by darzok0914** [comment] 2022-01-05 23:32
hi, thank you so much for your time and the prompt response. 

I try this, but with no success

```lua 
...
    local opts = {}
    opts.finder = finders.new_table(files)
    opts.sorter = sorters.get_generic_fuzzy_sorter({})
    opts.previewer = previewers.vim_buffer_cat.new({})
    opts.prompt_title = "<C-e> display/edit, <C-x> delete, <C-t> toggle review status"
    opts.results_title = results_titles[results_titles_idx]
    opts.attach_mappings = telescope_mappings(cards_file_path, deck, results_titles_idx)
    opts.path_display = function(opts, path)
        local tail = require"telescope.utils".path_tail(path)
        return string.format("%s (%s)", tail, path)
    end

    pickers.new(opts):find()

```

**Comment by Conni2461** [comment] 2022-01-06 06:56
Because `path_display` explains how a user should configure it and the finder can then make use of this information and display the path accordingly. You do not make use of this information because you just use the default `entry_maker`. You might get away with using the `make_entry.gen_from_file(opts)` but i can't know this because i do not know what the `files` table contains.

```lua
opts.finder = finders.new_table(new_table { results = files, entry_maker = make_entry.gen_from_file(opts) })
```

This [document](https://github.com/nvim-telescope/telescope.nvim/blob/master/developers.md#entry-maker) mentions some usage of entry_maker, but its not complete, we are still in the process of writing more documentation

If you are writing your own entry maker you need to use this function
https://github.com/nvim-telescope/telescope.nvim/blob/f285599440fcdbf97a7f44d120d403c80316f576/doc/telescope_changelog.txt#L84-L86
otherwise we just do nothing with `path_display`.

Closing because this is not a bug. Dont report questions as bugs

**Closed by Conni2461** 2022-01-06 06:56 UTC
Labels: bug

**Comment by darzok0914** [comment] 2022-01-06 09:19
thanks a lot your help, indeed it solved the issue :)  I just had to remove the "new_table". this is the line of code that made it work:
```lua
    opts.finder = finders.new_table({ results = cards_file_path, entry_maker = make_entry.gen_from_file(opts) })
```
