### ISSUE TITLE
No preview when setting search_dirs for live_grep

### ISSUE THREAD

**Issue by AndrewECarlson** [nvim-telescope/telescope.nvim#687] opened 2021-03-25 04:34 UTC
### Description
Previewer doesn't work for live_grep when setting search_dirs.

**Expected Behavior**
When running
```
 :lua require('telescope.builtin').live_grep({search_dirs = {"~/system/"}})
```
I'd expect a Telescope pop up with a live grep for files from ~/system with a preview
**Actual Behavior**
Telescope pop window pops up but the preview section is blank and once started filtering nvim gets the message: "We tried to open this file but couldn't. We failed with the following error message: ENOENT: no such file or directory: /home/andrew/system//system/home/andrew/system/index.md". It will still filter the list, and I can still hit enter to go to the file. It just doesn't have the preview.

When I ran that my current directory was ~/system. 

When I ran it with a different current directory the first /home/andrew/system/ was replaced with that directory.

I tried running it with cwd set to ~/system and /home/andrew/system, with and without a trailing slash. When I do, the no such file message changes to /home/andrew/system//system/home/andrew/system/index.md, with a third slash in the middle if there's a trailing slash on cwd.
### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2.  :lua require('telescope.builtin').live_grep({search_dirs = {"~/system/"}})
3. 
</details>

<details><summary>Environment</summary>
 - nvim --version output:
NVIM v0.5.0-dev+1157-g0ab88c2ea
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az204-778
Features: +acl +iconv +tui
See ":help feature-compile"

system vimrc file: "$VIM/sysinit.vim"
fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

 - Operating system: Arch Linux
 - Telescope commit: I'm not really sure where to check this, but I just updated with packer and the current commit is 83e1993d875d88ab1b715bfdf36c10e6a8ed1ff4

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by Conni2461** [comment] 2021-03-30 10:29
@tami5  did this work for you when you implemented it? Because i don't think it ever worked.

We just always concat it:
https://github.com/nvim-telescope/telescope.nvim/blob/2e03f67de9eab023098bd05916bf26556520a467/lua/telescope/make_entry.lua#L158

Maybe we should not do this part in `entry_maker`
https://github.com/nvim-telescope/telescope.nvim/blob/2e03f67de9eab023098bd05916bf26556520a467/lua/telescope/make_entry.lua#L188

But outside and if `search_dirs` than `cwd` is nil and then only concat when cwd is not nil. Thoughts?

**Comment by Conni2461** [comment] 2022-01-14 17:52
Can no longer reproduce this issue and i think i remember merging a fix. Closing feel free to reopen if its not resolved

**Closed by Conni2461** 2022-01-14 17:52 UTC
Labels: bug
