### ISSUE TITLE
prompt prefix not highlighted

### ISSUE THREAD

**Issue by max397574** [nvim-telescope/telescope.nvim#2384] opened 2023-02-14 14:12 UTC
### Description

the prompt prefix isn't highlighted

### Neovim version

```markdown
NVIM v0.9.0-dev-912+gfe1e6b82f
```

### Operating system and version

macos 11.4

### Telescope version / branch / rev

telescope head

### checkhealth telescope

```markdown
NVIM v0.9.0-dev-912+gfe1e6b82f
```

### Steps to reproduce

1. `nvim -u repro.lua`
2. `:Telescope find_files`

### Actual behavior

prompt prefix not highlighted

### Minimal config

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    "folke/tokyonight.nvim",
    {
        "nvim-telescope/telescope.nvim",
        config = true,
    },
    {
        "nvim-lua/plenary.nvim",
    },
    -- add any other plugins here
}
require("lazy").setup(plugins, {
    root = root .. "/plugins",
})
vim.api.nvim_set_hl(0,"TelescopePromptPrefix",{fg="#ffab00"})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by yunusey** [comment] 2023-02-22 01:38
Hello, did you try to take 
```lua
vim.api.nvim_buf_set_hl(0, "TelescopePromptPrefix", {fg="#ffab00"})
```
under this line:
```lua
vim.cmd.colorscheme("tokyonight")
```

So, your file should look like this at the end:
```lua

-- Your other stuff...
vim.cmd.colorscheme("tokyonight")

vim.api.nvim_set_hl(0,"TelescopePromptPrefix",{fg="#ffab00"})
-- Add anything else here...
```

The main reason I want you to try this is because ```tokyonight``` may be highlighting "TelescopePromptPrefix". So, although you're doing the right thing, ```tokyonight``` may be conflicting with it.

**Comment by yunusey** [comment] 2023-02-22 01:51
Also, I'd suggest you to setup ```tokyonight``` before using it. You can see one example [here](https://github.com/folke/tokyonight.nvim/blob/main/README.md#-overriding-colors--highlight-groups). I believe it should be something like this:
```lua
require("tokyonight").setup({
  on_highlights = function(hl, _)
    hl.TelescopePromptPrefix = {
      fg = "#ffab00",
    },
    -- Your other highlight config here...
  end,
})
```
I think this should work.

**Comment by utilyre** [comment] 2023-02-22 13:53
Hi @yunusey. I can confirm that even with the `TelescopePromptPrefix` hl being set in the tokyonight's `on_highlight` function, the prompt prefix remains unhighlighted.

BTW, this only happens on nvim-nightly.

**Comment by yunusey** [comment] 2023-02-22 14:14
Hello @utilyre , just one more thing: is there a chance that you misspelled ```on_highlights```? If you wrote ```on_highlight``` instead of ```on_highlights``` it may be the reason. Additionally, I tried the same config @max397574 did. And it worked. Can you check your spelling in your config file, please?

**Comment by utilyre** [comment] 2023-02-22 14:16
> Hello @utilyre , just one more thing: is there a chance that you misspelled `on_highlights`? If you wrote `on_highlight` instead of `on_highlights` it may be the reason. Additionally, I tried the same config @max397574 did. And it worked. Can you check your spelling in your config file, please?

Oh sorry that I forgot the 's' here but on my own config it's spelled correctly.

**Comment by yunusey** [comment] 2023-02-22 14:16
Is there a chance, you can upload your config?

**Comment by utilyre** [comment] 2023-02-22 14:19
There you go

```lua
-- tokyonight

local spec = {
  "folke/tokyonight.nvim",
  priority = 100,
}

function spec.config()
  local tokyonight = require("tokyonight")

  tokyonight.setup({
    style = "night",
    on_highlights = function(highlights, colors)
      highlights["@text.note"] = { bold = true, background = colors.blue2 }
      highlights["@text.todo"] = { bold = true, background = colors.green1 }
      highlights["@text.warning"] = { bold = true, background = colors.yellow }
      highlights["@text.danger"] = { bold = true, background = colors.red1 }

      highlights["NoiceCmdlinePopup"] = { background = colors.bg_float }

      highlights["TelescopePromptPrefix"] = { foreground = colors.blue }
      highlights["TelescopeMultiIcon"] = { foreground = colors.green }
      highlights["TelescopeMultiSelection"] = { bold = true }
    end,
  })

  tokyonight.load()
end

return spec
```

```lua
-- telescope

local spec = {
  "nvim-telescope/telescope.nvim",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "nvim-tree/nvim-web-devicons",
  },
}

function spec.config()
  local telescope = require("telescope")
  local themes = require("telescope.themes")
  local actions = require("telescope.actions")
  local builtin = require("telescope.builtin")

  telescope.setup({
    defaults = vim.tbl_deep_extend("force", themes.get_dropdown(), {
      prompt_prefix = vim.g.icons.widget.inline.ChevronRight .. " ",
      selection_caret = "  ",
      multi_icon = vim.g.icons.widget.inline.Check .. " ",
    }),
    pickers = {
      find_files = {
        hidden = true,
      },
      live_grep = {
        disable_coordinates = true,
      },
      buffers = {
        sort_lastused = true,
        initial_mode = "normal",
        mappings = {
          n = {
            dd = actions.delete_buffer,
          },
        },
      },
    },
  })

  local function map(left, right, ...)
    local parameters = { ... }
    vim.keymap.set("n", left, function() right(unpack(parameters)) end)
  end

  map("<leader>fr", builtin.resume)
  map("<leader>ft", builtin.filetypes)
  map("<leader>ff", builtin.find_files)
  map("<leader>fw", builtin.live_grep)
  map("<leader><space>", builtin.buffers)
end

return spec
```

**Comment by yunusey** [comment] 2023-02-22 14:26
Okay, thank you! One thing I saw that maybe the problem. When you say ```require("tokyonight")``` instead of finding the plugin ```tokyonight```, it maybe requiring the same file. For checking this, you can try doing this in your ```tokyonight.lua```:
```lua
print(vim.inspect(tokyonight))
```
Can you upload the output?  (Because it works for me)

**Comment by yunusey** [comment] 2023-02-22 14:32
Or, you can do this:
-- tokyonight

local spec = {
  "folke/tokyonight.nvim",
  priority = 100,
}

function spec.config()
  local tokyonight = require("tokyonight")

  tokyonight.setup({
    style = "night",
    on_highlights = function(highlights, colors)
      highlights["@text.note"] = { bold = true, background = colors.blue2 }
      highlights["@text.todo"] = { bold = true, background = colors.green1 }
      highlights["@text.warning"] = { bold = true, background = colors.yellow }
      highlights["@text.danger"] = { bold = true, background = colors.red1 }

      highlights["NoiceCmdlinePopup"] = { background = colors.bg_float }

      highlights["TelescopePromptPrefix"] = { foreground = colors.blue }
      highlights["TelescopeMultiIcon"] = { foreground = colors.green }
      highlights["TelescopeMultiSelection"] = { bold = true }
    end,
  })

  tokyonight.load()
end

spec.config()

return spec

**Comment by utilyre** [comment] 2023-02-22 15:04
I don't think it's relevant as I use lazy.nvim for plugin management.

**Comment by yunusey** [comment] 2023-02-22 15:19
Mhm, I see. Can you try copying this to your ```tokyonight.lua``` just to make sure that everything is alright?

```lua

-- tokyonight

local spec = {
  "folke/tokyonight.nvim",
  priority = 100,
}

function spec.config()
  local tokyonight = require("tokyonight")

  tokyonight.setup({
    style = "night",
    on_highlights = function(highlights, colors)
      highlights["TelescopePromptPrefix"] = { fg = “#00ff00” } — It should be green right now!
    end,
  })

  tokyonight.load()
end

spec.config()

return spec
```

**Comment by max397574** [comment] 2023-02-22 17:53
this stuff isn't related at all to tokyonight or anything
you can just do `:hi TelescopePromptPrefix` to see that the color is still there

**Comment by dstanberry** [comment] 2023-02-22 18:08
This is reproducible even after lazy configures telescope. Manually executing `vim.api.nvim_set_hl(0,"TelescopePromptPrefix",{fg="#ffab00"})` has no apparent effect.

**Comment by yunusey** [comment] 2023-02-22 21:24
> this stuff isn't related at all to tokyonight or anything you can just do `:hi TelescopePromptPrefix` to see that the color is still there

Honestly, that's the main reason I think there's something wrong with the tokyonight setup. It totally works for me unlike you.

**Comment by max397574** [comment] 2023-02-23 05:31
it has nothing to do with tokyonight

**Comment by max397574** [comment] 2023-02-23 05:33
```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
    vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
    {
        "nvim-telescope/telescope.nvim",
        config = true,
    },
    {
        "nvim-lua/plenary.nvim",
    },
    -- add any other plugins here
}
require("lazy").setup(plugins, {
    root = root .. "/plugins",
})

vim.api.nvim_set_hl(0,"TelescopePromptPrefix",{fg="#ffab00"})
-- add anything else here
```
I can also reproduce it without any colorscheme but I don't want to kill my eyes

**Comment by Conni2461** [comment] 2023-02-23 07:14
please stop discussing about tokyonight. If `:hi TelescopePromptPrefix` shows the correct highlight then we already know its not a configuration issue.

> BTW, this only happens on nvim-nightly.

was the key message. Its an issue with neovim nightly https://github.com/nvim-telescope/telescope.nvim/issues/2399 also confirms this. I dont have time to bisect neovim until sunday. I dont see anything [here](https://github.com/neovim/neovim/issues/14090) that indicates a breaking change that affects this highlighting.

If this issue is a deal breaker for you, i suggest you just go back to neovim 0.8.3

**Comment by Conni2461** [comment] 2023-02-26 10:45
https://github.com/nvim-telescope/telescope.nvim/pull/2403 should fix the issue. i've found the neovim commit that introduces this issue and i plan to open a Issue upstream with a minimal repro and ask if this is now the expected behavior. 

Can someone confirm that this issue is fixed with the proposed changes? after that i would merge

**Comment by max397574** [comment] 2023-02-26 11:16
this fixes it

**Closed** 2023-02-26 12:26 UTC
Labels: bug
