### ISSUE TITLE
Error executing vim.schedule lua callback: utils.lua:136: Invalid window id: 1024

### ISSUE THREAD

**Issue by fcying** [nvim-telescope/telescope.nvim#1615] opened 2021-12-20 14:23 UTC
### Description

sometimes I use `Telescope oldfiles`, after input some char, nvim be blocked, use` top` saw nvim cpu 90+%. 
wait several seconds jump error:
```
Error executing vim.schedule lua callback: ...er/opt/telescope.nvim/lua/telescope/previewers/utils.lua:136: Invalid window id: 1024
stack traceback:
[C]: in function 'nvim_win_get_height'
...er/opt/telescope.nvim/lua/telescope/previewers/utils.lua:136: in function 'cb'
 vim.lua:285: in function <vim.lua:285>
```

### Neovim version

```markdown
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

debian 11

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found..

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - WARNING: fd: not found. Install sharkdp/fd for extended capabilities

## ===== Installed extensions =====

## Telescope Extension: `ctags_outline`
  - INFO: No healthcheck provided

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

There is no stable way to reproduce.
some times happen.

### Expected behavior

not blocked nvim.

### Actual behavior

blocked nvim.

### Minimal config

```Lua
local actions = require('telescope.actions')
    local toggle_modes = function()
        local mode = api.nvim_get_mode().mode
        if mode == "n" then
            cmd [[startinsert]]
            return
        elseif mode == "i" then
            cmd [[stopinsert]]
            return
        end
    end
    require('telescope').setup{
        defaults = {
            --horizontal vertical flex center
            layout_strategy='vertical',
            mappings = {
                i = {
                    ["<esc>"] = actions.close,
                    ["<c-j>"] = actions.move_selection_next,
                    ["<c-k>"] = actions.move_selection_previous,
                    ["<tab>"] = toggle_modes,
                    ["<c-s>"] = actions.toggle_selection,
                    ["<C-q>"] = actions.send_to_qflist,
                },
                n = {
                    ["<tab>"] = toggle_modes,
                    ["<c-s>"] = actions.toggle_selection,
                    ["<C-q>"] = actions.send_to_qflist,
                }
            },
        },
        extensions = {
            fzf = {
                fuzzy = true,                    -- false will only do exact matching
                override_generic_sorter = true,  -- override the generic sorter
                override_file_sorter = true,     -- override the file sorter
                case_mode = "smart_case",        -- or "ignore_case" or "respect_case"
            },
            ctags_outline = {
                ctags_opt = {'ctags'}
            }
        }
    }
    require('telescope').load_extension('fzf')
    require('telescope').load_extension('ctags_outline')
```
```

**Comment by l-kershaw** [comment] 2021-12-21 22:48
@fdschmidt93 this seems to be something to do with the preview timeout in `previewers.file_maker`.
It looks like the `winid` that is passed to `set_preview_message` isn't valid, but I can't see a way for this to happen.

Any ideas what could cause this?
We could just add a check for `winid` being valid in `set_preview_message`, but that seems like it would just make the root cause harder to find, but might be wrong

**Comment by fdschmidt93** [comment] 2021-12-22 11:06
> Any ideas what could cause this?

Not really, wouldn't this mean the preview window is invalid? Something seems rather odd.

> We could just add a check for winid being valid in set_preview_message, but that seems like it would just make the root cause harder to find, but might be wrong

Sure, we could. But I'd much rather prefer having a proper repro with minimal init lua as we provide it.

@fcying can could please try to repro with minimal init lua? This should be triggered whenever you try to preview binaries (or generally non-text files) or extreme large files with eg `:Telescope find_files`.

**Comment by fcying** [comment] 2021-12-24 06:12
@fdschmidt93 I have been testing these days, but no recurrence.
I test with large binary files(Telescope oldfiles), when i preview this files, it will block nvim(cpu90+) several seconds, but not get error.

**Comment by fdschmidt93** [comment] 2021-12-24 08:31
Is telescope up to date? Telescope should time out and show a message that binaries cannot be previewed? What types of files are you attempting to preview?

**Comment by fcying** [comment] 2021-12-26 07:42
> Is telescope up to date?   

 I update telescope everyday.

>Telescope should time out and show a message that binaries cannot be previewed?  

yes, it just spent several seconds and show "Binary cannot be previewed in " in File Preview.
not get `Invalid window id` error message.

>What types of files are you attempting to preview?

one 40M binary(just for test).

**Comment by fdschmidt93** [comment] 2021-12-26 10:32
> one 40M binary(just for test).

That's not what I meant. We use `file` to attempt to determine whether the file to be previewed is a binary. In case it's detected as a binary, it de facto does not attempt to read the file for previewing, so any blockage here should not be caused by telescope per se. So what kinds of files are you attempting to preview? Furthermore, I'm kind of wondering why 40M binaries should be in `:Telescope oldfiles`.

Please provide full information (what files exactly are opened, how to repro with minimal init lua). Otherwise, we're both just dancing around the issue and getting rather frustrated. I'm afraid the information provided is insufficient to guide to a resolution.

**Comment by fcying** [comment] 2021-12-26 13:50
> That's not what I meant. We use file to attempt to determine whether the file to be previewed is a binary. In case it's detected as a binary, it de facto does not attempt to read the file for previewing, so any blockage here should not be caused by telescope perse

my test file, when I use `oldfiles` or `find_files` select this file, nvim block several seconds
```
$ file ccls
ccls: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=f57429a031f745a0a15feeee4d1155fea8d59962, for GNU/Linux 3.2.0, with debug_info, not stripped
```

> Furthermore, I'm kind of wondering why 40M binaries should be in :Telescope oldfiles.
just for test.  When I get the error(`Invalid window id`), the test file not in my `oldfiles`. 
I saw `can could please try to repro with minimal init lua? This should be triggered whenever you try to preview binaries (or generally non-text files) or extreme large files with eg :Telescope find_files.`, 
so I use mini init.lua and add one big file to test, but not reproduce the error (`Invalid window id`), only reproduce nvim be blocked.

**Comment by fdschmidt93** [comment] 2021-12-29 13:05
I close this since there's now been another issue opened with thankfully a much more detailed description of what steps are taken to arrive at an error.

**Closed by fdschmidt93** 2021-12-29 13:05 UTC
Labels: bug
