### ISSUE TITLE
Telescope result doesn't show

### ISSUE THREAD

**Issue by tea0112** [nvim-telescope/telescope.nvim#2681] opened 2023-09-02 02:33 UTC
### Description

I'm using Alacritty with WSL.
This is my telescope config:
```
local M = {}

local actions = require("telescope.actions")

function M.setup()
    defaults = {
        mappings = {
            i = {
                ["<esc>"] = actions.close,
            },
        },
    }
end

return M
```
![telescope-result-doesnt-show](https://github.com/nvim-telescope/telescope.nvim/assets/35191308/519eedab-3a56-4696-92bc-495ec4b93bb2)

### Neovim version

```markdown
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info
```

### Operating system and version

Windows 10

### Telescope version / branch / rev

telescope 0.1.1 / master / commit  c1a2af0

### checkhealth telescope

```markdown
telescope: health#telescope#check

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.3.1

===== Installed extensions ===== ~
```

### Steps to reproduce

<CMD>Telescope find_files<CR>

### Expected behavior

List file in current directory.

### Actual behavior

No file showed until press <C-p> or <C-n>

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment] 2023-09-02 03:12
This looks like it might be a duplicate of https://github.com/nvim-telescope/telescope.nvim/issues/2667#issuecomment-1694743099

**Closed** 2023-09-02 04:10 UTC
Labels: bug
