### ISSUE TITLE
Live grep not working after last update

### ISSUE THREAD

**Issue by hrqmonteiro** [nvim-telescope/telescope.nvim#1104] opened 2021-08-11 13:24 UTC
![livegrep](https://user-images.githubusercontent.com/17055027/129036623-2bdeb712-349b-4797-9aef-0eab71da51dc.png)

```
[telescope] ^I...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:410: in function <...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:364>[telescope] ^I...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:410: in function <...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:364>
```

**Comment by fdschmidt93** [comment] 2021-08-11 14:04
I cannot reproduce that after updating, TJ just moved all of popup to plenary (#1102) -- have you made sure to have updated both telescope and plenary?

**Comment by hrqmonteiro** [comment] 2021-08-11 14:20
> I cannot reproduce that after updating, TJ just moved all of popup to plenary (#1102) -- have you made sure to have updated both telescope and plenary?

I do a `:PackerUpdate` everyday, so it updated all of that.

And all of the other commands are just fine, only the live_grep is not working.

**Comment by hrqmonteiro** [comment] 2021-08-11 17:28
> Cannot reproduce either (on `live_grep`). Please give a more complete bug report: relevant config, exact steps to reproduce, ...

I am literally just opening nvim on any directory and doing `:Telescope live_greo`, i don't know how i can say more than this...

**Comment by Conni2461** [comment] 2021-08-11 17:48
what clason says. you should fill out the bug template.

Also does `:messages` give us more information? i think we should get a stack trace here

**Comment by alexfertel** [comment] 2021-08-11 18:14
I also experienced a similar issue, but when triggering `find_files`.

```
E5108: Error executing lua ...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:302: attempt to call field 'create' (a nil value) 
```

Would you need me to file a new issue?

**Comment by clason** [comment] 2021-08-11 18:15
If _you_ can fill out the bug template, that would be appreciated.

**Comment by Conni2461** [comment] 2021-08-11 18:16
> I also experienced a similar issue after updating just half an hour ago, but when triggering `find_files`.
> 
> ```
> E5108: Error executing lua ...re/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:302: attempt to call field 'create' (a nil value) 
> ```
> 
> In my case it doesn't even create the popup.
> 
> Would you need me to file a new issue?

You have a different issue make sure plenary is up to date. Like suggested in the first comment

**Comment by alexfertel** [comment] 2021-08-11 18:19
I just run `:PlugUpdate` which updates everything.

**Comment by alexfertel** [comment] 2021-08-11 18:23
I have the latest commit of `plenary`. So, should I file a different issue?

**Comment by Conni2461** [comment] 2021-08-11 18:26
Thats the right commit. After that everything should work.

Your issue and this issue 1104 is not related. Its a different error message.

Does your issue still exist after you reloaded vim? Because i can reproduce it if i checkout a commit prior to `5e5c87f`. If i checkout `5e5c87f` or master, the error disappears

**Comment by alexfertel** [comment] 2021-08-11 18:37
> Does your issue still exist after you reloaded vim?

Yeap, it does.

I just did a fresh install and reloaded nvim and it is still happening.

**Comment by Conni2461** [comment] 2021-08-11 18:48
This is a different issue (because its a different error message and affects all of telescope 1104 only affects live_grep), so you should open a new issue ticket and fill out the bug template. This right here is offtopic

**Comment by bluretrece** [comment] 2021-08-12 02:21
Mine is having issues since the last update as well. But the Picker error is different, though: 
`E5108: Error executing lua ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:302: attempt to call field 'create' (a nil value)`

I tried reinstalling and using vim-plug instead but I got the same error no matter what.

**Comment by hrqmonteiro** [comment] 2021-08-12 13:04
Just cleaned my `.local/share/nvim` folder, started it with a minimal config that contains only packer, telescope and plenary. Same thing happens.

![grep](https://user-images.githubusercontent.com/17055027/129201634-e1579682-d810-4d3d-b0d8-d298a79e6813.png)

**Comment by clason** [comment] 2021-08-12 13:05
You still did not give the full environment (neovim version, Lua(JIT) version, OS, ...) and did not share that "minimal config".

**Comment by hrqmonteiro** [comment] 2021-08-12 13:11
> You still did not give the full environment (neovim version, Lua(JIT) version, OS, ...) and did not share that "minimal config". You're not making it easy for us to help you...

https://github.com/hrqmonteiro/dotfiles/tree/main/.config/nvim

```
VIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/bin/cc -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2  -g -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/neovim-0.5.0/build/config -I/builddir/neovim-0.5.0/src -I/usr/include -I/builddir/neovim-0.5.0/build/src/nvim/auto -I/builddir/neovim-0.5.0/build/include
Compilado por void-buildslave@a-fsn-de

Features: +acl +iconv +tui
See ":help feature-compile"

    arquivo vimrc de sistema: "$VIM/sysinit.vim"
            padrão para $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

I'm on Void Linux.

Telescope and Plenary are on the latest commits, i installed just now.

**Comment by Conni2461** [comment] 2021-08-12 13:13
What does `:messages` return after you closed telescope?

I am 99% sure it will show us the issue. And my guess is that somehow plenary.job can't find ripgrep. Maybe it was accidentally uninstalled.

So open `live_grep` type one char, close telescope `:messages`

**Comment by clason** [comment] 2021-08-12 13:14
That's not a minimal config... Try with this:

```lua
 vim.cmd [[set runtimepath=$VIMRUNTIME]]
 vim.cmd [[set packpath=/tmp/nvim/site]]
 local package_root = '/tmp/nvim/site/pack'
 local install_path = package_root .. '/packer/start/packer.nvim'
 local function load_plugins()
   require('packer').startup {
     {
       'wbthomason/packer.nvim',
       {
         'nvim-telescope/telescope.nvim',
         requires = {
           'nvim-lua/plenary.nvim',
           { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
         },
       },
       -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
     },
     config = {
       package_root = package_root,
       compile_path = install_path .. '/plugin/packer_compiled.lua',
       display = { non_interactive = true },
     },
   }
 end
 _G.load_config = function()
   require('telescope').setup()
   require('telescope').load_extension('fzf')
   -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
 end
 if vim.fn.isdirectory(install_path) == 0 then
   print("Installing Telescope and dependencies. This may take a while!")
   vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
 end
 load_plugins()
 require('packer').sync()
 vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment] 2021-08-12 13:16
yeah we can't find `rg` make sure its installed and in your path

**Comment by hrqmonteiro** [comment] 2021-08-12 13:17
> That's not a minimal config... Try with this (save as `minimal.lua` and run with `nvim -nu minimal.lua`):
> 
> ```lua
>  vim.cmd [[set runtimepath=$VIMRUNTIME]]
>  vim.cmd [[set packpath=/tmp/nvim/site]]
>  local package_root = '/tmp/nvim/site/pack'
>  local install_path = package_root .. '/packer/start/packer.nvim'
>  local function load_plugins()
>    require('packer').startup {
>      {
>        'wbthomason/packer.nvim',
>        {
>          'nvim-telescope/telescope.nvim',
>          requires = {
>            'nvim-lua/plenary.nvim',
>            { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
>          },
>        },
>        -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
>      },
>      config = {
>        package_root = package_root,
>        compile_path = install_path .. '/plugin/packer_compiled.lua',
>        display = { non_interactive = true },
>      },
>    }
>  end
>  _G.load_config = function()
>    require('telescope').setup()
>    require('telescope').load_extension('fzf')
>    -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
>  end
>  if vim.fn.isdirectory(install_path) == 0 then
>    print("Installing Telescope and dependencies. This may take a while!")
>    vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
>  end
>  load_plugins()
>  require('packer').sync()
>  vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
> ```

Still not working.
And my config literally just loaded packer, telescope and plenary, the only differente to this one is that it loaded on separate files.

Here's when i opened with your `minimal.lua`:

![grep](https://user-images.githubusercontent.com/17055027/129203447-53764cfb-c5fb-40f1-96f8-951309dc2120.png)

**Comment by hrqmonteiro** [comment] 2021-08-12 13:19
> yeah we can't find `rg` make sure its installed and in your path

![grep](https://user-images.githubusercontent.com/17055027/129203732-db5cc037-27e4-4757-af49-222b70473c62.png)

**Comment by hrqmonteiro** [comment] 2021-08-12 13:21
![grep](https://user-images.githubusercontent.com/17055027/129204099-3c863eac-e02b-4bfb-a3bd-83f46f4578b6.png)

Rg is working fine with Fzf

**Comment by Conni2461** [comment] 2021-08-12 13:22
Log clearly indicates: 
```
[telescope] [WARN  10:14:17] ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:415: Failed wit
h msg:  .../site/pack/packer/start/plenary.nvim/lua/plenary/job.lua:105: rg: Executable not found
```

but hey we can ask nvim if it can find rg. `lua print(vim.fn.executable("rg"))` should return 1

**Comment by 0x8000-0000** [comment] 2021-08-13 03:52
I am having similar problem with top of the tree telescope and plenary, but on ":Telescope find_files" ; I only get the icons, but not the file names or the highlighted portion.

**Comment by clason** [comment] 2021-08-13 06:40
So it's not a similar problem at all. (Rather it's a duplicate of #1107.) Please don't hijack issues with your own problems!

**Comment by joacohoyos** [comment] 2021-08-25 00:03
I am having the same problems, and it almost started at the same time than OP.

I tried running :lua print(vim.fn.executable("rg")) and it returned 1, I updtade ripgrep to the last version

I tried running with minimal.lua as it was said in a previous comment and after closing telescope and running :messages it return nothing.

If I can help in trying to reproduce the bug I am more  than happy to help

**Comment by zouzonghua** [comment] 2021-08-25 10:42
I also had the same problem but I tried to run `brew install ripgrep` and everything was normal . Maybe you can try

**Comment by mrusme** [comment] 2021-09-04 00:57
Same issue here, Telescope opens but no matter what I do I don't get anything suggested. `:messages` shows this after Telescope opened once:

``
[telescope] [WARN  19:55:00] (tail call):-1: Finder failed with msg:  attempt to yield across metameth
od/C-call boundary
[telescope] [WARN  19:55:02] (tail call):-1: Finder failed with msg:  attempt to yield across metameth
od/C-call boundary
[telescope] [WARN  19:55:02] (tail call):-1: Finder failed with msg:  attempt to yield across metameth
od/C-call boundary
[telescope] [WARN  19:55:02] (tail call):-1: Finder failed with msg:  attempt to yield across metameth
od/C-call boundary
[telescope] [WARN  19:55:02] (tail call):-1: Finder failed with msg:  attempt to yield across metameth
od/C-call boundary
[telescope] [WARN  19:55:02] (tail call):-1: Finder failed with msg:  attempt to yield across metameth
od/C-call boundary
[telescope] [WARN  19:55:02] (tail call):-1: Finder failed with msg:  attempt to yield across metameth
od/C-call boundary
[telescope] [WARN  19:55:02] (tail call):-1: Finder failed with msg:  attempt to yield across metameth
od/C-call boundary
```

Running:

```
NVIM v0.5.0-dev+1449-gbdf3df402-dirty
Build type: Gentoo
Lua 5.1
Compilation: /usr/bin/x86_64-pc-linux-gnu-gcc -O2 -pipe -march=znver3 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/config -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999/src -I/usr/include -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/src/nvim/auto -I/var/tmp/portage/app-editors/neovim-9999/work/neovim-9999_build/include
Compiled by portage@localhost

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "/etc/vim/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

`which rg` returns `/usr/bin/rg`.

**Comment by fdschmidt93** [comment] 2021-09-10 08:14
@mrusme see #1174 your nvim is not built with luajit but lua 5.1. Please subscribe to that issue.

I'm closing this since the original issue is solved, others are partly no telescope issuss, and the thread was hijacked too often.

**Closed by fdschmidt93** 2021-09-10 08:14 UTC
Labels: bug, Missing bug template
