### ISSUE TITLE
Does telescope.nvim depend on LuaJIT?

### ISSUE THREAD

**Issue by pearzt** [nvim-telescope/telescope.nvim#2644] opened 2023-08-08 14:02 UTC
### Description

The bug has been principally reported here: https://github.com/nvim-telescope/telescope.nvim/issues/1174
The solution there seems to be to just rebuild Neovim using LuaJIT. Apparently, this solves the problem due to LuaJIT's 'resumable VM' feature.

However, just switching to LuaJIT does not work for me for architectural reasons. I would therefore like to clarify whether this project implicitly depends on LuaJIT (in contrast to plain Lua 5.1, which I am using). If so, this requirement should be documented IMHO. If telescope.nvim aims to be compatible to all platforms that are supported by Neovim, this should be treated as a bug report.

### Neovim version

```markdown
NVIM v0.9.1
Build type: Release
Lua 5.1
```

### Operating system and version

ManjaroLinux 23.0.0 (Linux 6.1.41-1-MANJARO)

### Telescope version / branch / rev

telescope v0.1.2

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions =====

Telescope Extension: `cmake_tools`
- No healthcheck provided
```

### Steps to reproduce

1. `nvim -c ":lua require('telescope.builtin').find_files{}" -V1log.log`
2. Inspect `log.log`

### Expected behavior

`find_files` shows files and provides search functionality.

### Actual behavior

`find_files` does not show any files. A search string can be entered, but to no effect. 
Error message in log:
`[telescope] [WARN  15:17:22] (tail call):-1: Finder failed with msg:  attempt to yield across metamethod/C-call boundary`

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment] 2023-10-11 10:18
Ye we kinda currently depend on luajit, basically since we implement the usage of `plenary.async-v2` and i dont think we will change this anytime soon as the lua 5.1 users are not that common. I am sorry, i just dont have the time to support such a unique usecase.

Its probably just easier to wait for an official `nvim.async` module even if it takes a couple of years.

> If so, this requirement should be documented IMHO

Yeah you can make the argument that this should be documented and ill do that, but i like to make the argument, that issues are in some why a form of documentation. There is no need for me to document every single limitation of a feature after a new issue is opened.

**Comment by Conni2461** [comment] 2023-10-11 10:30
its now documented, so i would close this as duplicate of https://github.com/nvim-telescope/telescope.nvim/issues/1174

**Closed by Conni2461** 2023-10-11 10:30 UTC
Labels: bug
