### ISSUE TITLE
Exit window command `:q` doesn't close the buffer

### ISSUE THREAD

**Issue by Tal500** [nvim-telescope/telescope.nvim#2873] opened 2024-01-16 13:45 UTC
Exit window command `:q` doesn't close the buffer of telescope dialogs: "E37: No write since last change (add ! to override)"
So our valid options are only `escape/q/:q!`.

It would be nice just to just have it supported via `:q`, and this potentially affect other custom keybinding of nvim distros, see AstroNvim/AstroNvim#2422 for example.

**Comment by mehalter** [comment] 2024-01-16 13:47
Also just a heads up @Tal500 chances are they won't see this as a bug given your issue is basically a duplicate of: https://github.com/nvim-telescope/telescope.nvim/issues/628

**Comment by mehalter** [comment] 2024-01-16 13:49
I'm saying it's possible, idk if the maintainers will find it necessary

**Comment by jamestrew** [comment] 2024-01-18 03:44
You can only close buffers with `buftype = 'prompt'` with `:q!`. This is a vim limitation. My gut feeling is that this isn't a bug.

Hooking into `BufLeave` (and related) events and forcing a bufdelete doesn't work pretty sure.
I *guess* we can perpetually set the `modified` state to false every time the buffer is modified. But this feels stupid.
I don't know, open to ideas but I'm convinced this even needs to be "fixed".

**Comment by Tal500** [comment] 2024-01-18 09:21
> You can only close buffers with `buftype = 'prompt'` with `:q!`. This is a vim limitation. My gut feeling is that this isn't a bug.
> 
> Hooking into `BufLeave` (and related) events and forcing a bufdelete doesn't work pretty sure. I _guess_ we can perpetually set the `modified` state to false every time the buffer is modified. But this feels stupid. I don't know, open to ideas but I'm convinced this even needs to be "fixed".

Thanks for the reply!

OK so here is my noob question, if it isn't acceptable universally - do you think it would make sense for my local config(and anyone else who wants that) - to remap ":q" to ":q!" whenever `buftype = 'prompt'` (the implementation of this is by setting a lua function checking it somehow as far as I understand)?

**Comment by Conni2461** [comment] 2024-01-18 09:34
You should continue to close telescope using `require"telescope.actions".close()` because we actually have a cleanup step, like all floating windows and more.

Also please next time, fill out the issue template, not just delete everything in the textarea!

closing as this is something i think we will not address here

**Closed by Conni2461** 2024-01-18 09:34 UTC
Labels: enhancement
