### ISSUE TITLE
prefix icon loses highlighting after running `dd` command

### ISSUE THREAD

**Issue by rockyzhang24** [nvim-telescope/telescope.nvim#1674] opened 2022-01-10 18:27 UTC
### Description

The prompt_prefix will be deleted together after running `dd` in normal mode.

### Neovim version

```markdown
NVIM v0.7.0-dev+797-gb218d02c4
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by rockyzhang@mbp2021
```

### Operating system and version

macOS 12.1 (the latest)

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.1

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

With the default config in README, open any builtin picker. Then type something after the prompt,  and then press `<Esc>` to go to normal mode. Now run `dd`, the prefix_prompt will be deleted together. 

### Expected behavior

I think after `dd`, the prompt_prefix should preserve there. I also tried other normal mode commands like `ciw` and I see that the prompt_prefix is not deleted. It seems the issue is just for `dd` command. 

### Actual behavior

https://user-images.githubusercontent.com/11582667/148818946-9980c713-75be-47ae-a69c-a25b92e354a2.mov

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment] 2022-01-10 20:01
Would say expected behavior of the prompt filetype. If you disagree, open an issue upstream (probably in vim).

1. Open a new buffer (either in neovim (latest nightly) or in vim (tested 8.2.3848))
2. run `set buftype=prompt`
3. go into insert mode
4. type something
5. dd
6. icon is gone.
7. back to insert, icon is back

The only bug we have here is that the icon is no longer colored. We should look into this.

**Comment by yanzhang0219** [comment] 2022-01-10 20:42
Wow so this is a missing behavior from vim itself. Sorry I was not familiar with the buffer with prompt type. Thank you and I will open an issue there.

**Comment by yanzhang0219** [comment] 2022-01-11 17:44
UPDATE: 
I opened an [issue](https://github.com/vim/vim/issues/9502) on the upstream vim and Bram said that's the normal behavior for `dd`.

**Comment by fdschmidt93** [comment] 2022-05-22 12:58
I think this is resolved as intended upstream behavior. Closing.

**Closed by fdschmidt93** 2022-05-22 12:58 UTC
Labels: bug
