### ISSUE TITLE
configurable timeout for `:Telescope git_status`

### ISSUE THREAD

**Issue by sodiumjoe** [nvim-telescope/telescope.nvim#2714] opened 2023-09-22 23:22 UTC
**Is your feature request related to a problem? Please describe.**
I work in a very large git repo, in which git operations often take a long time. This often causes `:Telescope git_status` to time out.

**Describe the solution you'd like**
A configurable timeout setting for the `git_status` telescope builtin.

**Describe alternatives you've considered**
I couldn't think of any other alternatives.

**Additional context**

**Comment by Conni2461** [comment] 2023-10-11 13:02
alternative, process git commands async

**Comment by kevin071586** [comment] 2023-11-09 19:49
I'd also like to see this.  Network latency is the source in my case so would also need the configurable timeout option.

My `:Telescope git_status` command times out after 5000ms and I can't find any way to configure it otherwise.

**Comment by lrfurtado** [comment] 2023-11-09 22:30
![image](https://github.com/nvim-telescope/telescope.nvim/assets/943194/b461defd-8eed-47cd-9ca4-3366c22c5028)

plenary seems to accept a timeout param to the sync job call. We could add it as a param to all git commands

**Comment by lrfurtado** [comment] 2023-11-09 22:32
:Telescope git_status timeout=100000 would that be accessible the implementation seems straight forward

**Comment by lrfurtado** [comment] 2023-11-10 00:02
@kevin071586 can you give above a try ? it seems to do the trick for me. I created a git wrapper that added latency for testing, and it seem to have worked fine for me.

**Comment by lrfurtado** [comment] 2023-11-10 00:03
@sodiumjoe can you trye the above as well ?

**Comment by Conni2461** [comment] 2023-11-10 08:05
again timeout would be fine, but id rather think we should probably just process this with `finders.new_oneshot_job` (and the other git commands as well, if possible)

**Comment by lrfurtado** [comment] 2023-11-10 14:08
@Conni2461 I am just starting with Lua so that looked easier to implement, let me try looking at your other suggestion with new_oneshot_job to see if I can get something working.

**Comment by kevin071586** [comment] 2023-11-13 14:42
> @kevin071586 can you give above a try ? it seems to do the trick for me. I created a git wrapper that added latency for testing, and it seem to have worked fine for me.

@lrfurtado thanks, this is great.  I manually copied your changes into my ~/.local/share/nvim/lazy/ directory and the command `Telescope git_status timeout=100000` worked perfectly.  I'll just reconfigure my bindings to do this by default, might be worth slightly upping the default timeout though.

I'm just trying neovim for the first time and used NvChad to get a decent C++ setup "out of the box" so didn't install Telescope directly.  I didn't see an easy way to simply "Cherry-pick" your changes to my installation so directly copied line by line.  Is there an easier way?

@Conni2461 I'm happy with alternative solutions as well and can't really speak to what is best, so I'd defer to you all if the `finders.new_oneshot_job` is a more appropriate solution.

**Comment by lrfurtado** [comment] 2023-11-14 01:50
@Conni2461  is the diff below in the direction you were looking for 
![image](https://github.com/nvim-telescope/telescope.nvim/assets/943194/8b342db3-17fc-4176-90cf-aba8ea37c01d)

I was not able to figure a nice way of porting the behavious of displaying the messages when there were no changes that was done on the code block below:

![image](https://github.com/nvim-telescope/telescope.nvim/assets/943194/99005aa1-6d71-4695-aad8-adfb93dcc260)


any suggestions ?

**Comment by lrfurtado** [comment] 2023-11-14 02:26
it seams to work with the caveat above.

**Comment by lrfurtado** [comment] 2023-11-14 02:28
@kevin071586 cna you test the commit above which uses the approach suggested by @Conni2461

**Comment by kevin071586** [comment] 2023-11-16 16:17
@lrfurtado Thanks, yes, I can confirm that [e5f0953](https://github.com/lrfurtado/telescope.nvim/commit/e5f09538eb0d2f379164810f7766ded31bbb287b) fixes the issue as well.

Additionally I spent the time to answer my own question, it seems like the .local/share/nvim/lazy/ directories are each git repos (didn't realize this since I set up my Neovim environment by installing NvChad).  In any case, I was able to easily cherry-pick the commit into the share/nvim/lazy/telescope.nvim repo in case others come along in the future with the same question.

**Comment by lrfurtado** [comment] 2023-11-17 05:54
@Conni2461 @jamestrew  created a pull request to address this issue with the apporach suggested on the issue.  Please let me know the PR is acceptable, happy to do any changes needed.

**Comment by Conni2461** [comment] 2023-11-24 14:58
can you guys test: https://github.com/nvim-telescope/telescope.nvim/pull/2789 if that fixes your issues?

**Comment by lrfurtado** [comment] 2023-11-24 19:32
@kevin071586 can you test the PR it would be ultra helpful.

**Comment by kevin071586** [comment] 2023-12-05 16:19
@lrfurtado sorry, been away - I just checked out the #2789 and the git_status command works.

**Comment by jamestrew** [comment] 2023-12-06 03:52
merged #2789
closing. thanks guys.

**Closed by jamestrew** 2023-12-06 03:52 UTC
Labels: enhancement
