### ISSUE TITLE
Freeze my computer after Live Grep with telescope in a project with assets folder

### ISSUE THREAD

**Issue by jjairojr** [nvim-telescope/telescope.nvim#2489] opened 2023-05-02 21:59 UTC
### Description

I've a React project with assets folder, when i search for a Live Grep (<leader>fs) and i type like "a", sort a thousand files and the my computers freeze and i need to restart, i remove the assets folder just for test and now works fine, how can i ignore the assets folder in my searchs ?

Please help me

Thanks <3

`telescope.lua `file
```
-- import telescope plugin safely
local telescope_setup, telescope = pcall(require, "telescope")
if not telescope_setup then
	return
end

-- import telescope actions safely
local actions_setup, actions = pcall(require, "telescope.actions")
if not actions_setup then
	return
end

-- configure telescope
telescope.setup({

	-- configure custom mappings
	defaults = {
		file_ignore_patterns = {
			"node_modules",
			"%.svg",
			".png",
			".jpg",
			".jpeg",
			".mp4",
			".ico",
			".otf",
			".icns",
			".mp3",
			".gif",
			".wav",
			"assets/**",
			"assets/",
			"*/assets",
		},
		mappings = {
			i = {
				["<C-k>"] = actions.move_selection_previous, -- move to prev result
				["<C-j>"] = actions.move_selection_next, -- move to next result
				["<C-q>"] = actions.send_selected_to_qflist + actions.open_qflist, -- send selected to quickfixlist
			},
		},
	},
})

telescope.load_extension("fzf")
```

### Neovim version

```markdown
NVIM v0.10.0-dev-219+g3287fc2ba
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS Venture 13.0

### Telescope version / branch / rev

new one

### checkhealth telescope

```markdown
telescope: health#telescope#check

- WARNING vim.health.report_start() is deprecated, use vim.health.start() instead. :help |deprecated|
  This feature will be removed in Nvim version 0.11

Checking for required plugins ~
- WARNING vim.health.report_ok() is deprecated, use vim.health.ok() instead. :help |deprecated|
  This feature will be removed in Nvim version 0.11
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured
```

### Steps to reproduce

create a assets folder with a lot of imgs, svgs, pngs, mp3.

### Expected behavior

dont freeze my computer

### Actual behavior

dont search in this folders

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment] 2023-05-02 23:19
I think this is a duplicate of this issue: https://github.com/nvim-telescope/telescope.nvim/issues/2482#issuecomment-1528053505
Try the vimgrep args in the comment linked and see if that helps. I've already created a PR https://github.com/nvim-telescope/telescope.nvim/pull/2488

**Comment by jamestrew** [comment] 2023-05-07 05:02
should be fixed on master now.

**Closed** 2023-06-13 02:17 UTC
Labels: bug
