### ISSUE TITLE
Using vim buffers for preview

### ISSUE THREAD

**Issue by tami5** [nvim-telescope/telescope.nvim#257] opened 2020-11-17 12:08 UTC
> @Conni2461 : But we can also use less if only cat is installed, so people without bat can also scroll.......
Or we just move completely to vim buffers, like the current previewer for tags. But we than have to implement scroll for vim buffers.
> Opinions?

_Originally posted by @Conni2461 in https://github.com/nvim-telescope/telescope.nvim/pull/216#discussion_r525067979_

**Comment by tami5** [comment] 2020-11-17 12:09
@Conni2461 the preview for tags feels really light (no more flickering when switch between results for the same file) and highlights correctly too. I think vim buffers should be used for everything else, don't you think @tjdevries?.

I believe anything that let us to replace external dependencies will always be better for performance and stability .

**Comment by Conni2461** [comment] 2020-11-17 12:37
Kinda duplicate of #206. But we can keep it around.

**Closed** 2020-12-09 15:58 UTC
Labels: discussion
