### ISSUE TITLE
Since #544c5ee opening a file causes neovim to enter insert mode after CursorHold

### ISSUE THREAD

**Issue by ten3roberts** [nvim-telescope/telescope.nvim#1912] opened 2022-05-03 08:37 UTC
### Description

When using telescope find_files and opening a file, insert mode will be entered after a short delay.

The issue is introduced in 544c5ee40752ac5552595da86a62abaa39e2dfa9.

### Neovim version

```markdown
NVIM v0.8.0-dev+113-g46734cf7c                                                                                                                                                                  
Build type: RelWithDebInfo                                                                                                                                                                      
LuaJIT 2.1.0-beta3
```

### Operating system and version

Linux Fedora 35

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====

## Telescope Extension: `dap`
  - INFO: No healthcheck provided

## Telescope Extension: `file_browser`
  - INFO: No healthcheck provided

## Telescope Extension: `fzy_native`
  - INFO: No healthcheck provided

## Telescope Extension: `harpoon`
  - INFO: No healthcheck provided

## Telescope Extension: `project`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. `nvim -nu scripts/minimal_init.vim
2. `:Telescope find_files`
3. Open any file
4. FIle opens, and after half a second insert mode is entered

### Expected behavior

Insert mode is not entered.

This issue does not happen if a file is opened through f.g; `:edit CONTRIBUTING.md`

### Actual behavior

![Screenshot from 2022-05-03 10-35-51](https://user-images.githubusercontent.com/25723553/166425230-2d4a2168-eee3-4a0a-863e-820618e1bd21.png)

Insert mode is entered

### Minimal config

```Lua
See https://github.com/nvim-telescope/telescope.nvim/blob/master/scripts/minimal_init.vim
```

**Comment by fdschmidt93** [comment] 2022-05-03 08:42
I cannot reproduce on `nvim-master` or `nvim-stable` with our `minimal_init.lua` from the bug template

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      {
        "nvim-telescope/telescope.nvim",
        requires = {
          "nvim-lua/plenary.nvim",
          { "nvim-telescope/telescope-fzf-native.nvim", run = "make" },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require("telescope").setup()
  require("telescope").load_extension "fzf"
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing Telescope and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

(assuming here `telescope-master` is affected just as well)

**Comment by ten3roberts** [comment] 2022-05-03 08:49
Alright, your above configuration does not reproduce the issue. I used the minimal_init.vim script. The difference is that `~/.local/share/site` is sourced.

So it must be some other plugin which has a autocommand or alike on a buffer with a buftype, like telescope.

The issue only happens after https://github.com/nvim-telescope/telescope.nvim/commit/544c5ee40752ac5552595da86a62abaa39e2dfa9, both before and after updating all other plugins.

I will lock into my plugins and the changes.

Thanks for a quick reply

**Comment by lenguyenthanh** [comment] 2022-05-03 14:30
I also have a problem with the latest commit.
Whenever I run Telescope command it looks like this:

<img width="711" alt="Screen Shot 2022-05-03 at 16 25 17" src="https://user-images.githubusercontent.com/437967/166472446-007e5eba-2d8e-43dd-bd65-5f020465eead.png">

here is the checkhealth:

```telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====

## Telescope Extension: `frecency`
  - INFO: No healthcheck provided

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `gradle`
  - INFO: No healthcheck provided

## Telescope Extension: `heading`
  - INFO: No healthcheck provided

## Telescope Extension: `luasnip`
  - INFO: No healthcheck provided

## Telescope Extension: `metals`
  - INFO: No healthcheck provided

## Telescope Extension: `neoclip`
  - INFO: No healthcheck provided

## Telescope Extension: `scaladex`
  - INFO: No healthcheck provided
```

**Comment by fdschmidt93** [comment] 2022-05-03 14:48
No hijacking of other issues; the original issue is an entirely different problem. Please open a new issue with proper repro as otherwise it's very difficult to help you.

**Comment by fdschmidt93** [comment] 2022-05-03 14:58
My hunch is you will find that most likely it works just fine with `minimal_init.lua`.

If that proves true, please bisect your config until we've found what causes it too be incorrect.

As a wild guess, we rely on the fact that `<ESC>` leaves from any other mode into normal mode and that `:` goes to the command line.

**Comment by lenguyenthanh** [comment] 2022-05-03 15:04
Yes, wow, you're right. I remap `:` vs `;`, and it causes this problem. Do we have any quickfix for this? Because I quite like this remap :(

**Comment by fdschmidt93** [comment] 2022-05-03 15:38
There is no quickfix I'm afraid, please stay on the latest working commit. We'll do our best to find a solution asap for this.

**Comment by tjdevries** [comment] 2022-05-03 15:42
> My hunch is you will find that most likely it works just fine with `minimal_init.lua`.
> 
> If that proves true, please bisect your config until we've found what causes it too be incorrect.
> 
> As a wild guess, we (currently sort of have to) rely on the fact that `<ESC>` leaves from any other mode into normal mode and that `:` goes to the command line.

where do we rely on that?

**Comment by lenguyenthanh** [comment] 2022-05-03 15:48
> where do we rely on that?

I believe here: https://github.com/nvim-telescope/telescope.nvim/commit/e454a0ad37ba72a14bebe516f99935c16f33ca50#diff-9ac2063a221b713185ddb6df3157cf01edf3b12894c2ae984e14250bf16ebd89R449

**Comment by johnmathews** [comment] 2022-05-03 16:00
I have the same issue as @lenguyenthanh . I also remap `;` and `:`.

**Comment by max397574** [comment] 2022-05-03 16:01
should I open an issue for this rq?

**Comment by lenguyenthanh** [comment] 2022-05-03 16:04
My solution now is hijack the code and change this line: https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/pickers.lua#L449
=> `local cmd = ";startinsert!|call histdel('cmd', -1)|echon ''<CR>"`

**Comment by lenguyenthanh** [comment] 2022-05-03 16:05
I'll create an issue for this in case of other people also have this remap.

**Comment by fdschmidt93** [comment] 2022-05-03 16:07
> can we use nvim_feedkeys instead?

No, I'll elaborate asap. On mobile atm.

**Comment by Conni2461** [comment] 2022-05-04 14:51
Coming back to the original issue reported from @ten3roberts This should be fixed with https://github.com/nvim-telescope/telescope.nvim/pull/1918

Can you validate this?

**Comment by ten3roberts** [comment] 2022-05-04 19:16
Yes, PR #1918 does fix my original issue.

Though I have also found another cause for it.

Removing https://github.com/stevearc/stickybuf.nvim and entering a buffer using telescope does not seem to replicate the behavior.

**Closed** 2022-05-05 08:05 UTC
Labels: bug
