### ISSUE TITLE
Buffers opened via sourcing a session file aren't listed in `:Telescope buffers`

### ISSUE THREAD

**Issue by noomly** [nvim-telescope/telescope.nvim#854] opened 2021-05-21 14:06 UTC
When sourcing a session file created via `:mksession <filename>`, the different opened files don't show up in Telescope's buffer list, except for the currently visible buffer. To make them appear on the list I have to manually cycle through each one of them first.

**Expected Behavior**: All opened files should be available in Telescope's buffer list without having to manually cycle through each of them.

**Steps to reproduce**:

1. `nvim a bunch of files`
2. `:mksession my_session`
3. close neovim
4. open neovim again but without any arguments this time
5. `:source my_session`
6. `:Telescope buffers`

The list should contains files: `a`, `bunch`, `of` and `files`. Instead it initially only contains file `a`.

- neovim version: `v0.5.0-dev+1339-g5d9c56012`
- Telescope commit: `69eb5ea`

**Comment by smithbm2316** [comment] 2021-05-21 17:50
There is an option to enable this: lua require'telescope.builtin'.buffers{ show_all_buffers = true } or Telescope buffers show_all_buffers=true
It should be default, it's in talks to make that happen. Its requested here: #415 (comment)

This is also a duplicate of #368, #338 and more, so I'm going to close this. Feel free to reopen if you have any other issues or questions!

**Closed** 2021-05-21 17:51 UTC
Labels: bug, duplicate

**Comment by noomly** [comment] 2021-05-21 20:01
Oh I wasn't aware of this! It doesn't appear on the help page. I'm sorry I didn't spot the other issues.

By the way, when trying to troubleshoot this issue I tried to run `:Telescope buffers help` and got the following error:

```
E5108: Error executing lua ...lugged/telescope.nvim/lua/telescope/_extensions/init.lua:11: This extension doesn't exist or is not installed: buffers                              
module 'telescope._extensions.buffers' not found:
        no field package.preload['telescope._extensions.buffers']
        no file './telescope/_extensions/buffers.lua'
        no file '/usr/share/luajit-2.0.5/telescope/_extensions/buffers.lua'
        no file '/usr/local/share/lua/5.1/telescope/_extensions/buffers.lua'
        no file '/usr/local/share/lua/5.1/telescope/_extensions/buffers/init.lua'
        no file '/usr/share/lua/5.1/telescope/_extensions/buffers.lua'
        no file '/usr/share/lua/5.1/telescope/_extensions/buffers/init.lua'
        no file './telescope/_extensions/buffers.so'
        no file '/usr/local/lib/lua/5.1/telescope/_extensions/buffers.so'
        no file '/usr/lib/lua/5.1/telescope/_extensions/buffers.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './telescope.so'
        no file '/usr/local/lib/lua/5.1/telescope.so'
        no file '/usr/lib/lua/5.1/telescope.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```

Should I open a new issue?

**Comment by smithbm2316** [comment] 2021-05-21 21:01
> Oh I wasn't aware of this! It doesn't appear on the help page. I'm sorry I didn't spot the other issues.

No worries, they get buried really easily. Honestly GitHub's search for issues and PRs is terrible, I can hardly ever find the issues I'm looking for on new or existing projects lol.

> By the way, when trying to troubleshoot this issue I tried to run `:Telescope buffers help` and got the following error:
> 
> ```
> E5108: Error executing lua ...lugged/telescope.nvim/lua/telescope/_extensions/init.lua:11: This extension doesn't exist or is not installed: buffers                              
> module 'telescope._extensions.buffers' not found:
>         no field package.preload['telescope._extensions.buffers']
>         no file './telescope/_extensions/buffers.lua'
>         no file '/usr/share/luajit-2.0.5/telescope/_extensions/buffers.lua'
>         no file '/usr/local/share/lua/5.1/telescope/_extensions/buffers.lua'
>         no file '/usr/local/share/lua/5.1/telescope/_extensions/buffers/init.lua'
>         no file '/usr/share/lua/5.1/telescope/_extensions/buffers.lua'
>         no file '/usr/share/lua/5.1/telescope/_extensions/buffers/init.lua'
>         no file './telescope/_extensions/buffers.so'
>         no file '/usr/local/lib/lua/5.1/telescope/_extensions/buffers.so'
>         no file '/usr/lib/lua/5.1/telescope/_extensions/buffers.so'
>         no file '/usr/local/lib/lua/5.1/loadall.so'
>         no file './telescope.so'
>         no file '/usr/local/lib/lua/5.1/telescope.so'
>         no file '/usr/lib/lua/5.1/telescope.so'
>         no file '/usr/local/lib/lua/5.1/loadall.so'
> ```
> 
> Should I open a new issue?

I'm not exactly sure why that error pops up, but if you were looking for the `help` docs for buffers, you'd want to run `:help telescope.builtin` and then search for `buffers` with the `/` command. We are currently working on updating and improving our documentation at the moment (i'm heading that endeavor myself). In that situation, you were essentially trying to pass the option of `help` to the `buffers` picker without specifying a value for it. Idk why that errored out like that, but if you're looking for help on anything telescope related, you'd want to run the `:help` command, starting with `:help telescope.nvim`. Hopefully that makes sense!

**Comment by mellery451** [comment] 2021-08-02 16:27
I see that this issue (and other dups) have been closed via #858. It still doesn't work for me. FWIW, I'm using the setup:

```
    require('telescope').setup{
        defaults = {
            file_ignore_patterns = {"bazel-*/*", "*.so", ".git/*"},
            vimgrep_arguments = {
                'rg',
                '--color=never',
                '--no-heading',
                '--with-filename',
                '--line-number',
                '--column',
                '--hidden',
                '--follow',
                '--smart-case',
            }
        },
        pickers = {
            buffers = {
                show_all_buffers = true,
                sort_lastused = true,
                theme = "dropdown",
                scroll_strategy = "cycle",
                previewer = false,
                mappings = {
                    i = {
                        ["<c-d>"] = require("telescope.actions").delete_buffer,
                    },
                    n = {
                        ["<c-d>"] = require("telescope.actions").delete_buffer,
                    }
                }
            }
        },
    }
```

Do I need to do something more to ensure that all buffers are shown in the picker after a session restore? Right now I'm only seeing 15 of the 20 buffers (although oddly the picker shows 20/20 in the top right), but the list only shows 15 and doesn't scroll or cycle at all. Could it be some limit/view issue instead?

**Comment by mellery451** [comment] 2021-08-02 17:13
oh - following my previous comment...it looks like `theme = "dropdown"` is my issue. That theme truncates to 15 entries for some reason.  That seems bad, but I'll just omit that theme for now. Sorry for the noise.

**Comment by Conni2461** [comment] 2021-08-03 07:54
@mellery451 We are not "truncating" we are only displaying n entries. We have not implemented paging yet. #42 You can still fuzzy find over the whole list :)

**Comment by mellery451** [comment] 2021-08-03 15:14
I'm aware that fuzzy find works over the list - but when I've opened myriad buffers via grep or location list, I usually don't remember the names. I just want to see them in the list so I can delete them.
