### ISSUE TITLE
Cannot open file with name including square brackets

### ISSUE THREAD

**Issue by lgmys** [nvim-telescope/telescope.nvim#1223] opened 2021-09-07 08:02 UTC
### Description

Let me start with this - thanks for the cool plugin! It makes file navigation a breeze.

While opening file with square brackets via file picker, all we get is empty buffer.

It works fine opened via `:e`.

### Neovim version

NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

Ubuntu 20.10

### Steps to reproduce

1. create file named `[...document].tsx` and try opening it via file picker
2. ???
3. observe empty buffer

### Expected behavior

I would like to see my file open :D.

### Actual behavior

Empty buffer opened instead of actual file.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment] 2021-09-07 08:04
Thanks for reporting! I'm closing this because a duplicate of https://github.com/nvim-telescope/telescope.nvim/issues/1171

And I think this came up somewhere else, too.

**Closed by fdschmidt93** 2021-09-07 08:04 UTC
Labels: bug
