### ISSUE TITLE
Quickfix picker doesn't jump to the location inside the file

### ISSUE THREAD

**Issue by weeman1337** [nvim-telescope/telescope.nvim#794] opened 2021-04-23 18:20 UTC
### Description

I am storing `live_grep`s result into the quickfix list. Then I am using Telescope to go through the quickfix list. Unfotunately on selecting an item it doesn't jump to the line and column.

**Expected Behavior**

Selecting a quickfix item jumps to the line and column.

**Actual Behavior**

Selecting a quickfix item jumps to the start of the file.

### Details

<details><summary>Reproduce</summary>

1. `nvim -nu test.vim`
2. `:Telescope live_grep`
3. Grep anything so that it doesn't point to the start of the file
4. Press C-q to send the results to the quickfix list
5. Close the search
6. `:Telescope quickfix`
7. Select any item
8. → it opens at start of the file

This information is available:

![image](https://user-images.githubusercontent.com/6216686/115913749-49b83200-a471-11eb-9123-08d40ce4f1b4.png)

</details>

<details><summary>Environment</summary>

- nvim --version output: 

```
NVIM v0.5.0-dev+1233-g82ac44d01
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az69-718

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
```

- Operating system: Ubuntu 20.04.2
- Telescope commit: 712de3e18237323a979b4fd256703e2edfaddf2f

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by tami5** [comment] 2021-04-23 23:52
Couldn't reproduce. Check if you have a quickfix plugin that causing this issue. I had similar issue in the past due to quickfix plugin i had installed

**Comment by weeman1337** [comment] 2021-04-24 06:56
> Couldn't reproduce. Check if you have a quickfix plugin that causing this issue. I had similar issue in the past due to quickfix plugin i had installed

It is a clean setup just for testing only this with the `test.vim` from above:

![quickfix](https://user-images.githubusercontent.com/6216686/115950338-ea8f0780-a4da-11eb-9f2b-882cc999b0bc.gif)

**Comment by smithbm2316** [comment] 2021-04-29 02:50
I can reproduce this, even after disabling a plugin I'm using that makes changes to how the quickfix list works. I'll try to take a look at this in the coming few days @weeman1337

**Comment by Conni2461** [comment] 2021-05-09 09:06
https://github.com/nvim-telescope/telescope.nvim/commit/e2907fc0f225a7bf33ace6915bc6b55ed1e10b31 should have fixed this issue. Closing

Feel free to reopen if it still doesn't work.

**Closed by Conni2461** 2021-05-09 09:06 UTC
Labels: bug

**Comment by weeman1337** [comment] 2021-06-10 07:19
Thanks. It is now working!
