### ISSUE TITLE
current_buffer_fuzzy_find preview with treesitter highlighting broken on Neovim 0.8

### ISSUE THREAD

**Issue by HUAHUAI23** [nvim-telescope/telescope.nvim#2149] opened 2022-08-27 09:44 UTC
### Description

```
Error executing Lua callback: ...r/start/telescope.nvim/lua/telescope/builtin/__files.lua:413: attempt to call method '_get_hl_from_capture' (a nil value)
stack traceback:
        ...r/start/telescope.nvim/lua/telescope/builtin/__files.lua:413: in function 'v'
        ...r/start/telescope.nvim/lua/telescope/builtin/__files.lua:529: in function 'v'
        ...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:514: in function <...cker/start/telescope.nvim/lua/t
elescope/builtin/init.lua:483>
        ...ck/packer/start/telescope.nvim/lua/telescope/command.lua:188: in function 'run_command'
        ...ck/packer/start/telescope.nvim/lua/telescope/command.lua:253: in function 'load_command'
        ...te/pack/packer/start/telescope.nvim/plugin/telescope.lua:109: in function <...te/pack/packer/start/telescope.
nvim/plugin/telescope.lua:108>
```

### Neovim version

```markdown
NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-v2NLjd/neovim-0.8.0~ubuntu1+git2022
08262348-b0e052a8b-c99271b19=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_
SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -
Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -W
double-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallt
hrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLA
RATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/buil
d/neovim-v2NLjd/neovim-0.8.0~ubuntu1+git202208262348-b0e052a8b-c99271b19/build/cmake.config -I/build
/neovim-v2NLjd/neovim-0.8.0~ubuntu1+git202208262348-b0e052a8b-c99271b19/src -I/build/neovim-v2NLjd/n
eovim-0.8.0~ubuntu1+git202208262348-b0e052a8b-c99271b19/.deps/usr/include -I/usr/include -I/build/ne
ovim-v2NLjd/neovim-0.8.0~ubuntu1+git202208262348-b0e052a8b-c99271b19/build/src/nvim/auto -I/build/ne
ovim-v2NLjd/neovim-0.8.0~ubuntu1+git202208262348-b0e052a8b-c99271b19/build/include
Compiled by buildd@lcy02-amd64-030
```

### Operating system and version

wsl2 ubuntu

### Telescope version / branch / rev

 tag⋅=⋅"0.1.0"

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - OK: fd: found fd 8.4.0

## ===== Installed extensions =====

## Telescope Extension: `dap`
  - INFO: No healthcheck provided

## Telescope Extension: `env`
  - INFO: No healthcheck provided

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided
```

### Steps to reproduce

:Telescope  current_buffer_fuzzy_find

### Actual behavior

:Telescope  current_buffer_fuzzy_find   
![image](https://user-images.githubusercontent.com/43649186/187024745-2c38f43f-903b-423f-b646-79f93364825b.png)
![image](https://user-images.githubusercontent.com/43649186/187024756-37ac11f5-db31-41f3-903c-fcd4f7bbcf65.png)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by clason** [comment] 2022-08-27 10:58
This is due to https://github.com/neovim/neovim/pull/19931, which removed the (internal, unstable!) `_get_hl_from_capture` due to changes to how treesitter highlight groups are handled. (Note that "your" minimal config is not enough to reproduce this! You need to have nvim-treesitter set up as well.

This will require a full reimplementation of this feature. I'd suggest gating the current highlighter behind a `!has('nvim-0.8')` for now and revisit after 0.8 is released with treesitter highlighting support.

**Closed** 2022-08-27 13:29 UTC
Labels: bug, Buffer Previewer

**Comment by HUAHUAI23** [comment] 2022-08-27 14:48
thanks，Minimal configuration is automatically generated, not mine

**Comment by clason** [comment] 2022-08-27 15:01
Yes. You're supposed to replace it with your own (which you can base on the provided example).
