### ISSUE TITLE
Selected line ends up at bottom of screen.

### ISSUE THREAD

**Issue by no-more-secrets** [nvim-telescope/telescope.nvim#2591] opened 2023-07-02 23:41 UTC
### Description

When selecting something in Telescope that results in neovim moving the cursor to a particular line (e.g., when using builtin.current_buffer_fuzzy_find and selecting a line), the selected line, if it is not currently visible in the window, will end up at the very bottom of the screen.  In other words, Telescope will only scroll the window the minimum amount necessary to reveal the selected line.

### Neovim version

```markdown
v0.9.x
```

### Operating system and version

Linux

### Telescope version / branch / rev

0.1.x

### checkhealth telescope

```markdown
checks pass
```

### Steps to reproduce

Open the builtin.current_buffer_fuzzy_find, and select a line that is below the bottom-most line visible in the window, and telescope will reveal that line, but putting as the very last line in the window.

### Expected behavior

Telescope should have the line placed higher up so that some context can be seen around the line, or at least there should be a config option to allow this.

### Actual behavior

The selected line ends up visible in the window, but as the very last line.  Then typically this always requires scrolling in the window of some kind to move it more towards the center so that the context around the line can be seen.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment] 2023-07-04 23:03
I'm not exactly sure which window you're referring to. The results window or the preview window?

I'm assuming it's the preview window but I don't see the issue you're referring to. 
The matching line does show up in the middle of the preview:
![image](https://github.com/nvim-telescope/telescope.nvim/assets/66286082/bec1472c-27eb-42d0-b52e-257083c8c5fd)
I didn't do any scrolling of the preview window here.

**Comment by no-more-secrets** [comment] 2023-07-04 23:22
@jamestrew Sorry I meant neither of those two windows -- I was referring to the normal nvim window containing the line that is selected, i.e. after the telescope window closes.  So in other words, find the result in the results window and then hit enter to select it, let the telescope window close, then observe where the line is on screen that was selected.

All that said, I see now that this behavior can be replicated just with a normal search, and so it doesn't necessarily have anything to do with telescope.  I.e., just do a normal search (using `/`) for something that bottom-most visible line in the window, and (sometimes?) the target line will be revealed on the last line of the window.

So I guess we can close this since it is not telescope specific, unless you think telescope could benefit from a setting that could change this.  E.g., a config setting that says "when the user selects a line in the results window and the telescope window closes, and the underlying nvim window scrolls to reveal the selected line, ensure that said line does not end up at the very bottom of the screen so that the user can see some context around it without having to further scroll the window."

**Comment by jamestrew** [comment] 2023-07-04 23:36
Oh okay I see :+1: 
This looks like a duplicate of https://github.com/nvim-telescope/telescope.nvim/issues/2580
You can just bind `<CR>` like this
```lua
["<CR>"] = actions.select_default + actions.center
```

**Closed by jamestrew** 2023-07-04 23:36 UTC
Labels: bug
