### ISSUE TITLE
`actions.close` mapping leaves a terminal in insert mode

### ISSUE THREAD

**Issue by ten3roberts** [nvim-telescope/telescope.nvim#2785] opened 2023-11-15 14:39 UTC
### Description

Using `actions.close` in the insert mappings for the telescope prompt does not restore the mode of the underlying terminal buffer.

### Neovim version

```markdown
NVIM v0.10.0-dev-2931+gd92dd2a0c-Homebrew
Build type: Release
LuaJIT 2.1.1699180677
Run "nvim -V1 -v" for more info
```

### Operating system and version

macOS Sonoma

### Telescope version / branch / rev

telescope 0.1.4

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `bookmarks` ~
- No healthcheck provided

Telescope Extension: `dap` ~
- No healthcheck provided

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `menufacture` ~
- No healthcheck provided

Telescope Extension: `smart_open` ~
- No healthcheck provided
```

### Steps to reproduce

- `:term` (opens in normal mode)
- `:Telescope find_files`
- `<esc>`

The terminal is now in insert/terminal mode, instead of normal mode.

Non terminal buffers correcly restore their mode to normal.

### Expected behavior

The terminal buffer is restored to normal mode

### Actual behavior

The terminal is left in the mode of the telescope prompt, I.e; insert mode

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			{
				"nvim-telescope/telescope.nvim",
				requires = {
					"nvim-lua/plenary.nvim",
					{ "nvim-telescope/telescope-fzf-native.nvim", run = "make" },
				},
			},
			-- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
			display = { non_interactive = true },
		},
	})
end
_G.load_config = function()
	require("telescope").setup({
		defaults = {
			mappings = {
				i = {
					["<esc>"] = require("telescope.actions").close,
				},
			},
		},
	})
	require("telescope").load_extension("fzf")
	-- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
	print("Installing Telescope and dependencies.")
	vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
```

**Comment by robbplo** [comment] 2023-11-15 18:56
This is also happening to me when i `find_files` from any other file, not even a terminal. Thought i was going crazy, adding `jjjj` to the top of all my files lol

**Comment by jamestrew** [comment] 2023-11-16 01:40
@ten3roberts thanks for the report, I'm able to reproduce this

@robbplo I'm not able to reproduce this outside of `:term`. We're tracking another issue where this seems to happen if you have something (like barbar.nvim with some settings) that looks at buffer options inside a `BufWinLeave` event. Feels like it's a general neovim issue (which has happened before).

Either way, both issues are somewhat related to https://github.com/nvim-telescope/telescope.nvim/issues/2766

**Comment by jamestrew** [comment] 2024-01-13 14:21
Can people try out this PR? https://github.com/nvim-telescope/telescope.nvim/pull/2850

I may have accidentally fixed this :grin:

**Comment by tbung** [comment] 2024-01-13 15:08
I tested it and it does not fix the issue. As far as I can tell the added call to `stopinsert` is only in the `commands` builtin, but the issue here is with `buffers`. I am not really familiar with telescope's code base, but a quick test showed, that adding
```lua
  vim.schedule(function()
    vim.cmd [[stopinsert]]
  end)
```
to the end of `action_set.edit` (about here https://github.com/nvim-telescope/telescope.nvim/blob/7264df471fb4864fbe060fff4a552a24f99ab8c2/lua/telescope/actions/set.lua#L209) at least goes back to `normal` mode, it does however not reset cursor position.

**Comment by jamestrew** [comment] 2024-01-13 16:17
@tbung yeah you're right in that it doesn't fix it. Thanks for trying. I was messing up the testing.

Let me think about this some more. There's a ton of flaky behavior around switching modes when opening/closing telescope. I need to be careful I don't break something trying to fix something else. I'm not even fully convinced this isn't a neovim core issue (which has happened before).

**Comment by jamestrew** [comment] 2024-01-14 19:41
Yeah this is actually reproducible without telescope. I'll create an issue with neovim and see if this is something that can be addressed upstream.

**Comment by jamestrew** [comment] 2024-01-16 02:51
This looks to be fixed upstream via https://github.com/neovim/neovim/pull/27033

**Closed by jamestrew** 2024-01-16 02:51 UTC
Labels: bug, reproducible
