### ISSUE TITLE
Confirming a selection (Enter / <CR>) not working 

### ISSUE THREAD

**Issue by rayantovi** [nvim-telescope/telescope.nvim#2731] opened 2023-10-07 15:33 UTC
### Description

Pressing enter after searching for a file just clears the text i typed and does NOT open the file i selected, ### **unless i press Alt before enter** 

### Neovim version

```markdown
NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Ubuntu 22.04.3 LTS x86_64 

### Telescope version / branch / rev

newest 

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.3.1

===== Installed extensions ===== ~
```

### Steps to reproduce

i do not know

### Expected behavior

Open file when pressing enter after searching/selecting

### Actual behavior

Clears text field and weird behavior 

### Minimal config

My config can be found here:

[https://github.com/rayantovi/nvim](https://github.com/rayantovi/nvim)

**Comment by jamestrew** [comment] 2023-10-07 16:01
Not reproducible.
Please try with the minimal config in the original issue template. Otherwise I'm closing the issue. I can't do anything else without more info.

**Comment by rayantovi** [comment] 2023-10-07 16:22
Sorry for the inconvenience, here's my config: [https://github.com/rayantovi/nvim](https://github.com/rayantovi/nvim)

**Comment by jamestrew** [comment] 2023-10-07 16:55
How about with this config

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by rayantovi** [comment] 2023-10-07 17:40
i did exactly that and i got a plain no plugin non sauce-able neovim regardless of how many times i sourced it and :PackerSync'ed, i might've missed or gotten something wrong but i could not do anything with this config

**Comment by rayantovi** [comment] 2023-10-07 19:39
Same results unfortunately, i also tried reinstalling and removing the telescope files and i checked my keymappings as well but still  the same problem, its very weird, i checked my keymappings as well 

![Screenshot from 2023-10-07 22-31-56](https://github.com/nvim-telescope/telescope.nvim/assets/40218380/9e0b443a-ed70-4a62-be8d-552664772bd3)

**Comment by jamestrew** [comment] 2023-10-07 20:17
you shouldn't have to `:source` anything. 
are you sure you're saving my minimal config as a file and then using it to launch neovim with the `-u` flag (`nvim -u /tmp/min.lua`).

the config should be automatically sourced/used as the neovim config, plugins installed and ready to use.


https://github.com/nvim-telescope/telescope.nvim/assets/66286082/c87efa79-d6d4-4831-9243-6b83d97a8e47

**Comment by rayantovi** [comment] 2023-10-08 09:34
Oh yes the the config does not require sourcing everything is loaded nice but still the same issue, entering (<CR>) just clears the text field unless ALT key is pressed beforehand, i'm really confused

**Comment by jamestrew** [comment] 2023-10-08 16:08
Open telescope and while it is open, go into normal mode and then do `:verbose nmap <cr>`.

You can also do `<c-/>` in insert mode to show telescope keymappings.

This might be able to tell you what's happening with the mappings.

**Comment by rayantovi** [comment] 2023-10-08 22:51
it seems very normal to me but i'll continue tinkering around with it, here are the results:


![Screenshot from 2023-10-09 01-48-53](https://github.com/nvim-telescope/telescope.nvim/assets/40218380/533f3773-7811-41a0-b417-4022106788af)
![Screenshot from 2023-10-09 01-49-41](https://github.com/nvim-telescope/telescope.nvim/assets/40218380/70fd2886-e390-4ce5-8655-87db7c06a5dd)

**Comment by jamestrew** [comment] 2023-10-09 04:01
oh sorry I meant `:verbose imap <cr>` but either way it looks like `<CR>` is not bound to `select_default` according to the second pic.

try `:verbose imap <cr>`.
are you calling `require('telescope').setup()` anywhere in your config?

**Comment by rayantovi** [comment] 2023-10-09 08:23
oh my god we got it, _**it was  [tmsvg/pear-tree](https://github.com/tmsvg/pear-tree)  all along**_,

 the `:verbose imap <cr>` finally exposed it, i basically just replaced it with a _much better_ non conflicting plugin [windwp/nvim-autopairs](https://github.com/windwp/nvim-autopairs).

Thanks a lot!

**Comment by jamestrew** [comment] 2023-10-09 21:02
Glad you were able to find the issue 👍

**Closed** 2023-10-09 21:02 UTC
Labels: bug, not reproducible
