### ISSUE TITLE
Tab key doesn't work in insert mode due to Telescope

### ISSUE THREAD

**Issue by AviAvinav** [nvim-telescope/telescope.nvim#2545] opened 2023-05-29 05:13 UTC
### Description

Hi, I am using telescope and telescope-file-browser, it used to work flawlessly till a few days ago but recently there's been an issue. Whenever I am in a buffer with a file open and press the <Tab> key, I get the error in the screenshot.

<img src="https://i.ibb.co/n1ZWL5X/Screenshot-2023-05-29-103253.png"/>

### Neovim version

```markdown
NVIM v0.10.0-dev-400+ge41b2e34b
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Windows 11

### Telescope version / branch / rev

0.1.1

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

- WARNING vim.health.report_start() is deprecated, use vim.health.start() instead. :help |deprecated|
  This feature will be removed in Nvim version 0.11

Checking for required plugins ~
- WARNING vim.health.report_ok() is deprecated, use vim.health.ok() instead. :help |deprecated|
  This feature will be removed in Nvim version 0.11
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0 (rev af6b6c543b)
- OK fd: found fd 8.7.0

===== Installed extensions ===== ~

Telescope Extension: `file_browser` ~
- WARNING vim.health.report_info() is deprecated, use vim.health.info() instead. :help |deprecated|
  This feature will be removed in Nvim version 0.11
- No healthcheck provided
```

### Steps to reproduce

1. Have telescope and telescope-file-browser setup
2. Open a file and go into insert mode and press TAB key

### Actual behavior

N/A

### Minimal config

```Lua
return {
	{
		"nvim-telescope/telescope.nvim",
		tag = "0.1.1",
		dependencies = { "nvim-lua/plenary.nvim" },
		event = { "VeryLazy" },
	},
	{
		"nvim-telescope/telescope-file-browser.nvim",
		dependencies = { "nvim-telescope/telescope.nvim", "nvim-lua/plenary.nvim" },
		event = { "VeryLazy" },
		config = function()
			local tl = require "telescope"
			local file_browser = require "plugins.telescope.file_browser"

			tl.setup {
				extensions = {
					file_browser = file_browser,
				},
			}
			tl.load_extension "file_browser"
		end,
	},
}

-- I am using `lazy.nvim`
```

**Comment by jamestrew** [comment] 2023-05-29 21:59
You're getting that error when telescope isn't open?

**Comment by AviAvinav** [comment] 2023-05-30 04:21
Yes, it's when telescope isn't open but the error references telescope. By the way just an extra piece of info for the issue I have mentioned above that I have telescope-file-browser but the error persists even when it's disabled(telescope is still active).

**Comment by Conni2461** [comment] 2023-05-30 05:01
Is this only happening on 0.1.1 or also on our release branch 0.1.x / lastest master? Because i currently cant reproduce it.

**Comment by AviAvinav** [comment] 2023-06-06 06:47
Sorry for such a late reply but I tested it out on the latest master and the error still persists, it's the exact same error. My config for telescope is very minimal, I am using `lazy.nvim`:

```lua
return {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = { "nvim-lua/plenary.nvim" },
    cmd = "Telescope",
  },
}
```

**Comment by Conni2461** [comment] 2023-06-07 08:46
this is surprisingly similar to this issue: https://github.com/nvim-telescope/telescope.nvim/issues/1975

Also also saying you dont have a telescope config is very minimal doesnt help us. We need to know that this issue can be reproduced with a minimalrc. the bug template provides one and that one should have been used with `nvim -nu minimal.lua`

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

None the less, i also refactored the whole keymappings code and even got rid of this `Unsure how we got here` part so maybe that helps. I'll try to get the new mapping code to master today

**Comment by Conni2461** [comment] 2023-06-09 11:58
the mappings refactor is now on latest master, can you retest. it might have fixed your issue because we no longer need to do hacks for keymappings.

**Comment by AviAvinav** [comment] 2023-06-10 07:29
Yes, I updated it to the latest master and it seems to have fixed the issue. Thanks a lot!

**Comment by Conni2461** [comment] 2023-06-10 15:46
Thanks for testing. I close the issue if this issues comes back feel free to reopen

**Closed** 2023-06-10 15:46 UTC
Labels: bug
