### ISSUE TITLE
Preview window cannot be scrolled when layout_strategy = "flex"

### ISSUE THREAD

**Issue by yutkat** [nvim-telescope/telescope.nvim#796] opened 2021-04-25 06:22 UTC
### Description

When I try to scroll the preview window with layout_strategy = "flex", I get the following error.
`E5108: Error executing lua ...vim/plugged/telescope.nvim/lua/telescope/actions/set.lua:140: attempt to index field 'layout_config' (a nil value)`

`layout_strategy = "horizontal",` works as expected.

**Expected Behavior**

scroll up/down in the preview window

**Actual Behavior**

display this error message
`E5108: Error executing lua ...vim/plugged/telescope.nvim/lua/telescope/actions/set.lua:140: attempt to index field 'layout_config' (a nil value)`

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. `:Telescope buffers`
3. display this error message `E5108: Error executing lua ...vim/plugged/telescope.nvim/lua/telescope/actions/set.lua:140: attempt to index field 'layout_config' (a nil value)`
</details>

<details><summary>Environment</summary>

- nvim --version output: v0.5.0-dev+1272-g4570d04b1
- Operating system: ArchLinux
- Telescope commit: 6fd1b3bd255a6ebc2e44cec367ff60ce8e6e6cab

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "flex",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by smithbm2316** [comment] 2021-05-08 09:44
Are you getting this error in the minimal config as well as your own personal config? I have been using the flex layout for months and have been able to scroll up/down in the preview window just fine. If you're having issues with the minimal config as well I can take a look into what might be the issue @yutkat

**Comment by yutkat** [comment] 2021-05-08 09:58
You can find the minimum configuration by toggling Configuration in Details.

I've just tried this now. This was still reproduced in 88f7b27222ac75223ab971c5158dbcf64a326669.

**Comment by smithbm2316** [comment] 2021-05-08 10:39
I'll take a look into this further this weekend. From an initial look I think I may have found the culprit, but will have to test it to see if my suspicion is true. Sorry for the delay on an initial response!

**Comment by smithbm2316** [comment] 2021-05-08 10:45
@yutkat If you add the following setting to your Telescope config, does it temporarily fix your issue?

```
layout_defaults = {
  horizontal = {
    mirror = false,
  },
  vertical = {
    mirror = false,
  }
}
```

**Comment by yutkat** [comment] 2021-05-08 13:03
I tried, but unfortunately it reproduces :cry:

**Comment by smithbm2316** [comment] 2021-05-08 20:32
@yutkat I can't reproduce the issue on my end when adding the above additions to the minimal or my own personal config. I have a temporary fix in the PR mentioned above this comment, if you have the time and want to try using that branch of Telescope, I believe it should fix the bug you're experiencing.

**Comment by yutkat** [comment] 2021-05-09 02:47
Wow, great. I applied that patch and it fixed it!

**Comment by smithbm2316** [comment] 2021-05-09 03:16
Great to hear! That patch may not get merged into master for a bit, as I'm pretty sure it's not actually solving the real underlying issue, rather just adding an extra check to make sure that if that issue arises, don't break the code 🤣. We may merge it, but I think I have some more exploration to be done to really figure out the root issue. Will update here when I have some more info!

**Comment by Conni2461** [comment] 2021-07-01 10:39
I think this is fixed now in a better way with the layout configuration changes.

I can no longer reproduce this bug on latest master. Closing for now. If i am wrong here, feel free to reopen :)

**Closed by Conni2461** 2021-07-01 10:39 UTC
Labels: bug

**Comment by yutkat** [comment] 2021-07-01 14:14
It works! Thank you.
