### ISSUE TITLE
live_grep on find_files results

### ISSUE THREAD

**Issue by andy941** [nvim-telescope/telescope.nvim#2095] opened 2022-07-22 13:43 UTC
**Is your feature request related to a problem? Please describe.**
No, it is not related to a problem with Telescope, but the enhancement would make my life easier.
I am a research scientist working with genomics datasets. I routinely generate  multiple .csv files and each contains several thousands genes expression values and gene descriptions, organized in nested directories . I used to use regular grep a lot to quickly glance at well known genes and keywords, to have a sense of the performance of my analysis. Nowdays I cd (in neovim) in the right directory (where I know I have mostly only the csv files for a given analysis) and use live_grep. I do this to not pollute the search with unrelated files. It works like a charm but is restrictive and a bit cumbersome.

**Describe the solution you'd like**
It would be amazing to have a way to select a list of files with find_files and live_grep on that subset by a sort of "piping" command. It would allow me to do very complex/tailored searches with ease.

**Describe alternatives you've considered**
I tried to find out if it was possible to do it in Lua but I am either not good enough or it's not trivial. Probably the former. 

**Additional context**
I know it might be very specific in my case, but I can imagine other use cases like this in other fields/situations. I use neovim for everything nowdays (shout out to nvim-R) and I love the speed and simplicity of it. This would really be the cherry on top for me. I apologize if I missed an evident solution, I tried my best. Probably the closest thing I saw was the commit that introduced the `refine` action, but I don't think it does what I need.

Thank you,
Andrea

**Comment by fdschmidt93** [comment] 2022-07-23 06:06
The below seems to work for me as intended.

local builtin = require("telescope.builtin")

```lua
builtin.find_files({
  attach_mappings = function(prompt_bufnr)
    local actions = require("telescope.actions")
    local action_state = require("telescope.actions.state")
    actions.select_default:replace(function()
      local current_picker = action_state.get_current_picker(prompt_bufnr)
      local selections = current_picker:get_multi_selection()
      -- if no multi-selection, leverage current selection
      if vim.tbl_isempty(selections) then
        table.insert(selections, action_state.get_selected_entry())
      end
      local paths = vim.tbl_map(function(e)
        return e.path
      end, selections)
      actions.close(prompt_bufnr)
      builtin.live_grep({
        search_dirs = paths,
      })
    end)
    -- true: attach default mappings; false: don't attach default mappings
    return true
  end,
})
```

You can then also map `actions.select_all` to swiftly select all entries after searching e.g. for `.csv` files.

**Comment by andy941** [comment] 2022-07-24 20:08
Thank you very much for the answer. Forgive my ignorance, where should I insert the code? I just pasted it in the telescope.lua config I have (beginning of the file), every time I start neovim it just opens up the find_files telescope builtin by default. How do I invoke this? Do I have to set a mapping or is it substituting  some default action?
I more or less understand the code  but I don't have clear how this  has to fit in the Telescope config. It's probably easier to show you what I have at the moment:

``` lua
local utils = require('utils')
local opts = { noremap=true, silent=true }
local tele = require('telescope')
local actions = require('telescope.actions')
local action_state = require("telescope.actions.state")
local builtin = require("telescope.builtin")

builtin.find_files({
  attach_mappings = function(prompt_bufnr)
    actions.select_default:replace(function()
      local current_picker = action_state.get_current_picker(prompt_bufnr)
      local selections = current_picker:get_multi_selection()
      -- if no multi-selection, leverage current selection
      if vim.tbl_isempty(selections) then
        table.insert(selections, action_state.get_selected_entry())
      end
      local paths = vim.tbl_map(function(e)
        return e.path
      end, selections)
      actions.close(prompt_bufnr)
      builtin.live_grep({
        search_dirs = paths,
      })
    end)
    -- true: attach default mappings; false: don't attach default mappings
    return true
  end,
})

tele.setup {
	defaults = {
		layout_strategy = 'vertical',
		layout_config = {
			width = 0.90,
			height = 0.95,
			preview_height = 0.75,
		},
		file_ignore_patterns = { -- % is an escape char in lua regex
			'Pictures/',
			'Drives/',
			'vpnconfigs/',
			'.git/',
			'lua%-language%-server/',
		},
		mappings = {
			n = {
				["<C-q>"] = false,
				["<C-a>"] = actions.send_to_qflist + actions.open_qflist,
				["<M-q>"] = false,
				["<C-l>"] = actions.send_selected_to_qflist + actions.open_qflist
			},
		},
		prompt_prefix = "    "
	},
	pickers = {
		find_files = {
			hidden = true,
		},
		live_grep = {
			hidden = true
		},
		file_browser = {
			hidden = true
		}
	},
	extensions = {
		fzf = {
			fuzzy = true,                    -- false will only do exact matching
			override_generic_sorter = true,  -- override the generic sorter
			override_file_sorter = true,     -- override the file sorter
			case_mode = "smart_case",        -- or "ignore_case" or "respect_case"
			-- the default case_mode is "smart_case"
		},
		bibtex = {
			-- Context awareness disabled by default
			context = true,
			-- Fallback to global/directory .bib files if context not found
			-- This setting has no effect if context = false
			context_fallback = true,
			wrap = true,
			search_keys = {'author', 'year', 'title', 'abstract'},
			custom_formats = {
        {id = 'spaced_cite', cite_marker = '~\\cite{%s}'}
      },
      format = 'spaced_cite',
		},
		heading = {
			treesitter = true,
		},
	},
}
-- To get fzf loaded and working with telescope, you need to call
-- load_extension, somewhere after setup function:
tele.load_extension('fzf')

-- project management with Telescope
tele.load_extension('project')

-- Bibtex citation search
tele.load_extension('bibtex')

-- Search in headings (if applicable)
tele.load_extension('heading')

-- DAP integration
tele.load_extension('dap')

```

**Comment by fdschmidt93** [comment] 2022-07-25 06:24
> every time I start neovim it just opens up the find_files telescope builtin by default. 

Neovim sources your telescope configuration file that executes that code snippet now, so --

> Do I have to set a mapping or is it substituting some default action?

yes, you'd wrap my code in a function to map it to a key combination of your choosing:

```lua
local my_func = function()
 -- code ..
end
-- and then
vim.keymap.set('n', '$YOUR_KEY', my_func)
```

It's not really part of the telescope configuration, as it's more a function to launch a customized picker. Strictly speaking, you could overwrite the default `find_files` configuration with those (in table where `hidden = true` in `find_files`), but of course that's most likely not what you want.

To get started to read up more broadly on Neovim configuration --

1. Learn the basics of lua (or fennel I suppose if you prefer lisp): what help me greatly is reading code from plugins to gather some patterns around metatables (which are fantastic once understood) and functional patterns (anonymous functions, currying, etc)
2. https://github.com/nanotee/nvim-lua-guide is a decent guide
3. Leverage `:Telescope help_tags` to search quickly for docs on what you are looking for (like `vim.keymap.set`)

Closing this as telescope side of things I think is completed here and general neovim help is beyond our scope.

**Closed by fdschmidt93** 2022-07-25 06:24 UTC
Labels: enhancement
