### ISSUE TITLE
Failed to run 'config' on startup

### ISSUE THREAD

**Issue by jobanmendpara** [nvim-telescope/telescope.nvim#2676] opened 2023-08-29 23:08 UTC
### Description

Upon startup, I get an error message about telescope unable to run config. 
I was able to use telescope without any issues earlier in the morning.
Before the error started occurring the only change I made to my dev env was to remove NIX package manager and I've not noticed other side effects from doing so.
No changes were made to my neovim config either.
This issue happens on a fresh install of preconfigured neovim distros as well (lazyvim and astrovim).

![image](https://github.com/nvim-telescope/telescope.nvim/assets/60673266/32147a15-5d77-40cc-acd5-fc3e370e8d4f)

### Neovim version

```markdown
NVIM v0.10.0-dev-3554+g97cfee39e-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 14.0

### Telescope version / branch / rev

telescope 0.1.2

### checkhealth telescope

```markdown
telescope: health#telescope#check
    Checking for required plugins
    - OK plenary installed.
    - OK nvim-treesitter installed.
    
    Checking external dependencies
    - OK rg: found ripgrep 13.0.0
    - OK fd: found fd 8.7.0
===== Installed extensions =====
```

### Steps to reproduce

1. nvim -nu minimal.lua

**Error Displayed:** 
```Error executing vim.schedule lua callback: vim/_editor.lua:401: nvim_exec2()..User Autocommands for "PackerComplete": Vim(lua):E5108: E
rror executing lua ...e/pack/packer/start/plenary.nvim/lua/plenary/strings.lua:18: dlsym(RTLD_DEFAULT, linetabsize_col): symbol not fou
nd
stack traceback:
        [C]: in function '__index'
        ...e/pack/packer/start/plenary.nvim/lua/plenary/strings.lua:18: in function 'strdisplaywidth'
        ...e/pack/packer/start/plenary.nvim/lua/plenary/strings.lua:157: in function 'dedent'
        ...ack/packer/start/telescope.nvim/lua/telescope/config.lua:891: in function 'set'
        ...ack/packer/start/telescope.nvim/lua/telescope/config.lua:895: in function 'set_defaults'
        ...ack/packer/start/telescope.nvim/lua/telescope/config.lua:909: in main chunk
        [C]: in function 'require'
        .../pack/packer/start/telescope.nvim/lua/telescope/init.lua:133: in function 'setup'
        /Users/jobanmendpara/Developer/minimal/minimal.lua:26: in function 'load_config'
        [string ":lua"]:1: in main chunk
        [C]: in function 'nvim_exec2'
        vim/_editor.lua:401: in function 'cmd'
        /tmp/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:356: in function 'cb'
        vim/_editor.lua:325: in function <vim/_editor.lua:324>
stack traceback:
        [C]: in function 'nvim_exec2'
        vim/_editor.lua:401: in function 'cmd'
        /tmp/nvim/site/pack/packer/start/packer.nvim/lua/packer.lua:356: in function 'cb'
        vim/_editor.lua:325: in function <vim/_editor.lua:324>
```

### Expected behavior

No error and all telescope features are accessible.

### Actual behavior

The following error displays on startup:

```
Failed to run config for telescope.nvim

...cal/share/nvim/lazy/plenary.nvim/lua/plenary/strings.lua:18: dlsym(RTLD_DEFAULT, linetabsize_col): symbol not found

stacktrace:
  
/plenary.nvim/lua/plenary/strings.lua:18 in strdisplaywidth
/plenary.nvim/lua/plenary/strings.lua:157 in dedent
/telescope.nvim/lua/telescope/config.lua:866 in set
/telescope.nvim/lua/telescope/config.lua:870 in set_defaults
/telescope.nvim/lua/telescope/config.lua:884
/telescope.nvim/lua/telescope/actions/init.lua:57
~/.config/nvim/lua/plugins/telescope.lua:14 in config
```

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by delphinus** [comment] 2023-08-30 00:52
hmm the error occurs here.

https://github.com/nvim-lua/plenary.nvim/blob/0dbe561ae023f02c2fb772b879e905055b939ce3/lua/plenary/strings.lua#L6-L20

Can you show me the output from `:=jit` in Neovim?

**Comment by delphinus** [comment] 2023-08-30 02:07
Possibly, LuaJIT may not exist already in your box. `brew reinstall luajit` solves this issue?

**Comment by jobanmendpara** [comment] 2023-08-30 02:27
So I did try that earlier in the day and just a few minutes ago and it did not change the results.
However, after doing more searching online, I found an existing issue with plenary.nvim producing the same error as I've mentioned above:
[strings: FFI error with Apple Clang 15 #510](https://github.com/nvim-lua/plenary.nvim/issues/510)

Seems like the issue lies with plenary and not telescope itself. Considering plenary is a dependency for other neovim plugins, it's possible there are other plugins facing a similar problem.

**Comment by delphinus** [comment] 2023-08-30 02:40
The feature to use `strdisplaywidth` by `ffi` has been introduced in #464. I don't really remember the reason why this was needed, but according to #464, it seemed unable to use `vim.fn.strdisplaywidth()` in Lua main loop.

Now the problem might be solved, then we may have to consider not to use `plenary.strings`. 🤔

**Comment by fibbo** [comment] 2023-09-06 09:17
The issue linked by @delphinus made me realize that the problem seems to be caused by using Xcode 15 (beta 7 in my case).

I rebuilt neovim with Xcode 14.2, and all is fine, but when compiling with Xcode beta, I observed the same failure.

**Comment by Conni2461** [comment] 2023-09-12 18:03
this issue should be fixed with the latest plenary version.

**Comment by jobanmendpara** [comment] 2023-09-13 14:48
Confirmed!

**Closed** 2023-09-13 14:48 UTC
Labels: bug
