### ISSUE TITLE
`:Telescope `<Tab> gives errors on Windows (Dictionary, List required)

### ISSUE THREAD

**Issue by sp1n0r** [nvim-telescope/telescope.nvim#406] opened 2021-01-09 00:46 UTC
### Description

Since the latest commit https://github.com/nvim-telescope/telescope.nvim/commit/77d6a74d1ea3d272e6e898860a71a61b184540ff everytime I enter the command `:Telescope ` `<Tab>` (for suggestions) it throws some errors.

**Expected Behavior**

No errors should occur.

**Actual Behavior**

```
:Telescope ...
Error detected while processing function <SNR>65_telescope_complete:
line    7:
E715: Dictionary required
E714: List required
```
Nonetheless, the command still works, and no errors occur as long as I don't press `<Tab>`

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. `Telescope ` (don't forget the space at the end :) )
3. Press `<Tab>`
4. ... bang here is the issue
</details>

<details><summary>Environment</summary>

- nvim version: 0.5.0
- Operating system: Windows
- Telescope commit: '77d6a74'

</details>

<details><summary>Configuration</summary>
<p>
 

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom", 
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by tami5** [comment] 2021-01-09 07:22
cc @glepnir

**Comment by glepnir** [comment] 2021-01-09 07:25
Can't reproduce ..

**Comment by tami5** [comment] 2021-01-09 07:37
@glepnir 🙏

**Comment by glepnir** [comment] 2021-01-09 07:41
fixed.

**Comment by sp1n0r** [comment] 2021-01-09 11:33
I did `:PlugUpdate` but the issue didn't get fixed :/

**Comment by sp1n0r** [comment] 2021-01-09 11:34
Oh it hasn't been merged yet

**Comment by glepnir** [comment] 2021-01-09 11:36
@sp1n0r  Now merged.

**Closed** 2021-01-09 11:35 UTC
Labels: Windows, bug

**Comment by sp1n0r** [comment] 2021-01-09 11:37
cool I'll try it rn. Just for future reference what would I do if I wanted to try it before it was merged? Create a new local branch and then what?

**Comment by sp1n0r** [comment] 2021-01-09 11:37
Works great now thanks :)

**Comment by tami5** [comment] 2021-01-09 12:02
> cool I'll try it rn. Just for future reference what would I do if I wanted to try it before it was merged? Create a new local branch and then what?

use `gh` or github-cli, gh pr checkout {pr number} in the root of github dir

**Comment by sp1n0r** [comment] 2021-01-09 12:10
ohh thanks
