### ISSUE TITLE
`initial_mode` not applied when invoking telescope

### ISSUE THREAD

**Issue by kuntau** [nvim-telescope/telescope.nvim#1611] opened 2021-12-18 22:55 UTC
### Description

Telescope still opened in `insert` mode when using the following command. From command line and key mapping
```
:Telescope buffers sort_lastused=true initial_mode=normal
:lua require("telescope.builtin").buffers({sort_lastused=true, initial_mode="normal"})
```

### Neovim version

```markdown
NVIM v0.7.0-dev+95803f0e9
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 10.15.7

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.0

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. Type this on commandline `:Telescope buffers sort_lastused=true initial_mode=normal`
2. Or this `lua require("telescope.builtin").buffers({sort_lastused=true, initial_mode="normal"})`
3. Telescope opened in `insert` mode

### Expected behavior

Telescope opened in `normal` mode

### Actual behavior

Telescope opened in `insert` mode

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment] 2021-12-21 22:07
It works for me, though not entirely as intended, which I suspect this is due to prompt buffer changes.

Could you please see whether #1600 also fixes your issue?

**Comment by LudoPinelli** [comment] 2022-01-08 01:43
Just to report that I have the same problem (on Linux  and Windows), I tried the #1600 fix but it didn't fix the problem.

**Comment by Conni2461** [comment] 2022-01-08 21:46
This bug is not fix. It only occurs in the latest nightly release, not in 0.6.*

**Comment by Bekaboo** [comment] 2022-03-01 19:16
Can confirm this bug has not been fixed now in neovim 0.7.*

**Comment by dpetka2001** [comment] 2022-03-01 22:54
I don't have this bug in NVIM v0.7.0-dev. I personally use it with buffers and oldfiles and initial_mode=normal works as it should.

**Comment by hgigas** [comment] 2022-03-15 15:46
Impossible to set initial_mode to normal. `Telescope oldfiles initial_mode=normal`

All pickers open in `insert` mode.

init.lua
```
require('plugins')
```

lua/plugins.lua
```
require'packer'.startup {function()

use 'wbthomason/packer.nvim'

use {
  'nvim-telescope/telescope.nvim',
  requires = {
    {
      'nvim-lua/plenary.nvim',
    },
  },
  config = function()
    require'telescope'.setup {
      defaults = {
        initial_mode = "normal",
        path_display = {
          truncate = 1,
        },
        cycle_layout_list = { "horizontal", "vertical" },
        layout_config = {
          horizontal = {
            height = 0.9,
            width = 0.9,
            preview_width = 0.7,
            preview_cutoff = 60
          }
        },
        preview = {
          filesize_limit = 0.5,
          timeout = 100,
        },
      },
      pickers = {
        buffers = {
          ignore_current_buffer = true,
        }
      },
    }
  end
}
end,
}
```

**Comment by Conni2461** [comment] 2022-04-22 14:16
fixed by https://github.com/nvim-telescope/telescope.nvim/commit/cc1a3440f9ba6f28a8ca0bfff867f60c2d80c353

If not feel free to reopen, thanks :)

**Closed by Conni2461** 2022-04-22 14:16 UTC
Labels: bug
