### ISSUE TITLE
Prompt input written into target file.

### ISSUE THREAD

**Issue by mrdgo** [nvim-telescope/telescope.nvim#501] opened 2021-02-05 11:21 UTC
### Description

When I type something in telescope prompt, that text sometimes is written into the currently opened file.

**Expected Behavior**

Using telescope does not modify my current buffer.

**Actual Behavior**

Searching for something acts like `R` in normal mode.
With the addition, that it is not saved as the latest change in history.
That is as annoying as it is to describe.

### Details

Example:

the file I want to open looked like this:
```python
        # tf.keras.layers.Flatten(input_shape=dim_input),
```

I opened telescope to change to the above mentioned buffer, with search string 'e2e'.
The line looks like:
```python
      e2e tf.keras.layers.Flatten(input_shape=dim_input),
```

also, when I pressed `u` in normal mode to undo, it changed previous changes first.
So I am forced, to manually restore the file.

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. :e test2.vim
3. :mksession test.sess
4. :q
5. nvim -nu test.vim -S test.sess
6. :lua require'telescope.builtin'.buffers({ show_all_buffers = true })
7. Use step 6 a few times to change buffers - for me the error occurs quite often.
</details>

<details><summary>Environment</summary>

- nvim --version output: v0.5.0-dev+1064
- Operating system: Artix Linux (Arch based)
- Telescope commit: 5f1d16a

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by tami5** [comment] 2021-02-05 23:00
this used to happen to me a lot with `>` getting written into buffer

**Comment by elianiva** [comment] 2021-02-06 03:49
> this used to happen to me a lot with `>` getting written into buffer

I found an easy way to reproduce this. 
- open Telescope
- close it using your mouse (clicking on telescope window)
- quit the file you're currently editing (using `:q`)
- you'll get this error
```
E37: No write since last change
E162: No write since last change for buffer "[Prompt]"
```
- it will jump to a buffer with `>` as its content (can also change to `> foobar` if you typed `foobar` before closing Telescope using the mouse)

**Comment by mrdgo** [comment] 2021-02-06 09:27
I feel like you actually experience different bugs.

There is no prompt buffer written in my case.
In my case the search string from the prompt buffer is written into my file.

please note this difference.

**Comment by Conni2461** [comment] 2021-02-06 09:37
> In my case the search string from the prompt buffer is written into my file.

That never happened to me but this might be an issue with prompt filetype. I think neovim is still missing some patches to fix them.

Could you confirm my hunch by using
```lua
require('telescope').setup{
  defaults = {
    prompt_prefix = "",
  }
}
```

Maybe that fixes this. MAYBE. Just guessing right now :)

**Comment by elianiva** [comment] 2021-02-06 09:38
> I feel like you actually experience different bugs.
> 
> There is no prompt buffer written in my case.
> In my case the search string from the prompt buffer is written into my file.
> 
> please note this difference.

Ah, sorry. I was replying to Tami because he said he has `>` written to a buffer so I assume it's the prompt thingy.

Anyway, I couldn't reproduce your issue using the provided minimal `init.vim`.

**Comment by mrdgo** [comment] 2021-02-08 08:56
> > I feel like you actually experience different bugs.
> > There is no prompt buffer written in my case.
> > In my case the search string from the prompt buffer is written into my file.
> > please note this difference.
> 
> Ah, sorry. I was replying to Tami because he said he has `>` written to a buffer so I assume it's the prompt thingy.
> 
> Anyway, I couldn't reproduce your issue using the provided minimal `init.vim`.

**Comment by mrdgo** [comment] 2021-02-08 08:57
> > I feel like you actually experience different bugs.
> > There is no prompt buffer written in my case.
> > In my case the search string from the prompt buffer is written into my file.
> > please note this difference.
> 
> Ah, sorry. I was replying to Tami because he said he has `>` written to a buffer so I assume it's the prompt thingy.
> 
> Anyway, I couldn't reproduce your issue using the provided minimal `init.vim`.

Thanks for your effort!
I will add a more detailed description on how this happens.

**Comment by mrdgo** [comment] 2021-02-08 09:09
I tried it out, thank you for the suggestion!

It didn't help.

**Comment by tobyond** [comment] 2021-02-27 00:03
I've experienced this issue too. The only thing I could track it down to was the fact that it would only happen if I used `<C-c>` to exit the window, I've since switched to using `<esc>` to exit, and haven't seen it since. A quick perusal of the mappings https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/mappings.lua#L9 doesn't really reveal anything specific since they both call `actions.close`. Although I never could ascertain why there is an `i` table that has the `<C-c>` in it, and an `n` table that has the `<esc>`.

**Comment by Conni2461** [comment] 2022-05-22 09:58
I am closing this as stale. I've never experienced this issue and there wasn't any activity for over a year so i dont think it still is an issue.

If i am wrong i kindly ask you to create a new issue, filling out the new bug report template. Thanks :)

**Closed by Conni2461** 2022-05-22 09:58 UTC
Labels: bug
