### ISSUE TITLE
Render picker in a persistent window instead of a popup

### ISSUE THREAD

**Issue by lorefnon** [nvim-telescope/telescope.nvim#1967] opened 2022-05-25 14:36 UTC
**Is your feature request related to a problem? Please describe.**

Is there a way to render the picker in a persistent window eg. I'd like to bind a command that render live_grep picker in a window that doesn't go away when a file is selected. 

I am aware of the resume feature, but that gets clunky when telescope is being used for multiple things so often I run telescope resume to end up in an actions window instead of my last live grep and then I remember the action selector also uses telescope. I see that it takes an index but that is not as intuitive as just having the picker in a regular vim buffer instead of a popup.

**Additional context**
Intellij has a feature to pin the search tool window, which is exactly what I am looking for.

**Comment by Conni2461** [comment] 2022-05-29 10:42
currently not on the roadmap, would require a lot of changes

**Comment by lorefnon** [comment] 2022-05-29 11:31
Ok, thanks for your reply (and for your work on telescope).

For my own usage I found that a simple alternative was to just use vim features. 

1. Create new buffer: `:new`
2. Run external command and inject its output into current buffer eg: `:r! rg project`, `:r! 'fd .*.md'`
3. Use `C-w f` to open any file reference in a new window

This is pretty unfancy (and also not live) but adequate.

**Comment by Conni2461** [comment] 2022-05-29 11:58
I prefer to keep it open for now

**Comment by lorefnon** [comment] 2022-06-05 10:08
The [vim-side-search](https://github.com/ddrscott/vim-side-search) plugin is pretty nice for this kind of use case.

**Comment by Conni2461** [comment] 2022-06-30 12:59
This actually is a duplicate of https://github.com/nvim-telescope/telescope.nvim/issues/310

So i would close this issue in favor of #310 (keeping the oldest issue)

**Closed by Conni2461** 2022-06-30 12:59 UTC
Labels: enhancement
