### ISSUE TITLE
Errors while executing basic commands in latest neovim v0.5.0-dev+1140-g097ec71bd

### ISSUE THREAD

**Issue by saahiluppal** [nvim-telescope/telescope.nvim#640] opened 2021-03-11 18:42 UTC
Same error for all these commands

:Telescope find_files<cr>
:Telescope live_grep<cr>
:Telescope buffers<cr>
:Telescope help_tags<cr>
```bash
E5108: Error executing lua vim.lua:269: Tried to call API function with vim.fn: 
use vim.api.nvim_create_buf instead
```

I know things break while using nightly release.
Still it might be helpful for developers to know

**Comment by clason** [comment] 2021-03-11 18:43
This should already be fixed. Can you update to the latest version of telescope.nvim **and plenary.nvim** and try again?

**Comment by Conni2461** [comment] 2021-03-11 18:46
and popup :) the error was in popup

**Comment by saahiluppal** [comment] 2021-03-11 18:49
Updated all the plugins.
Now another problem arises.

:Telescope find_files
WORKS FINE
Hit CTRL-C
```bash
Error executing vim.schedule lua callback: ...ig/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:905: Invalid buffer id: 44                                                            
Error executing vim.schedule lua callback: ...ig/nvim/plugged/telescope.nvim/lua/telescope/pickers.lua:905: Invalid buffer id: 44
```

**Comment by Conni2461** [comment] 2021-03-11 19:06
This is weird. No one has touched that code in a while. Are you hitting `c-c` in normal or insert mode?

**Comment by saahiluppal** [comment] 2021-03-12 07:51
Insert Mode

**Comment by deibit** [comment] 2021-03-16 18:58
Similar behaviour here. Mine shows:

With minimal lua.init. Only loading Telescope.

:Telescope find_files

(mode autochanges to INSERT) 

Cannot move with c-n or c-p, does not show highlight bar...and when pressing c-c to get out:

`E5108: Error executing lua ...pack/packer/start/telescope.nvim/lua/telescope/utils.lua:189: attempt to call field 'nvim_buf_delete' (a nil value)`

Using neovim from MacOS brew (HEAD)

**Comment by Conni2461** [comment] 2021-03-16 19:27
@saahiluppal I am sorry no idea why yours throwing an error. Couldn't reproduce it :|

@deibit pretty sure your neovim is just out of date. `nvim_buf_delete` is like 4 - 5 months old and you can't do `c-n`, `c-p` because we use `nvim_buf_set_text` like 1 - 2 month old. Try `brew upgrade --HEAD --fetch-HEAD neovim` or something like this. I am not a mac guy

**Comment by deibit** [comment] 2021-03-16 20:12
> @deibit pretty sure your neovim is just out of date. `nvim_buf_delete` is like 4 - 5 months old and you can't do `c-n`, `c-p` because we use `nvim_buf_set_text` like 1 - 2 month old. Try `brew upgrade --HEAD --fetch-HEAD neovim` or something like this. I am not a mac guy

Ok. Have to compile neovim from repo by my own (thankfully neovim team is doing such a great work). brew do not point to the tip of the repo yet (even with HEAD). Can confirm works like a charm. Awesome project you got here.

**Comment by keeslinp** [comment] 2021-03-18 16:45
I am having the same issue as @saahiluppal whenever I exit out of the file selector. Didn't have it before, but I just updated to the latest telescope and it started happening.

**Comment by saahiluppal** [comment] 2021-03-19 11:41
I am not very sure, but i guess nerd-font is the reason.

Installed linux again, reconfigured neovim and everything was working fine
installed nerd-font to get devicons working, and this problem starts again.

**Comment by luc-tielen** [comment] 2021-03-19 13:10
I am also running into it, I have Fira Code nerd-font. So @saahiluppal might be correct.

**Comment by Conni2461** [comment] 2021-03-19 19:46
I know whats going on. Its because we actually cleaning up buffers now. Not related to fonts.
Fix will be in #664

**Comment by luigibertaco** [comment] 2021-03-23 04:52
> Ok. Have to compile neovim from repo by my own (thankfully neovim team is doing such a great work). brew do not point to the tip of the repo yet (even with HEAD). Can confirm works like a charm. Awesome project you got here.

hey @deibit , I think the issue with the brew upgrade is that the nightly build doesn't create a new release on updates, you can force brew to reinstall it with `brew reinstall neovim`, it worked for me.

**Comment by deibit** [comment] 2021-03-23 06:41
> > Ok. Have to compile neovim from repo by my own (thankfully neovim team is doing such a great work). brew do not point to the tip of the repo yet (even with HEAD). Can confirm works like a charm. Awesome project you got here.
> 
> hey @deibit , I think the issue with the brew upgrade is that the nightly build doesn't create a new release on updates, you can force brew to reinstall it with `brew reinstall neovim`, it worked for me.

Thank @luigibertaco, currently I'm happy with my own build. Tried what you did on other machine with an Apple M1 and can confirm it works. Thanks for the update.

**Closed** 2021-03-30 10:32 UTC
Labels: bug
