### ISSUE TITLE
Gruvbox colorscheme not working

### ISSUE THREAD

**Issue by davebrouwer1** [nvim-telescope/telescope.nvim#2001] opened 2022-06-12 14:31 UTC
### Description

Whenever I select the gruvbox theme in the Telescope colorscheme, it throws an error: "

`E5108: Error executing lua .../start/telescope.nvim/lua/telescope/builtin/internal.lua:973: Vim(colorscheme):E5113: Error while calling lua chunk: ...m/site/pack/packer/start/gruvbox.nvim/colors/gruvbox.lua:6: attempt to call field 'load' (a nil value)
stack traceback:
        ...m/site/pack/packer/start/gruvbox.nvim/colors/gruvbox.lua:6: in main chunk
        [C]: in function 'cmd'
        .../start/telescope.nvim/lua/telescope/builtin/internal.lua:973: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:242: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
stack traceback:
        [C]: in function 'cmd'
        .../start/telescope.nvim/lua/telescope/builtin/internal.lua:973: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:242: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk`

All the other colorschemes seem to be working, except for the gruvbox one, gruvbox flat works as well.

### Neovim version

```markdown
NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Windows 11, WSL 2 Arch

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - ERROR: rg: not found. `live-grep` finder will not function without [BurntSushi/ripgrep](https://github.com/BurntSushi/ripgrep) installed.
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `notify`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. :Telescope colorscheme 
2. Select gruvbox theme

### Actual behavior

Error message.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment] 2022-06-12 14:54
Can't reproduce and your minimal config doesn't provide the gruvbox theme. We dont provide support if you dont fill out the template correctly and provide a reproduce that works show when running neovim with `nvim -nu min.lua`. I'll close this but i take another look at this if you fix the template and write down the steps to reproduce, including `nvim -nu`

Just saying but `require("gruvbox").load()` fails so, i think there might be multiple lua `gruvbox` versions installed that conflict.

**Closed by Conni2461** 2022-06-12 14:54 UTC
Labels: bug

**Comment by davebrouwer1** [comment] 2022-06-12 14:58
Ah yes, I am stupid, I had multiple gruvbox versions installed which caused the error, im sorry for wasting your time, thanks for the help though!
