### ISSUE TITLE
rg don't exit

### ISSUE THREAD

**Issue by nzlov** [nvim-telescope/telescope.nvim#1159] opened 2021-08-24 13:27 UTC
### Description

When using `live_grep ` the query, if you enter and switch entries quickly, it will get stuck and rg will have multiple processes

### Neovim version

NVIM v0.5.0

### Operating system and version

macos 11.4

### Steps to reproduce

1. [LunarVim](https://github.com/LunarVim/LunarVim)
2. open big project
3. open live_grep()
4. enter and switch entries quickly

### Actual behavior

![image](https://user-images.githubusercontent.com/2859981/130624103-37159aba-110c-4b07-a24b-d3cd8f624304.png)

https://user-images.githubusercontent.com/2859981/130627873-d4a287dd-0cb2-4582-b30f-8453a23e7849.mp4

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by clason** [comment] 2021-08-24 14:02
Please use the provided minimal config. If you can only reproduce with LunarVim, it's _not_ an issue with Telescope and should be reported at their repo.

**Comment by nzlov** [comment] 2021-08-24 14:21
@clason Sorry, I don't know basic Lua configuration neovim right now, so I have to use a third party integrated configuration and I still reproduce the problem using `NvChad` which I just installed.

**Comment by clason** [comment] 2021-08-24 14:27
I cannot reproduce this, though (also on macOS).

**Comment by nzlov** [comment] 2021-08-24 14:28
Please find a big project

**Comment by clason** [comment] 2021-08-24 14:29
Define "big project". (I'm testing on the neovim repo.)

**Comment by clason** [comment] 2021-08-24 14:30
Also, did you check whether these `rg` processes exit eventually?

**Comment by nzlov** [comment] 2021-08-24 14:36
When `nvim` exits, the `rg` is over.
I think the problem should be that the last RG query process is not closed, and the new RG process has begun, causing the previous unable to turn off.


https://user-images.githubusercontent.com/2859981/130636334-e4196eac-1902-4380-bbdf-677569067f2f.mp4

**Comment by clason** [comment] 2021-08-24 14:39
That's intended; canceling an async job is not trivial. So currently a new job is spawned and just allowed to finish, which might take a while on a giant project (>>100K files). I need to grep over my whole home directory (>500K files) before I can see `rg` processes left running after I (immediately) close neovim.

**Comment by nzlov** [comment] 2021-08-24 14:57
I know, the problem is why the previous process is not closed. Do they have completed the process automatically?

**Comment by clason** [comment] 2021-08-24 14:59
The process is not closed, no, because it exits by itself when it has finished going through the current directory.

**Comment by nzlov** [comment] 2021-08-24 15:03
Sorry, I didn't see them exited. Even for a long time.

**Comment by nzlov** [comment] 2021-08-24 15:04
You need to quickly change the query string during the query

**Comment by nzlov** [comment] 2021-08-24 15:54
Use Docker to run Archlinux, you can recover.

* init
```
docker run -dit  archlinux /bin/bash
docker exec -it id /bin/bash 
pacman -Syu neovim git ripgrep make gcc
mkdir -p ~/.config/nvim
nvim ~/.config/nvim/init.lua
nvim
```

* maybe need build fzf-native
```
cd /tmp/nvim/site/pack/packer/start/telescope-fzf-native.nvim
make
```

* test
```
cd /
nvim
:lua require('telescope.builtin').live_grep()
```

quickly change the query string during the query

**Comment by synthmeat** [comment] 2021-12-02 17:03
Just to note that this is still an issue with latest telescope and nvim 0.6. Everything vanilla, Appimage on debian, ripgrep 13.0.0

**Comment by quetz** [comment] 2022-04-18 20:07
Having this issue as well. Every time you interrupt search in progress (by pressing a key and changing search query) number of `rg` processes increases. 

I see that https://github.com/nvim-telescope/telescope.nvim/issues/1159 is not merged yet, so I can't confirm if it fixes this issue.

**Comment by quetz** [comment] 2022-04-19 05:39
https://github.com/nvim-telescope/telescope.nvim/pull/1856 fixes it for me

**Comment by nesqi** [comment] 2022-04-22 19:22
I can confirm that https://github.com/notjrbauer/telescope.nvim/commit/71df0e2444d0941d9ceded2732ebffac18df2e6a does NOT fix this issue. Just tried it and it does not solve the issue for me.

**Closed** 2022-04-30 10:33 UTC
Labels: bug
