### ISSUE TITLE
Exact search instead of fuzzy search

### ISSUE THREAD

**Issue by leosolid** [nvim-telescope/telescope.nvim#1083] opened 2021-08-05 04:16 UTC
Couldn't tell if there was a way to do this. In FZF you can start the search with `'` to search for exact matches only. Does telescope have something similar?

**Comment by fdschmidt93** [comment] 2021-08-05 05:56
As far as I can tell, [telescope-fzf-native.nvim](https://github.com/nvim-telescope/telescope-fzf-native.nvim) supports this just like fzf as evident [here](https://github.com/nvim-telescope/telescope-fzf-native.nvim/blob/main/src/fzf.c#L1112) (though I have virtually zero C experience ;).

I've also tried it and it seems to work as intended :)

There is ongoing work to highlight that telescope-fzf-native.nvim is recommended and likely will eventually be shipped with telescope itself.

#988 
#1066

**Comment by fdschmidt93** [comment] 2021-08-05 08:19
Closing as I think the answer was accepted :) Happy to re-open and help further if there's any other open questions.

**Closed by fdschmidt93** 2021-08-05 08:19 UTC
Labels: enhancement
