### ISSUE TITLE
invalid event user telescopefindpre

### ISSUE THREAD

**Issue by caycun** [nvim-telescope/telescope.nvim#2735] opened 2023-10-11 05:31 UTC
### Description

E5108: Error executing lua: ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:347: Invalid 'event': 'User TelescopeFindPre'
stack traceback:
        [C]: in function 'nvim_exec_autocmds'
        ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:347: in function 'find'
        ...tart/telescope.nvim/lua/telescope/builtin/__internal.lua:750: in function 'v'
        ...tart/telescope.nvim/lua/telescope/builtin/__internal.lua:1362: in function 'v'
        ...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:514: in function <...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:483>

### Neovim version

```markdown
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1696795921
```

### Operating system and version

arch linux latest

### Telescope version / branch / rev

telescope 0.1.0

### checkhealth telescope

```markdown
i cant copy all is installed except ripgrep/live-grep and fd
```

### Steps to reproduce

use my keybinds and run any command

### Expected behavior

commands should work properly

### Actual behavior

its showing an error instead
E5108: Error executing lua: ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:347: Invalid 'event': 'User TelescopeFindPre'
stack traceback:
        [C]: in function 'nvim_exec_autocmds'
        ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:347: in function 'find'
        ...tart/telescope.nvim/lua/telescope/builtin/__internal.lua:750: in function 'v'
        ...tart/telescope.nvim/lua/telescope/builtin/__internal.lua:1362: in function 'v'
        ...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:514: in function <...cker/start/telescope.nvim/lua/telescope/builtin/init.lua:483>

### Minimal config

```Lua
local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, {})
vim.keymap.set('n', '<C-p>', builtin.git_files, {})
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
vim.keymap.set('n', '<leader>vh', builtin.help_tags, {})
```

**Comment by Conni2461** [comment] 2023-10-11 05:36
dupe of #2734

Ill look into it

**Comment by Conni2461** [comment] 2023-10-11 06:03
Your bug is already no longer present in the latest stable release 0.1.3

Please make sure to update to the latest stable version (0.1.3) or 0.1.4 once this version is released

**Closed by Conni2461** 2023-10-11 06:03 UTC
Labels: bug

**Comment by coffebar** [comment] 2023-10-11 18:58
I have the same on both 0.1.3 and 0.1.4, NVIM v0.9.4

commit 7011ea
```
Error executing Lua callback: ...ck/packer/start/telescope.nvim/lua/telescope/pickers.l
ua:347: Invalid 'event': 'User TelescopeFindPre'
stack traceback:
        [C]: in function 'nvim_exec_autocmds'
        ...ck/packer/start/telescope.nvim/lua/telescope/pickers.lua:347: in function 'f
ind'
        ...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:350: in function 'v
'
        ...im/lazy/telescope.nvim/lua/telescope/builtin/__files.lua:595: in function 'v
'
        .../nvim/lazy/telescope.nvim/lua/telescope/builtin/init.lua:541: in function <.
../nvim/lazy/telescope.nvim/lua/telescope/builtin/init.lua:500>
        ...share/nvim/lazy/telescope.nvim/lua/telescope/command.lua:188: in function 'r
un_command'
        ...share/nvim/lazy/telescope.nvim/lua/telescope/command.lua:253: in function 'l
oad_command'
        ...ocal/share/nvim/lazy/telescope.nvim/plugin/telescope.lua:108: in function <.
..ocal/share/nvim/lazy/telescope.nvim/plugin/telescope.lua:107>
```

**Comment by coffebar** [comment] 2023-10-11 19:23
My bad, that module was loaded from the wrong plugin manager. Version  0.1.4 is actually ok.

**Comment by realestninja** [comment] 2023-11-09 12:26
After the latest manjaro system update, I got this error too.

I am using the preset plugin configuration by "lunar vim's base IDE" (not available anymore since recently) where the commit hashes were pinned.

I removed the pinned commit hash for nvim-telescope/telescope.nvim and pinned the current stable version instead. 

This fixed it for me:
```
  use { "nvim-telescope/telescope.nvim", tag = '0.1.4' }
```

**Comment by flppv** [comment] 2023-11-11 08:06
Thanks, @realestninja, that helped! Mine was at 0.1.0 all the time

**Comment by Msouza91** [comment] 2023-12-09 23:44
Got the same issue with nvim 0.10 and telescope 0.1.5, reverting to 0.1.4 is a workaround

**Comment by jamestrew** [comment] 2023-12-10 00:00
@Msouza91 I'm certain this issue doesn't exist on 0.1.5. The line that makes this error possible doesn't exist 0.1.3+.

If anyone else is continuing to experiencing this issue after updating to 0.1.3+ (including 0.1.5), please verify that you've properly updated telescope. Try rm -rf'ing the directory where telescope is installed and try installing again making sure your config isn't pinned to an earlier release.

If you're 100% certain and you're still getting this error, please create a new issue with a minimal config.

I'm going to lock this issue since there's a ton of repeated noise between this and duplicate related issues.
