### ISSUE TITLE
better glyph highlighting for xterm and st (suckless terminal)

### ISSUE THREAD

**Issue by smartding** [nvim-telescope/telescope.nvim#358] opened 2020-12-23 08:59 UTC
### Description

For users of xterm and st (suckless terminal), highlighted glyphs in telescope are cut off as shown in the following screenshot. 

It doesn't happen for more “modern” terminals such as  alacritty and kitty.

![pic-selected-201223-1640-49](https://user-images.githubusercontent.com/16423944/102977311-c7a91280-453d-11eb-8abe-6fb298aa83f7.png)

It turned out that in st and xterm, in order to properly highlight a glyph, one has to set the highlight for both the glyph and the white space after it. Not sure when the st and xterm developers would fix this. So I wonder if we can fix this in telescope. 

I tried changing the following line:
https://github.com/nvim-telescope/telescope.nvim/blob/1e3ae2847281b5323cc820fcbe66a0cdcdfe45f2/lua/telescope/make_entry.lua#L112
into `return display, { { {1, 4}, hl_group } }`, it seems to work for functions such as `git_files`, at least for the default setting. But I'm not familiar with telescopes' code, not sure if this is the only place to change.

**Expected Behavior**

glyphs shouldn't be cut off. 

### Details

<details><summary>Reproduce</summary>

1. enable `color_devicons` of telescope
2. run any telescope functions with popup in st or xterm
2. you can see the cut off of glyphs
</details>

<details><summary>Environment</summary>

- nvim version: v0.5.0-dev+965-gd0668b36a
- Operating system:  archlinux
- Telescope commit: 1e3ae2847281b5323cc820fcbe66a0cdcdfe45f2

</details>

<details><summary>Configuration</summary>
<p>
 

Doesn't matter what configuration I use.

**Comment by tami5** [comment] 2020-12-23 14:17
This might be flagged as wontfix, but just for the record I have the same issue (using st). One way I was able to fix it is to add space in the icons plugin render. But that made it look ugly.

I think its a font related thing, but I would appreciate ideas or workarounds telescope can provide to overcome this.

**Comment by tjdevries** [comment] 2020-12-23 20:16
Hmmm, maybe try and make sure the icon highlights don't have italics?

**Comment by smartding** [comment] 2020-12-24 02:59
> Hmmm, maybe try and make sure the icon highlights don't have italics?

it's not the italics, the glyph for golang files are also cut off, it has no italic.
![pic-selected-201224-1056-21](https://user-images.githubusercontent.com/16423944/103056098-fa531980-45d6-11eb-95c2-dfb69b5e0205.png)

**Comment by Conni2461** [comment] 2020-12-24 09:51
I am also using st and i noticed that too but i am also thinking this is an bug inside st and the suckless guys say thats an bug in libxft. Because the same think can also be reproduced with emoji's and the fix for that is using `font2` and having the emoji font render at a smaller size.

Its not really the highlighting that gets cut of its the whole glyph. Also your mentioned fix does nothing for me and tamis fix as well. It is just really weird, i can reproduce the cutting of of glyphs in a normal buffer as well, if i hover over different chars. But on the other side it just works for my statusline 😆, which uses the `nvim-web-devicons` as well.
Maybe i figure something out next week but i wouldn't bet on it.
https://streamable.com/evyx4v

**Comment by gregorias** [comment] 2021-03-20 19:21
@Conni2461 Do you have a link to the root cause bug in libxft? If yes, could you provide it so that people can track progress on it?

**Comment by nimaipatel** [comment] 2021-09-25 16:19
Using this path worked for me https://github.com/Dreomite/st/commit/e3b821dcb3511d60341dec35ee05a4a0abfef7f2. Also, obviously, it fixed glyph rendering in all plugins.

![image](https://user-images.githubusercontent.com/53116839/134778404-67a7710a-6f75-47b1-b793-feb7412b7c32.png)

**Comment by Conni2461** [comment] 2021-12-10 15:47
This needs to be fixed at terminal-emulator level. Not here. Closing

**Closed by Conni2461** 2021-12-10 15:47 UTC
Labels: help wanted, reproducible
