### ISSUE TITLE
"Use colors from nvim-devicons" cause high CPU usage, sometimes nvim process gets killed

### ISSUE THREAD

**Issue by smartding** [nvim-telescope/telescope.nvim#190] opened 2020-10-25 08:14 UTC
Right after I pulled the latest update of telescope, I noticed a high CPU usage when running `telescope.builtin.git_files` in source code tree with 7k+ files.  And sometimes the whole nvim process is killed, dropping me back to command line.

Then I locally deleted the commit `a8e780708698a4` `feat: Use colors from nvim-devicons`, everything returns normal. 

Can we revert this feature until performance is improved? Or provide an option to disable this feature.

**Comment by tjdevries** [comment] 2020-10-25 12:21
Huh, that's very weird -- I can't figure out why that would happen. Does it happen immediately when running git files? can you paste your setup as well?

I did add a way to turn it off though: 113a516 you can use `color_devicons = false` in your configuration to turn the feature off.

**Comment by tjdevries** [comment] 2020-10-25 12:21
(but we shouldn't close this issue til I can track down the performance issue)

**Comment by smartding** [comment] 2020-10-25 12:37
> Huh, that's very weird -- I can't figure out why that would happen. Does it happen immediately when running git files? can you paste your setup as well?
> 
> I did add a way to turn it off though: [113a516](https://github.com/nvim-lua/telescope.nvim/commit/113a516c63fb6e1ae1fb01173ed8fefdf450b08a) you can use `color_devicons = false` in your configuration to turn the feature off.

It doesn't happen immediately after I run git_files, cpu usage doesn't go up much after I type in a query. But once I start deleting some characters with backspace, cpu usage goes through the roof.

Here's my config for telescope:
```lua
local telescope = {}

telescope.edit_dotfiles = function()
  local opts = require('telescope.themes').get_dropdown{
    cwd = '~/.config',
    -- add symbolic links too, most of my dotfiles are symlinked
    find_command = { 'fd', '--type', 'f', '--type', 'l' },
    prompt_title = 'dotfiles',
    previewer = false,
    borderchars = {
      prompt = {"─", "│", " ", "│", "┌", "┐", "│", "│"},
      results = {"─", "│", "─", "│", "├", "┤", "┘", "└"},
    }
  }

  require('telescope.builtin').find_files(opts)
end

telescope.lsp_workspace_symbols =  function()
  local input = vim.fn.input('Query: ')
  vim.api.nvim_command('normal :esc<CR>')
  vim.api.nvim_command('echom "' .. input .. '"')
  if not input or #input == 0 then return end
  require('telescope.builtin').lsp_workspace_symbols{
      query = input
  }
end

telescope.setup = function()

  require('telescope').setup{
    defaults = {
      borderchars = { '─', '│', '─', '│', '┌', '┐', '┘', '└'},
      generic_sorter = require'telescope.sorters'.get_fzy_sorter,
    }
  }
  local opts = { noremap=true, silent=true }
  vim.api.nvim_set_keymap('n', '<C-p>', ":lua require('telescope.builtin').git_files()<CR>", opts)
  vim.api.nvim_set_keymap('n', '<leader>f', ":lua require('telescope.builtin').find_files()<CR>", opts)
  vim.api.nvim_set_keymap('n', '<leader>e', ":lua require('telescope.builtin').lsp_document_symbols()<CR>", opts)
  vim.api.nvim_set_keymap('n', '<leader>w', ":lua require('plugins.telescope').lsp_workspace_symbols()<CR>", opts)
  -- vim.api.nvim_set_keymap('n', '<leader>w', ":lua require('telescope.builtin').lsp_workspace_symbols()<CR>", opts)
  vim.api.nvim_set_keymap('n', '<leader>r', ":lua require('telescope.builtin').lsp_references()<CR>", opts)
  vim.api.nvim_set_keymap('n', '<leader>/', ":lua require('telescope.builtin').live_grep()<CR>", opts)
  vim.api.nvim_set_keymap('n', '<leader>b', ":lua require('telescope.builtin').buffers()<CR>", opts)
  vim.api.nvim_set_keymap('n', '<leader>t', ":lua require('telescope.builtin').treesitter()<CR>", opts)
  vim.api.nvim_set_keymap('n', '<leader>ed', ":lua require('plugins.telescope').edit_dotfiles()<CR>", opts)

  vim.api.nvim_command("highlight! link TelescopeSelection Type")
  vim.api.nvim_command("highlight! link TelescopeMatching Statement")
end

return telescope
```

**Comment by tjdevries** [comment] 2020-10-25 13:03
Interesting, so only after backspace it does it. Even if you've only typed something like two characters and then backspace once?

**Comment by smartding** [comment] 2020-10-25 13:11
> Interesting, so only after backspace it does it. Even if you've only typed something like two characters and then backspace once?
Type in two characters and backspace one doesn't trigger high CPU usage.
I experimented a bit more, and I found CPU usage goes up whenever I type/backspace the search query very fast. backspace is just a special case, because I usually type fast when backspacing.

**Comment by smartding** [comment] 2020-10-25 13:19
CPU usage is back to normal after I set  `color_devicons = false`, no matter how fast I type/backspace

**Comment by tjdevries** [comment] 2020-10-25 17:36
Does it matter which sorter you are using?

**Comment by smartding** [comment] 2020-10-26 02:50
> Does it matter which sorter you are using?

I was using the regular file sorter. 
I just tried fyz sorter by `file_sorter = require'telescope.sorters'.get_fzy_sorter`,  same problem. I can't tell which sorter is worse, because both caused high cpu usage, and killed neovim process, even htop stopped working when all this happened.

Does each backspace trigger a new sort operation? So if I backspace fast, multiple sort operation will be trigger at the same time? Since I've got 7k+ files to sort, those concurrent sort operations take all my CPU cores.

**Comment by tjdevries** [comment] 2020-10-26 04:06
It shouldn't be possible for it to take up more than one core because neovim is single-threaded and we are operating in process.

yes, the multiple sorts are a problem and I'm currently working on a large refactor that should at least make this more manageable (and definitely not re-sort for every intermediate keypress, if you have pressed several in a row). 

So hopefully this problem will get significantly better in the next week or so. I'll definitely be on the lookout for ways to debug this issue better.

**Comment by tjdevries** [comment] 2020-11-13 20:29
Does this still happen btw? Just wondering if it is still happening.

**Comment by smartding** [comment] 2020-11-13 23:25
> Does this still happen btw? Just wondering if it is still happening.

Yes, after turning `color_devicons` back on, there's still high CPU usage and neovim process is killed if I run `git_files` and do some fast backspacing in the prompt.

I tried this in my github.com/kubeedge/kubeedge repo, I also cloned the neovim repo, the problem happens too.

**Comment by tjdevries** [comment] 2020-11-14 02:37
Can you show me the output of version? Also what is your distro?

**Comment by smartding** [comment] 2020-11-14 02:54
> Can you show me the output of version? Also what is your distro?

Sure. Here's output from `nvim --version`
```
NVIM v0.5.0-832-g35325ddac
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/smart/.cache/yay/neovim-git/src/build/config -I/home/smart/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/smart/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/smart/.cache/yay/neovim-git/src/build/include
Compiled by smart

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
I'm using archlinux, I installed neovim with the neovim-git aur.

**Comment by smartding** [comment] 2020-11-28 01:37
Just to report  that the problem is still there, after I installed 'nvim-telescope/telescope-fzy-native.nvim' plugin

**Comment by jedrzejboczar** [comment] 2020-12-14 22:53
Hi, I can also confirm the issue.

I did some more testing and it seems that it is more the memory usage what kills the process, then CPU usage. For me the CPU usage is just 100% on a single core at a time but the memory usage grows after each character pressed and the memory is not deallocated until the buffer closes. This way one can easily use up whole RAM or, with some memory limit per process, the process will die.

I can also confirm that `color_devicons = false` fixes the problem, so that's somehow related to highlights, because it's the only thing that this option changes. I dug through the code to find where the highlight [gets set](https://github.com/nvim-telescope/telescope.nvim/blob/dfeebffd93ecf4a6abac29c078ca58ddf6bf107c/lua/telescope/pickers.lua#L852). It does not seem to be ever cleared, so I tried adding `a.nvim_buf_clear_namespace(self.results_bufnr, ns_telescope_entry, 0, -1)` [here](https://github.com/nvim-telescope/telescope.nvim/blob/dfeebffd93ecf4a6abac29c078ca58ddf6bf107c/lua/telescope/pickers.lua#L538), before each finder iteration. It actually helped greatly. The memory still grows but in much lower increments. The behavior looks like this:
![telescope_mem_usage](https://user-images.githubusercontent.com/16623787/102144279-804bc380-3e65-11eb-8513-949b362a7aa7.png)
Both 1) and 2) are exactly the same query sequences, but in 2) I added the mentioned highlight clearing. 1) is longer because it worked much slower. This was ran in a directory with ~17k files.

I don't really know the Neovim source code, but maybe the issue is actually there? Or is it something more that is not getting cleared in telescope? Of course my solution is not good, because the highlights disappear for a moment between clearing them and adding new ones.

Just for reference, I was testing `builtin.find_files` and this is my config:
```lua
require('telescope').setup {
    defaults = {
        prompt_position = 'top',
        sorting_strategy = 'ascending',
        layout_strategy = 'flex',
        winblend = 10,
        file_sorter = require('telescope.sorters').get_fzy_sorter,
        generic_sorter = require('telescope.sorters').get_fzy_sorter,
        --color_devicons = false,
    }
}

require('telescope').load_extension('fzy_native')
```

**Comment by tjdevries** [comment] 2020-12-18 05:03
If anyone wants to test out #344 for various highlight bug fixes, that'd be cool. It might (?) fix this problem? :) let me know

**Comment by smartding** [comment] 2020-12-18 05:25
> If anyone wants to test out #344 for various highlight bug fixes, that'd be cool. It might (?) fix this problem? :) let me know

I ran `git_files` a few times in a large repo, it seems the PR fixes this issue

**Comment by jedrzejboczar** [comment] 2020-12-20 11:32
I can also confirm that the changes fix the issue. I ran the same tests as before and the memory usage is dramatically lower than without the fix. I tested on revision https://github.com/nvim-telescope/telescope.nvim/commit/eca83f214ab6c64ca8df838a306d1a4570accd31 (before the PR got reverted).

I also did some more tests and by repeatably writing and deleting the query I can see that memory usage increases slowly but steadily. However it happens even with `color_devicons = false`, so it's not related to devicons. Also, it's not really a big deal as I cannot imagine having a need to stay in the picker for that long.

**Closed** 2020-12-22 15:10 UTC
Labels: !!, bug
