### ISSUE TITLE
Telescope doesn't work probably if we remap`:` key. after #e454a0a

### ISSUE THREAD

**Issue by lenguyenthanh** [nvim-telescope/telescope.nvim#1913] opened 2022-05-03 16:20 UTC
### Description

Telescop stops working after https://github.com/nvim-telescope/telescope.nvim/commit/e454a0ad37ba72a14bebe516f99935c16f33ca50 if we remap `:` key.

The problem is this we rely on `:` to enter command line mode(thanks @fdschmidt93 for your input).

I know two hacky solutions which are:

1. Revert to the previous commit.

2. For example if you remap `:` and `;` you can go to `telescope.nvim` source and then change this line: https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/pickers.lua#L449 to `local cmd = ";startinsert!|call histdel('cmd', -1)|echon ''<CR>"`

### Neovim version

```markdown
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.7.0/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

MacOS 12.3.1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====

## Telescope Extension: `frecency`
  - INFO: No healthcheck provided

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `gradle`
  - INFO: No healthcheck provided

## Telescope Extension: `heading`
  - INFO: No healthcheck provided

## Telescope Extension: `luasnip`
  - INFO: No healthcheck provided

## Telescope Extension: `metals`
  - INFO: No healthcheck provided

## Telescope Extension: `neoclip`
  - INFO: No healthcheck provided

## Telescope Extension: `scaladex`
  - INFO: No healthcheck provided
```

### Steps to reproduce

Add these mappings to `minimial_ini.lua`
```
-- switch : ;
map("n", ";", ":")
map("n", ":", ";")
map("t", ";", ":")
map("t", ":", ";")
map("v", ";", ":")
map("v", ":", ";")
```
then run `nvim -nu minimal_init.lua`

### Expected behavior

It should work normally

### Actual behavior

It shows some thing like this:

<img width="711" alt="Screen Shot 2022-05-03 at 16 25 17" src="https://user-images.githubusercontent.com/437967/166472446-007e5eba-2d8e-43dd-bd65-5f020465eead.png">

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]

-- switch : ;
map("n", ";", ":")
map("n", ":", ";")
map("t", ";", ":")
map("t", ":", ";")
map("v", ";", ":")
map("v", ":", ";")
```

**Comment by levouh** [comment] 2022-05-03 16:32
Referencing the conversation on #1912, I do not have `:` nor `<Esc>` remapped and I get the same issue as mentioned above (the literal text `:startinsert!|call histdel('cmd', -1)|echon ''` in the _Telescope_ input window upon opening it). More often, however, I use a mapping that invokes a _Telescope_ window, and perhaps 2/3 of the time it is just immediately closed ("action callbacks" and whatnot still happen). This is likely anecdotal, but it tends to happen to me more often when I am doing an action that produces a lot of results - finding files on a huge mono-repo, or listing branches in a giant work code base, etc.

My configuration is all over the place, so I take this with a grain of salt as I'm sure the differing behavior is due to something I've done myself. I am not available to work on reproducing it with a minimal configuration right now, but I will do as soon as possible.

**Comment by fdschmidt93** [comment] 2022-05-03 16:33
I'll just revert that commit for the time being and then we'll (most likely Conni and I) find a better solution.

**Comment by lenguyenthanh** [comment] 2022-05-03 16:41
It works now on latest master. Thanks for your quick action!

**Comment by tjdevries** [comment] 2022-05-03 16:52
Thanks @fdschmidt93 <3 perhaps there is something we can do in neovim core to make this work better?

**Comment by tjdevries** [comment] 2022-05-03 16:52
(we can talk in different thread perhaps)

**Comment by levouh** [comment] 2022-05-03 16:54
@fdschmidt93 mine are all over the place and I'm 99% sure they are a byproduct of my own config oddities, my comment was to mostly add contextual information to see if it helped debug. I would not be worried about catering to my issues - I will debug it myself and extract it into something useful if I find it.

The issue I had before, however, was that I would intermittently get a `A` entered in the _Telescope_ prompt window (roughly the same use cases as mentioned above, but different outcomes), which I imagine reverting will likely return. Either way, its all the same problem that I've had my own issues with (e.g. native `prompt` buffers not starting in the right mode) that is not fun to circumvent.

---

>In brief, it's a pretty unfortunate interaction with how ex commands are scheduled and how nvim's event loop works with our async pickers. That's in a nutshell why we are relying on raw input as it schedules more appropriately (as opposed to vim.cmd [[ startinsert! ]] or nvim_feedkeys)

My solution - which is obviously limited in impact to only me & my config, hence allowing them to be a bit more belligerent - was to wrap things like this in a `vim.schedule` call to get them to happen "when I wanted them to" (largely meaning just "not right now, but soon"). When scheduled, things like `startinsert!` _seemed_ to work more reliably, but even that was a bit intermittent. A lot of my use case were things like "start insert mode if not in insert mode on entering _X_ window" - usually triggered from `WinEnter`. The problem with that was that sometimes the `autocmd` fired too soon, and I'd still be stuck in normal mode at the end of it all, even though when the event fired I was in insert mode so things _seemed_ fine.

`</rambling>`. I ended up with this _monstrosity_ for now that seems to handle most of the use cases I'm interested in:

```
util.start_insert = function(winid, callback, ...)
  local args = { ... }
  local curcb, maxcb = 0, 10

  local dcb, lcb
  dcb = function()
    if vim.api.nvim_get_mode().mode ~= "i" then
      vim.cmd("startinsert")
    end

    if callback then
      vim.schedule(function()
        callback(unpack(args))
      end)
    end
  end

  lcb = function()
    curcb = curcb + 1

    if not winid or vim.api.nvim_get_current_win() == winid then
      dcb()
    elseif curcb <= maxcb then
      vim.defer_fn(lcb, 30)
    end
  end

  vim.defer_fn(lcb, 30)
end
```

**Comment by fdschmidt93** [comment] 2022-05-03 17:13
> Thanks @fdschmidt93 <3 perhaps there is something we can do in neovim core to make this work better?

@Conni2461 and I've been meaning to find a time to have a telecorp chat -- I know he's been to some degree also through that fight (the `nvim_feedkeys` route, which funnily enough triggers the finder loop twice as per below)

```lua
local builtin = require("telescope.builtin")

local index = 0
builtin.find_files({
  on_complete = {
    function()
      index = index + 1
      -- 2 with `nvim_feedkeys`
      require("telescope.log").warn(index)
    end,
  },
})
```
That's essentially how the `nvim_input` (abomination, I'm afraid) came to be.

I was very excited seeing https://github.com/neovim/neovim/pull/18306 which maybe can help?

Let's see

@levouh wow, kind of a monstrosity we seem to have been working in parallel towards :laughing: . Maybe the above linked neovim PR will help :sweat_smile: . As a reference, the commit I reverted used `nvim_input` to literally input `:startinsert!` since that works appropriately in the event loop as opposed to `vim.cmd [[startinsert!]]` -- it's a quite astounding problem.

As per the random entries of `A`, I haven't been able to repro this and, again, sincerely apologize and will look to find a universal solution asap. For more context, to give you a feeling of the problem space (merely a quantum solace, I understand)

Initial modes in a telescope picker need to be appropriately handled
- coming from any mode and going to normal/insert mode
- coming from another picker going to normal/insert mode (probably the one that is the primary problem right now since prompt buffer patches)
- having `default_text` in all of the above combinations
- not triggering the finder loop twice (which is another very stupid problem) due to `on_complete` callbacks

which quickly amounts to an absurd explosion of combinations :/

**Comment by fdschmidt93** [comment] 2022-05-03 17:29
I'll close this as the "original" issue is addressed; any follow-up discussion should please happen in #1915 -- the new kitchen sink for initial mode setting at picker start up :sweat_smile:

**Closed by fdschmidt93** 2022-05-03 17:29 UTC
Labels: bug
