### ISSUE TITLE
Highlight of fuzzy match breaks when using matchers like (.*)

### ISSUE THREAD

**Issue by AndreiCalazans** [nvim-telescope/telescope.nvim#2015] opened 2022-06-18 21:41 UTC
### Description

When searching using grep_live the matching term does not get highlighted as expected when using matchers like `.*`.

### Neovim version

```markdown
NVIM v0.8.0-dev+414-ge420cd6c6
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 12.3

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

search term: `function.*\)`

### Expected behavior

search term: `function`

<img width="700" alt="image" src="https://user-images.githubusercontent.com/20777666/174457714-1cbd6d9a-8d99-414d-b98b-ba4b94137980.png">

### Actual behavior

However, it breaks when we use ReGex like matchers

search term: `function.*\)`
<img width="700" alt="image" src="https://user-images.githubusercontent.com/20777666/174457719-1de55ef7-62e4-493e-9c14-99b4c8733522.png">

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment] 2022-06-26 09:21
duplicate of https://github.com/nvim-telescope/telescope.nvim/issues/1708

**Closed by Conni2461** 2022-06-26 09:21 UTC
Labels: bug
