### ISSUE TITLE
Buffers picker :: Odd colorization of highlighted lines

### ISSUE THREAD

**Issue by lcrockett** [nvim-telescope/telescope.nvim#1213] opened 2021-09-05 03:53 UTC
### Description

Using the `buffers` picker, colorization of the highlighted line in the preview window recently seems to have changed. Whereas previously the highlighted line in the Telescope preview window looked the same as highlighting it in a regular buffer.

Depending on the colorscheme, characters like parentheses are sometimes difficult to read. Furthermore this behaviour cannot be replicated when using a different picker that highlights lines in the preview window, for instance the `current_buffer_fuzzy_find`.

This change got introduced by commit [79dc995f820150d5de880c08e814af327ff7e965](https://github.com/nvim-telescope/telescope.nvim/commit/79dc995f820150d5de880c08e814af327ff7e965). Reading through a few other issues like https://github.com/nvim-telescope/telescope.nvim/issues/1151, disabling Treesitter resolves the issue, but as said already in that thread; it's a workaround and rather obvious that the problem disappears when disabling Treesitter.

### Neovim version

NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

MacOS 11.5.2 + Ubuntu 20.04

### Steps to reproduce

1. Neovim (+)0.5.0 loaded up with Treesitter, Telescope, and (optionally) a custom colorscheme (for instance, solarized :: ishan9299/nvim-solarized-lua)
2. Open any file (for instance a Lua file) and navigate to a line with text. Bonus points if navigating to a line that contains parentheses or curly braces
3. Open the picker : : Telescope buffers
4. Boom 💥

### Expected behavior

I would expect highlighted lines in a Telescope preview window to look the same as they do in a regular buffer as right right now colorization is a bit off in preview windows for the `buffers` picker.

### Actual behavior

Prior to commit `79dc995f820150d5de880c08e814af327ff7e965`
![telescope-good-00](https://user-images.githubusercontent.com/58056722/132114371-a576710c-99b1-4316-8ba1-2c5a0c5e5b48.jpg)

With commit `79dc995f820150d5de880c08e814af327ff7e965`
![telescope-bad-00](https://user-images.githubusercontent.com/58056722/132114372-5a2aaa06-0cd1-459c-9bad-50df2f76cac2.jpg)

How a selected line looks like in a regular buffer (latest, so post `79dc995f820150d5de880c08e814af327ff7e965` commit)
![telescope-good-01](https://user-images.githubusercontent.com/58056722/132114375-21e16b0e-3c62-4ddd-b348-95b3fff3f753.jpg)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      { "nvim-treesitter/nvim-treesitter" },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  require("nvim-treesitter.configs").setup {
    ensure_installed = { "lua" },
    highlight = { enable = true },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment] 2021-09-05 15:46
Just to check, is the highlighting the same as if you'd visually select the line (3rd screenshot says no?)? Is it consistent with, say, `builtin.live_grep`. That is how it should be and seems to be for me. My guess then is highlight groups + highlighting commands have a sideways interaction for you.

What does `:hi visual` return for you with solarized?

> Furthermore this behaviour cannot be replicated when using a different picker that highlights lines in the preview window. 

As means of background, we recently changed the way previewer works for the buffers picker #1120 to use the actual buffers such that previewing special buffers (like terminals) works correctly. Other previewers actually create new temporary buffers that, as a welcome side effect, solve a lot of things quite nicely when it comes to highlighting and opening/closing previews. However, previewing terminals then is not really possible.

**Comment by fdschmidt93** [comment] 2021-09-06 15:46
Could you please provide a very detailed repo?

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      {
        "nvim-telescope/telescope.nvim",
        requires = {
          "nvim-lua/plenary.nvim",
          { "nvim-telescope/telescope-fzf-native.nvim", run = "make" },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      { "nvim-treesitter/nvim-treesitter" },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require("telescope").setup {
    pickers = {
      find_files = {
        theme = "ivy",
      },
    },
  }
  require("telescope").load_extension "fzf"
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  require("nvim-treesitter.configs").setup {
    ensure_installed = {"lua"},
    highlight = {
      enable = true, -- false will disable the whole extension
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing Telescope and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

and opening `nvim -u minimal_init.lua minimal_init.lua` and then navigating to a line with curly brackets works as intended for me.

**Comment by lcrockett** [comment] 2021-09-12 23:56
If I highlight a line in a regular buffer outside of Telescope, the highlighting is as expected (no weird colored highlights). It is therefore consistent with e.g. `builtin.live_grep`.

`:hi Visual` -> `Visual         xxx guifg=#002b36 guibg=#586e75 guisp=nil`

I seem to have pinpointed the issue with the `p00f/nvim-ts-rainbow` plugin that highlights parentheses. Once enabled and activated, the issue appears. If deactivated or uninstalled, the issue does not appear. BTW. the same goes for `lewis6991/spellsitter.nvim`. Using the spellsitter plugin. highlights also get garbled within the Telescope buffer preview. For sake of consistency however i'm only focusing on the `nvim-ts-rainbow` plugin in this case.

An updated minimal configuration:

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      {
        "nvim-telescope/telescope.nvim",
        requires = {
          "nvim-lua/plenary.nvim",
          { "nvim-telescope/telescope-fzf-native.nvim", run = "make" },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      {
        "nvim-treesitter/nvim-treesitter",
        config = function()
          require('nvim-treesitter.configs').setup {
            additional_vim_regex_highlighting = false,
            autopairs = { enable = true },
            ensure_installed = {
              'lua',
            },
            highlight = { enable = true },
            indent = { enable = true },
            rainbow = {
              enable = true,
              extended_mode = false,
            },
          }
        end
      },
      { "ishan9299/nvim-solarized-lua" },
      { "p00f/nvim-ts-rainbow" },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require("telescope").setup {
    pickers = {
      find_files = {
        theme = "ivy",
      },
    },
  }
  require("telescope").load_extension "fzf"
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  require("nvim-treesitter.configs").setup {
    ensure_installed = {"lua"},
    highlight = {
      enable = true, -- false will disable the whole extension
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing Telescope and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment] 2021-09-13 07:24
The minimal init lua seems incomplete as eg the theme is not activated adequately. I'm pretty sure that there is this issue but it's not reproduced out-of-the-box. This is with the cursor being on the curly bracket. I need a step-by-step repro in which the minimal init lua + steps produces this out-of-the-box, as hunting bugs myself I'm afraid is a bit too much overhead.

![brr](https://user-images.githubusercontent.com/39233597/133040935-bdf2e00b-391c-4990-b58e-df05340c7b90.png)

**Comment by lcrockett** [comment] 2021-09-26 23:06
Of course and apologies, I seem to have forgotten the colorscheme activation instructions. See updated minimal init lua here below and screenshots using this specific init lua.

If you need any extra info or details, let  me know.

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
  require("packer").startup {
    {
      "wbthomason/packer.nvim",
      {
        "nvim-telescope/telescope.nvim",
        requires = {
          "nvim-lua/plenary.nvim",
          { "nvim-telescope/telescope-fzf-native.nvim", run = "make" },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      {
        "nvim-treesitter/nvim-treesitter",
        config = function()
          require('nvim-treesitter.configs').setup {
            additional_vim_regex_highlighting = false,
            autopairs = { enable = true },
            ensure_installed = {
              'lua',
            },
            highlight = { enable = true },
            indent = { enable = true },
            rainbow = {
              enable = true,
              extended_mode = false,
            },
          }
        end
      },
      {
        "ishan9299/nvim-solarized-lua",
        config = function()
          vim.o.termguicolors = true
          vim.cmd("colorscheme solarized")
        end,
      },
      { "p00f/nvim-ts-rainbow" },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. "/plugin/packer_compiled.lua",
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require("telescope").setup {
    defaults = { layout_strategy = 'vertical' },
    pickers = {
      find_files = {
        theme = "ivy",
      },
    },
  }
  require("telescope").load_extension "fzf"
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  require("nvim-treesitter.configs").setup {
    ensure_installed = {"lua"},
    highlight = {
      enable = true, -- false will disable the whole extension
    },
  }
end
if vim.fn.isdirectory(install_path) == 0 then
  print "Installing Telescope and dependencies."
  vim.fn.system { "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path }
end
load_plugins()
require("packer").sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

Regular buffer:
![image](https://user-images.githubusercontent.com/58056722/134827164-e9cab225-3dc6-4be6-bea1-102f1cd6f8fb.jpeg)

Regular buffer - Line VISUAL selected:
![image](https://user-images.githubusercontent.com/58056722/134827170-d4f9c975-a6e7-4f8d-a84f-bef99e45a61e.jpeg)

Telescope - buffers picker:
![image](https://user-images.githubusercontent.com/58056722/134827179-c489804c-f73b-4baf-b124-912b97586659.jpeg)

Telescope - live_grep picker:
![image](https://user-images.githubusercontent.com/58056722/134827190-5c4cf08c-ea2a-409c-992d-ea2435cd1be5.jpeg)

**Closed** 2021-10-04 20:35 UTC
Labels: bug
