### ISSUE TITLE
devicons appears always white

### ISSUE THREAD

**Issue by heyn0r** [nvim-telescope/telescope.nvim#728] opened 2021-04-05 12:13 UTC
### Description
Hey there! I'm new to the Vim-Universe and am just struggling with the settings for Telescope.
When I open Telescope (:Telescope find_files), the logos for the corresponding file extensions also appear. However, these are always white. If I understood the Telescope settings correctly, then color_devicons is true by default. Nevertheless, I have run it in my nvim.init additional. What is the reason that I don't see colored icons? Is it a setting issue of the theme (Dracula), of nvim_web_devicons, of Telescope or of the font (Fira Code Nerd Font)?

Thanks for your time and help!

**Expected Behavior**
Expected colored Icons

**Actual Behavior**
Always white Icons

### Details

<details><summary>Reproduce</summary>

1. take my nvim.init file
2. :Telescope find_files
3. .... bang here is the issue
</details>

<details><summary>Environment</summary>

- nvim --version output:
NVIM v0.5.0-dev+6db3ba9
Build type: Release
LuaJIT 2.1.0-beta3
- Operating system:
MacOS 11.2.3

</details>

<details><summary>Configuration</summary>
<p>

```viml
syntax on

set nu
set relativenumber
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set hidden
set nowrap
set scrolloff=8
set colorcolumn=80
set signcolumn=yes

call plug#begin('~/.vim/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'gruvbox-community/gruvbox'
Plug 'vim-airline/vim-airline'
Plug 'kyazdani42/nvim-web-devicons'
call plug#end()

let mapleader = " "
nnoremap <leader>pv :wincmd v<bar> :Ex <bar> :vertical resize 30<CR>

nnoremap <leader>ff <cmd>Telescope find_files<cr>
nnoremap <leader>fg <cmd>Telescope live_grep<cr>
nnoremap <leader>fb <cmd>Telescope buffers<cr>
nnoremap <leader>fh <cmd>Telescope help_tags<cr>

lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}

EOF
colorscheme gruvbox

**Comment by windwp** [comment] 2021-04-05 12:29
set termguicolors

**Comment by heyn0r** [comment] 2021-04-05 13:32
Thanks for your reply. It's still there.

<img width="269" alt="whiteIcons" src="https://user-images.githubusercontent.com/64201500/113579064-0e6dd480-9624-11eb-8f9e-7bf6e990689d.png">

**Comment by fdschmidt93** [comment] 2021-04-05 16:04
If I recall correctly, this most likely it boils down to load order or missing `setup` call of nvim web devicons.

Make sure that devicons are set up after your colorscheme (many of which clear highlight groups, consequently clearing highlights of devicons) and before telescope.

**Comment by Conni2461** [comment] 2021-04-06 19:50
Okay there was a bug with was caused by wrong order but it got fixed in `nvim_web_devicons`.

See https://github.com/nvim-telescope/telescope.nvim/issues/652 for the whole discussion.

Closing for now. Feel free to reopen if it still doesn't work

**Closed by Conni2461** 2021-04-06 19:50 UTC
Labels: bug
