### ISSUE TITLE
live_grep not displaying results

### ISSUE THREAD

**Issue by Tyson453** [nvim-telescope/telescope.nvim#2161] opened 2022-09-05 16:39 UTC
### Description

Whenever I use :Telescope live_grep the window shows no output. I searched up the issue and found a few previous issues that encountered the same thing. Those issues said to install the plugin "BurntSushi/ripgrep" but that didn't fix anything. I'm using packer to install plugins and whenever I run :PackerStatus , it shows that ripgrep is installed. However, when I run :checkhealth telescope it says ripgrep is not installed.

### Neovim version

```markdown
NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Windows 11

### Telescope version / branch / rev

'master' branch

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - ERROR: rg: not found. `live-grep` finder will not function without [BurntSushi/ripgrep](https://github.com/BurntSushi/ripgrep) installed.
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====

## Telescope Extension: `media_files`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. type ":Telescope live_grep" in neovim
2. type something in

### Expected behavior

I expect the window to display the results of the search.

### Actual behavior

The window is blank

### Minimal config

```Lua
local status, telescope = pcall(require, "telescope")
if not status then
    return
end

telescope.load_extension("media_files")

local actions = require "telescope.actions"

telescope.setup {
    defaults = {
        prompt_prefix = " ",
        selection_caret = " ",
        path_display = { "smart" },

        mappings = {
            i = {
                ["<C-n>"] = actions.cycle_history_next,
                ["<C-p>"] = actions.cycle_history_prev,

                ["<C-c>"] = actions.close,

                ["<Down>"] = actions.move_selection_next,
                ["<Up>"] = actions.move_selection_previous,

                ["<CR>"] = actions.select_default,
                ["<C-x>"] = actions.select_horizontal,
                ["<C-v>"] = actions.select_vertical,
                ["<C-t>"] = actions.select_tab,

                ["<C-u>"] = actions.preview_scrolling_up,
                ["<C-d>"] = actions.preview_scrolling_down,

                ["<PageUp>"] = actions.results_scrolling_up,
                ["<PageDown>"] = actions.results_scrolling_down,

                ["<Tab>"] = actions.toggle_selection + actions.move_selection_worse,
                ["<S-Tab>"] = actions.toggle_selection + actions.move_selection_better,
                ["<C-q>"] = actions.send_to_qflist + actions.open_qflist,
                ["<M-q>"] = actions.send_selected_to_qflist + actions.open_qflist,
                ["<C-l>"] = actions.complete_tag,
                ["<C-_>"] = actions.which_key, -- keys from pressing <C-/>

                ["<C-k>"] = actions.move_selection_next,
                ["<C-l>"] = actions.move_selection_previous,

            },

            n = {
                ["<esc>"] = actions.close,
                ["<CR>"] = actions.select_default,
                ["<C-x>"] = actions.select_horizontal,
                ["<C-v>"] = actions.select_vertical,
                ["<C-t>"] = actions.select_tab,

                ["<Tab>"] = actions.toggle_selection + actions.move_selection_worse,
                ["<S-Tab>"] = actions.toggle_selection + actions.move_selection_better,
                ["<C-q>"] = actions.send_to_qflist + actions.open_qflist,
                ["<M-q>"] = actions.send_selected_to_qflist + actions.open_qflist,

                ["<Down>"] = actions.move_selection_next,
                ["<Up>"] = actions.move_selection_previous,
                ["gg"] = actions.move_to_top,
                ["G"] = actions.move_to_bottom,

                ["<C-u>"] = actions.preview_scrolling_up,
                ["<C-d>"] = actions.preview_scrolling_down,

                ["<PageUp>"] = actions.results_scrolling_up,
                ["<PageDown>"] = actions.results_scrolling_down,

                ["?"] = actions.which_key,

                ["k"] = actions.move_selection_next,
                ["l"] = actions.move_selection_previous,
                ["j"] = actions.move_to_top,
                ["M"] = actions.move_to_middle,
                [";"] = actions.move_to_bottom,
            },
        },
    },

    pickers = {
        -- Default config for builtin pickers
    },

    extensions = {
        media_files = {
            filetypes = {"png","webp","jpg","jpeg"},
            find_cmd = "rg",
        }
    },
}
```

**Comment by Conni2461** [comment] 2022-09-06 06:30
BurntSushi/ripgrep is a binary that needs to be installed like a normal program, not like a vim plugin. I dont think packer does anything with it other than closing the repository.

Checkhealth is here correct `live_grep` will never show results if we dont find the ripgrep binary.

So install it similar to neovim (which you have probably done with chocolatey or scoop)

**Comment by carlosgrillet** [comment] 2022-09-08 02:55
> BurntSushi/ripgrep is a binary that needs to be installed like a normal program, not like a vim plugin. I dont think packer does anything with it other than closing the repository.
> 
> Checkhealth is here correct `live_grep` will never show results if we dont find the ripgrep binary.
> 
> So install it similar to neovim (which you have probably done with chocolatey or scoop)

Thanks, it solve the problem for me. I just read the docs at [https://github.com/BurntSushi/ripgrep](url) and follow the instalation steps (debian for me) and just after that `live_grep` now is working fine

**Comment by Conni2461** [comment] 2022-09-17 08:52
Seems to be resolved, closing

**Closed by Conni2461** 2022-09-17 08:52 UTC
Labels: bug

**Comment by e1leet** [comment] 2023-02-06 18:59
> BurntSushi/ripgrep is a binary that needs to be installed like a normal program, not like a vim plugin. I dont think packer does anything with it other than closing the repository.
> 
> Checkhealth is here correct `live_grep` will never show results if we dont find the ripgrep binary.
> 
> So install it similar to neovim (which you have probably done with chocolatey or scoop)

Thanks, you helped me

**Comment by bornedj** [comment] 2023-08-10 15:14
This is potential a regression. Running into the same issue with telescope version 0.1.2. Running nvim 0.8.3 built with apt, within a wsl Ubuntu instance. Ripgrep was installed with apt-get, and its binary is on my PATH, and can be used within the terminal.

Running `checkhealth telescope` returns the following:
```
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```
