### ISSUE TITLE
`man_pages` not work

### ISSUE THREAD

**Issue by SnakeHit** [nvim-telescope/telescope.nvim#2326] opened 2023-01-16 06:27 UTC
## Input the command `:Telescope man_pages` in command mode, the window have nothing

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/45898625/212610944-62d12d1c-3e29-44ba-a972-e1ae60618d93.png">

## But input `:Man 3 printf`, the neovim will open a horizontal window which displays normally.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/45898625/212611296-69c5bbe6-c68e-41a9-abe3-ad044f3da08a.png">

### Neovim version

```markdown
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.2/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

macOS 13.0.1

### Telescope version / branch / rev

telescope 0.1.0

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====

## Telescope Extension: `file_browser`
  - INFO: No healthcheck provided

## Telescope Extension: `frecency`
  - OK: sql.nvim installed.
  - OK: nvim-web-devicons installed.

## Telescope Extension: `project`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. nvim
2. `:Telescope man_page`

### Expected behavior

work normally

### Actual behavior

nothing

### Minimal config

```Lua
-- use { "Yggdroot/LeaderF", cmd = "Leaderf", run = ":LeaderfInstallCExtension" }
    use {
        'nvim-telescope/telescope.nvim', tag = '0.1.0',
        -- or                            , branch = '0.1.x',
        requires = { {'nvim-lua/plenary.nvim'} }
    }
    use {
        "nvim-telescope/telescope-frecency.nvim",
        config = function()
          require"telescope".load_extension("frecency")
        end,
        requires = {"kkharji/sqlite.lua"}
    }

    use { 
        "nvim-telescope/telescope-file-browser.nvim",
        config = function()
            require("telescope").load_extension "file_browser"
        end,
    }

    use {
        "nvim-telescope/telescope-project.nvim",
        config = function()
            require'telescope'.load_extension('project')
        end,
    }
```

```
local previewers = require("telescope.previewers")
local Job = require("plenary.job")
local new_maker = function(filepath, bufnr, opts)
  filepath = vim.fn.expand(filepath)
  Job:new({
    command = "file",
    args = { "--mime-type", "-b", filepath },
    on_exit = function(j)
      local mime_type = vim.split(j:result()[1], "/")[1]
      if mime_type == "text" then
        previewers.buffer_previewer_maker(filepath, bufnr, opts)
      else
        -- maybe we want to write something to the buffer here
        vim.schedule(function()
          vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, { "BINARY" })
        end)
      end
    end
  }):sync()
end

require('telescope').setup{
    -- see :help telescope.setup()
    defaults = {
        -- https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/actions/init.lua
        mappings = {
            i = {
                ["<Esc>"] = require('telescope.actions').close,
                ["<Tab>"] = require('telescope.actions').move_selection_previous,
                ["<S-Tab>"] = require('telescope.actions').move_selection_next
            },
        },
        -- The below pattern is lua regex and not wildcard
        file_ignore_patterns = {"%.out", "%.pdf", "%.png", "%.ok"},
        prompt_prefix = "🔍 ",
        path_display={"smart"},
        buffer_previewer_maker = new_maker,
    }
}
```
```

**Comment by mklishevych** [comment] 2023-01-26 12:13
@SnakeHit I'm not a maintainer, but I tried to check your bug on my mac and it works just fine. 

Did you try to debug the problem? E.g. does `on_exit` callback in `new_maker` gets called? Did you try adding `on_stderr` (example below)?

```lua
    on_stderr = vim.schedule_wrap(function(_, line)
      print("Ooopsey")
      print(vim.inspect(line))
    end),

```

**Comment by SnakeHit** [comment] 2023-01-26 12:22
@mklishevych Thanks for your reply, I think this is not related to this configuration. Even I disable all config in telescope.lua, this bug still appear.

**Comment by SnakeHit** [comment] 2023-01-26 12:27
@mklishevych Could you tell me your neovim version in mac?

**Comment by mklishevych** [comment] 2023-01-26 18:39
@SnakeHit same as yours:

```
:version
NVIM v0.8.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by mklishevych** [comment] 2023-01-26 18:46
@SnakeHit what does the following command produce in the shell for you?

```bash
apropos ' '
```

**Comment by SnakeHit** [comment] 2023-01-27 04:26
@mklishevych nothing
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/45898625/215009264-5ca9b183-8bdd-4cbd-bffe-baed53ce37e4.png">

**Comment by mklishevych** [comment] 2023-01-27 13:51
@SnakeHit the problem is definitely with the new MacOS, tried on a different laptop and got the same empty result.
I thought maybe this could be fixed by passing `man_cmd = { "manpath", "-q" }`, but had no luck either. In this case I get some issue from the async job runner, but I don't really understand it.

**Comment by fschauen** [comment] 2023-01-28 22:33
> the problem is definitely with the new MacOS

@mklishevych I also think so, this broke for me with the update to Ventura.

As a workaround, I am using `man_cmd = { "apropos", ".*" }` and it's working for me.

AFAIK `apropos(1)` takes a regular expression as its argument, so this solution just makes it return everything it can find, just like the default Telescope builtin does (or used to in previous macOS versions, I guess):

https://github.com/nvim-telescope/telescope.nvim/blob/dce1156ca103b8222e4abbfc63f9c6887abf5ec6/lua/telescope/builtin/__internal.lua#L771

**Comment by SnakeHit** [comment] 2023-01-29 06:31
@fschauen awesome work, thank you.

**Closed** 2023-01-30 07:01 UTC
Labels: bug

**Comment by mklishevych** [comment] 2023-01-31 10:36
@fschauen nice, thank you! I was using the wrong command, which I took from the PR to neovim without looking :facepalm:

**Comment by fschauen** [comment] 2023-02-01 21:14
@mklishevych you're welcome 😀

Btw, if you're following the `master` branch, just update the plugin and you won't need the workaround above. The PR above (already merged) is a slightly better solution.
