### ISSUE TITLE
Telescope windows with same ordering make custom rendering hard/impossible (ex. Neovide)

### ISSUE THREAD

**Issue by DimitrisMilonopoulos** [nvim-telescope/telescope.nvim#1564] opened 2021-12-06 22:27 UTC
### Description

To display its Telescope creates four windows, all with the same ordering (50). UIs like neovide may try to display Telescope with more advanced rendering, such as applying a transparent blur. Since all Telescope windows have the same order, how they stack ends up being a race condition, causing blurred text at random. Without accurate ordering information, it is impossible to properly blur only text that the user perceives to be "behind" the Telescope window.
Operating system and version: all
checkhealth telescope: N/A

### Neovim version

```markdown
NVIM v0.6.0-dev+566-g4174244d8
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Operating system and version

Manjaro

### checkhealth telescope

```markdown
health#telescope#check
```

### Steps to reproduce

1. Download, build, and run neovide using its instructions: https://github.com/neovide/neovide#install. 
2. Then follow the steps at [#1071](https://github.com/neovide/neovide/issues/1071)

### Expected behavior

Expected behavior:  [#1071](https://github.com/neovide/neovide/issues/1071)

### Actual behavior

Actual behavior:  [#1071](https://github.com/neovide/neovide/issues/1071)

### Minimal config

```Lua
Minimal config: Any setup that opens telescope, when using 

$ neovide --multigrid
```

**Comment by LoipesMas** [comment] 2021-12-07 13:34
Just to add: I'm not sure if nvim api allows for settings custom ordering. I think `50` is just ordering for all floating windows. So this can potentially be something that has to be solved in neovim. 
Unless telescope could just render 1 floating window, but I assume there is a reason why it uses more than one right now.

**Comment by l-kershaw** [comment] 2021-12-21 15:51
It seems like the root cause of this issue has now been resolved within neovide (based on the status of the issues linked).
Therefore, I will close this issue and the related PR in `plenary` ([link](https://github.com/nvim-lua/plenary.nvim/pull/280)).

If I have misunderstood this situation, feel free to reopen this issue and we can discuss further 🙂

**Closed by l-kershaw** 2021-12-21 15:51 UTC
Labels: bug
