### ISSUE TITLE
Default theme

### ISSUE THREAD

**Issue by ikerurda** [nvim-telescope/telescope.nvim#1598] opened 2021-12-16 09:36 UTC
Setting a default theme would be awesome, have you guys considered this option?
```lua
require("telescope").setup {
    defaults = {
        theme = "dropdown",
        ...
    },
    ...
}
```
I end up configuring many pickers to this theme and this seems intuitive and easier.
Thanks for your great work!

**Comment by l-kershaw** [comment] 2021-12-16 10:02
This issue is a duplicate of #938. There is a workaround in the comments that could make things easier for you.

I don't think that anyone is currently working on implementing this in the way you suggest; if you want to have a go, I'm happy to review a PR 🙂

For now, I will close this issue as a duplicate.

**Closed by l-kershaw** 2021-12-16 10:02 UTC
Labels: enhancement
