### ISSUE TITLE
Buffer opened with telescope is blank, while the file contains data.

### ISSUE THREAD

**Issue by MatthiasGrandl** [nvim-telescope/telescope.nvim#1291] opened 2021-09-27 14:07 UTC
### Description

So here is a weird one:

Usually telescope works as expected for me. But using svelte, I sometimes have files that are name `[...slug].svelte`.
When trying to open those files with telescope, the buffer comes up as blank and I assume that due to the special combination of characters... Opening those files directly with any other means, works just fine though. I am not sure how to debug this.

![image](https://user-images.githubusercontent.com/50196894/134922949-dd5c1f31-8ad2-4752-b8bc-16bbc67d0520.png)

### Neovim version

> nvim --version
NVIM v0.5.1
Build type: Release
LuaJIT 2.0.5

### Operating system and version

Linux 5.14.7

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `media_files`
  - INFO: No healthcheck provided
```

### Steps to reproduce

```
mkdir empty-buffer && cd empty-buffer
echo "test" >  \[...slug\].svelte
nvim
:Telescope find_files
```

hit enter and marvel at the absence of the word "test"

### Expected behavior

the word "test" to appear in the opened buffer

### Actual behavior

the opened buffer to be completely blank. Also trying to save results in:
```
"/[...slug].svelte"
E212: Can't open file for writing: permission denied
```

### Minimal config

```Lua
init.lua


paq({ "nvim-telescope/telescope.nvim" })

local telescope = require("telescope")
telescope.setup({})
```

**Comment by fdschmidt93** [comment] 2021-09-27 14:10
I think this is a duplicate of https://github.com/nvim-telescope/telescope.nvim/issues/1171 -- PR to address this would be very welcome :)

**Comment by MatthiasGrandl** [comment] 2021-09-27 14:12
@fdschmidt93 ouch I am sorry. Tried to search for an existing issue, but couldn't find anything. Indeed seems to be the same problem. Feel free to close this as duplicate.

**Comment by fdschmidt93** [comment] 2021-09-27 14:13
No worries :)

**Closed** 2021-09-27 14:12 UTC
Labels: bug
