### ISSUE TITLE
find_files does not leave insert mode on exit

### ISSUE THREAD

**Issue by laxman20** [nvim-telescope/telescope.nvim#82] opened 2020-09-16 01:22 UTC
When you call :lua require'telescope.builtin'.find_files{}, the finder window pops up, but it puts you into insert mode. When you select a file, you will be put back into normal mode.

But if you instead hit Ctrl-c to back out of picking a file, you are still left in insert mode.

**Comment by PanagiotisS** [comment] 2020-09-16 12:47
The same applies for `lua require'telescope.builtin'.find_files{}`.
Additionally, if the completion is open when selecting and opening a file it will remain in insert mode.

# Neovim version

`neovim-0.4.4.0.git.14574.f34eeba2d` -> https://github.com/neovim/neovim/commit/f34eeba2d85b4382d7504e1f3e12a7afb0788c1d

# Minimal init.vim

```vim
" vim:fdm=marker:foldlevel=0
set encoding=utf-8
scriptencoding utf-8

" Remap leader to space - Set it here before start using leader
let g:mapleader="\<Space>"

" Dein 
let s:path = expand(stdpath('config') . '/bundle')
let &runtimepath .= ',' . expand(stdpath('config') . '/bundle/repos/github.com/Shougo/dein.vim/')

if dein#load_state(s:path)
    call dein#begin(s:path, [expand('<sfile>'),])

    call dein#add('Shougo/dein.vim', {
            \ 'hook_add': 'let g:dein#enable_notification = 0'
            \ })

    " call dein#add('Shougo/deoplete.nvim', {
    "             \ 'hook_add': 'let g:deoplete#enable_at_startup = 1'
    "             \ })

    call dein#add('nvim-lua/plenary.nvim')

    call dein#add('nvim-lua/popup.nvim')

    call dein#add('nvim-lua/telescope.nvim', {
        \ 'hook_add': "
        \ nnoremap <silent><leader>gr <cmd>lua require'telescope.builtin'.live_grep{}<cr>\n
        \ nnoremap <silent><leader>r <cmd>lua require'telescope.builtin'.find_files{}<cr>\n
        \ ",
        \ })

    call dein#end()
    call dein#save_state()
endif
call dein#call_hook('source')

" 
filetype plugin indent on
syntax enable

" show the line number
set number
set background=light

inoremap <c-F> <c-X><c-F>
```

# Gif with the problem

- Opening neovim
- Open "find_files"
- Start typing "tes"
- Use "<c-F>" for ins-completion of file names (I re-maped <c-x><c-f> to <c-f> as <c-x> is mapped to split open by telescope.nvim).
- Select and open a file
- It remains in insert mode
- Type one letter, it gets out of insert mode
- undo does not work.

![telescope](https://user-images.githubusercontent.com/11048776/93336845-d3d35480-f817-11ea-8d61-61bd8c587c89.gif)

# Additional comments

If escape is pressed to close the completion menu, everything is ok (first part of the second gif)

If "Shougo/deoplete.nvim" is used for completion then it starts "miss-behaving" and I have to restart neovim
(second part of the gif when I press "a" or "i" it reports "E523: Not allowed here".

![telescope_deoplete](https://user-images.githubusercontent.com/11048776/93338733-33cafa80-f81a-11ea-89ac-cee0ce5ee329.gif)

**Comment by tjdevries** [comment] 2020-09-16 14:31
Wow, thanks for the helpful report!

I will take a look at it.

**Comment by tjdevries** [comment] 2020-09-16 14:54
Does 54f768fd7f93e35da6fec37121b0160f7db9d2a8 fix the problem for you?

I was at least able to first reproduce the filetype completion thing, and then fix that with this commit (for me).

Interested if it fixes the original issue as well.

**Comment by PanagiotisS** [comment] 2020-09-16 15:12
Yes thank you! It fixes both the original <c-c> and the completion menu (at least with my configuration and with the minimal configuration I reported).

While testing, I found one more case where the same problem happens.

- Open a file (e.g. `nvim test1.txt`)
- Edit the file and do NOT save
- Trying to open a different file e.g. `:e test2.txt` will get the obvious message `E37: No write since last change (add ! to override)`
- Use any of the above telescope functions i.e. `find_files` to open a new file will report the follow message
`E5108: Error executing lua ...m/bundle/.cache/init.vim/.dein/lua/telescope/actions.lua:88: Vim(edit):E37: No write since last change (add ! to override)`

There are two cases:

1. Without the completion menu open the message does not appear (you can see it with `:messages`) and it looks like nothing happened (is it by design?)

2. If the completion menu is open, then it behaves as the previous report (remaining in insert mode, pressing a key will get out of insert mode and undo button will ignore the change)

I can record a gif again if you would like.

**Comment by tjdevries** [comment] 2020-09-17 16:47
Ah, is the newest problem then that we actually insert the text from the menu?

If so, can we close this issue and move your stuff to the new one? I don't want to try and track both issues in the same one (since otherwise it's too confusing for me)

**Comment by PanagiotisS** [comment] 2020-09-17 17:00
Sorry. Indeed. There are two issues.

One is indeed where we insert text from the menu (edits 2 and 3).  This can go to a separate issue.

The other one is when we try to open a new file when we have not saved the current one. 
Then, the same behaviour as the previous reports happen. We stay in insert mode and if we press a key, that key inserts in the text and gets back to normal mode. Pressing "u" for undo will not undo that action.
(Original message plus edit 1 for the gif).

**Comment by tjdevries** [comment] 2020-09-25 02:22
OK, We should try this issue out again after my patch to neovim gets merged (or altered and then merged.) I'm hoping it fixes several of these problems.

**Comment by tjdevries** [comment] 2020-09-25 15:19
( This is the fix: https://github.com/neovim/neovim/pull/12977 )

**Comment by tjdevries** [comment] 2020-09-25 15:20
BTW, I cannot tell you how helpful your gifs and comments were on reproducing the issue. Thanks a bunch.

**Comment by PanagiotisS** [comment] 2020-09-25 17:15
I am glad I was able to help. I really enjoy this plugin. Thank you :)
I also watched the vod regarding the solution. It was really interesting!
Maybe it would be helpful to set up an "ISSUE_TEMPLATE.md" requesting a minimal init.vim and steps to reproduce the issue.

**Comment by tami5** [comment] 2020-11-17 07:55
@laxman20 please reopen if this is still on going issue

**Comment by mrdgo** [comment] 2021-04-22 10:36
I still experience both issues.
latest neovim-nightly-bin and also daily updates of telescope and deoplete.

"Not allowed here" and the text insertion.

**Comment by mrdgo** [comment] 2021-06-04 10:27
Until the neovim issue is merged:

```vim
autocmd FileType TelescopePrompt
       \ call deoplete#custom#buffer_option('auto_complete', v:false)
```

this prevents autocompletion for the TelescopePrompt.
Im my case, it prevents the text insertion.

**Comment by simonweil** [comment] 2022-04-19 18:42
I'm getting this `E523: Not allowed here` issue on daily basis :(

**Comment by simonweil** [comment] 2022-04-20 17:03
> Until the neovim issue is merged:
> 
> ```viml
> autocmd FileType TelescopePrompt
>        \ call deoplete#custom#buffer_option('auto_complete', v:false)
> ```
> 
> this prevents autocompletion for the TelescopePrompt. Im my case, it prevents the text insertion.

This worked for me, thanks!

**Closed** 2022-04-20 17:30 UTC
Labels: bug

**Comment by DanielRivasMD** [comment] 2022-04-20 19:04
This does not work for me!

**Comment by Conni2461** [comment] 2022-04-20 19:21
Open a new Issue because currently you provide 0 information for me to work with!

I am locking this conversation. Here is my full statement of why i will no longer respond to these comments: https://github.com/nvim-telescope/telescope.nvim/issues/94#issuecomment-1104216405
