### ISSUE TITLE
Ignore git submodules from search

### ISSUE THREAD

**Issue by tgy** [nvim-telescope/telescope.nvim#1729] opened 2022-01-31 14:40 UTC
**Is your feature request related to a problem? Please describe.**

My problem is that telescope is searching within my git submodules, which can be large and contain many files. I would prefer telescope to search only the source files.

**Describe the solution you'd like**

I would like a setting for telescope that disables searching git submodules.

**Comment by Conni2461** [comment] 2022-01-31 20:05
About which search are we talking. `find_files`? `git_files`? `grep_string`? `live_grep`?

**Comment by tgy** [comment] 2022-02-02 08:55
hey! thanks for your quick reply, it's `find_files`

**Comment by Conni2461** [comment] 2022-02-14 16:22
What do you use for find_files? `fd`, ripgrep` or `find`? you should have filled out the bug template.
But basically `find_files` is only a frontend for one of the above. None them can ignore submodules. And adding this on top from our side would be a none trivial task that is out of scope for this project.

You should use `git_files` for your use case. `help builtin.git_files`.

Closing feel free to reopen if this answer doesn't satisfy you

**Closed by Conni2461** 2022-02-14 16:22 UTC
Labels: enhancement

**Comment by arminveres** [comment] 2023-10-18 12:13
Did anything change? `recurse_submodules` seems to have no effect on the latest telescope version.

**Comment by jamestrew** [comment] 2023-10-18 23:44
Nothing relevant has changed I believe. It still works for me on both on 0.1.4 and nightly.

**Comment by arminveres** [comment] 2023-10-19 07:46
@jamestrew Could I have your configuration for it?
mine is:
```lua
defaults = {
        pickers = {
            git_files = { recurse_submodules = false },
        },
}
```

**Comment by Conni2461** [comment] 2023-10-19 11:43
Please open a new bug report with minimaö rc and reproduce steps

**Comment by jamestrew** [comment] 2023-10-19 17:42
> @jamestrew Could I have your configuration for it? mine is:
> 
> ```lua
> defaults = {
>         pickers = {
>             git_files = { recurse_submodules = false },
>         },
> }
> ```

I thought you want to search git submodule files no?
I just did `:Telescope git_files recurse_submodules=true` for that.

**Comment by arminveres** [comment] 2023-10-19 20:24
@jamestrew no actually the opposite, i would like to exclude submodules and the flag doesn't make a difference.

**Comment by jamestrew** [comment] 2023-10-19 21:07
@arminveres in that case please open a bug report after verifying it with the minimal config in the issue template.

The git module for telescope has not changed in 9 months on the stable branch so `:Telescope git_files` should work.

Maybe check your git config as well. Maybe there's something in there that affects the `git ls-files` command.

**Comment by arminveres** [comment] 2023-10-23 08:28
@jamestrew Yeah, it was something with git itself. Sorry for the mix up.
