### ISSUE TITLE
Question: Disable previewer by default?

### ISSUE THREAD

**Issue by jurisbu** [nvim-telescope/telescope.nvim#1003] opened 2021-07-16 11:06 UTC
I would like to have a default for pickers to have previewer disabled. Currently I have not found a convenient way to set `previewer = false` as default for all pickers. Then I could enable preview for some pickers that makes sense to me.

Currently what I do is disable preview for each picker which is not optimal in my opinion.

```lua
require('telescope').setup{
  pickers = {
    find_files = {
      disable_devicons = true,
      previewer = false,
    },
    file_browser = {
      disable_devicons = true,
      previewer = false,
    },
...
  }
}
```

**Comment by jackhub** [comment] 2021-07-16 11:42
Same to you, this makes me very confused. I set "previewer = false," in defaults, but it does not work.

**Comment by fdschmidt93** [comment] 2021-09-10 05:52
The issue is that the global default is set in that there is dedicated previewer for any picker as they are very individual in nature. Hence, it gets awkward to unify the two easily at picker setup as you'd have conflicting "defaults" and introduces new difficulties (how to opt out of global `previewer = false`).
Furthermore, the user can quite easily introduce default options on their end with simple redirection. I'll suggest that we will add this example to an FAQ (or something) in our documentation overhaul.

```lua
local builtins = require "telescope.builtin"

-- common opts users would like to have a default for
local defaults = { previewer = false, disable_devicons = true }

local pickers = setmetatable({}, {
  __index = function(_, key)
    if builtins[key] == nil then
      error "Invalid key, please check :h telescope.builtin"
      return
    end
    return function(opts)
      opts = vim.tbl_extend("keep", opts or {}, defaults)
      builtins[key](opts)
    end
  end,
})

-- later..
pickers.find_files()
```

**Comment by fdschmidt93** [comment] 2021-09-10 05:52
The issue is that the global default is set in that there is dedicated previewer for any picker as they are very individual in nature. Hence, it gets awkward to unify the two easily at picker setup as you'd have conflicting "defaults" and introduces new difficulties (how to opt out of global `previewer = false`).
Furthermore, the user can quite easily introduce default options on their end with simple redirection. I'll suggest that we will add this example to an FAQ (or something) in our documentation overhaul.

```lua
local builtins = require "telescope.builtin"

-- common opts users would like to have a default for
local defaults = { previewer = false, disable_devicons = true }

local pickers = setmetatable({}, {
  __index = function(_, key)
    if builtins[key] == nil then
      error "Invalid key, please check :h telescope.builtin"
      return
    end
    return function(opts)
      opts = vim.tbl_extend("keep", opts or {}, defaults)
      builtins[key](opts)
    end
  end,
})

-- later..
pickers.find_files()
```

**Comment by fdschmidt93** [comment] 2021-09-10 07:04
Closing this as my solution seems to have been accepted. I've written it done in my notes that is has to make it into FAQ :)

Just ping me here in case there is any problems with my snippet.

**Closed by fdschmidt93** 2021-09-10 07:04 UTC
Labels: enhancement

**Comment by jurisbu** [comment] 2021-09-10 07:14
@fdschmidt93 Thanks! This is a reasonable solution!

**Comment by Conni2461** [comment] 2021-09-12 14:24
> I've written it done in my notes that is has to make it into FAQ :)

You can put it in FAQ for now. But i would prefer be able to set all values in `.setup` for accessibility. That includes
- `previewer =false`
- `theme = "dropdown"` or `theme = "get_dropdown"` (lets threat it as synonym)
- `disable_devicons` i whatever way.

CC @fdschmidt93

**Comment by fdschmidt93** [comment] 2021-09-16 21:40
You can now also set 
```lua
require "telescope".setup {
  defaults = {
    preview = false
  }
}
```

To opt out of previewing for all pickers. Please see `:h telescope.defaults.preview` for more info.
