### ISSUE TITLE
Coloured devicons are clipped in the Telescope popup

### ISSUE THREAD

**Issue by gregorias** [nvim-telescope/telescope.nvim#674] opened 2021-03-20 11:05 UTC
### Description
Coloured devicons are clipped in the Telescope popup:
![Screenshot from 2021-03-20 11-25-33](https://user-images.githubusercontent.com/722385/111866818-6c39c580-8970-11eb-8b5a-6b5863de885e.png)

**Expected Behavior**
The devicons are fully rendered.

**Actual Behavior**
Coloured devicons are clipped.

### Details

1. Open a project directory.
2. `nvim -nu test.vim`
3. `:Telescope find_files`

<details><summary>Environment</summary>

* Neovim: `NVIM v0.5.0-dev+1161-gfa4ee00fa`
* Operating system: Manjaro
* Telescope commit: d4bf118 (18 Mar 2021)

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
  Plug 'kyazdani42/nvim-web-devicons' " for file icons
  Plug 'gruvbox-community/gruvbox'
  Plug 'nvim-lua/popup.nvim'
  Plug 'nvim-lua/plenary.nvim'
  Plug 'nvim-telescope/telescope.nvim'
call plug#end()

set termguicolors
colorscheme gruvbox

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
```

**Comment by elianiva** [comment] 2021-03-20 11:24
it's caused by ST, try another terminal like Alacritty or Kitty.
see https://github.com/nvim-telescope/telescope.nvim/issues/358

**Comment by tami5** [comment] 2021-03-20 12:02
btw it used to happen to me and I use st. Not sure what happen but it no longer happen to me :laughing: . Font issue maybe

**Comment by Melkster** [comment] 2021-06-13 21:41
I have the same problem in [neovim-qt](https://github.com/equalsraf/neovim-qt/) with the font FiraCode, but not in the plugin [nvim-tree.lua](https://github.com/kyazdani42/nvim-tree.lua) for some reason. I'm not sure what's up with that 🤔.

![telescope](https://user-images.githubusercontent.com/15816726/121822660-944f7100-cca0-11eb-9985-8d7e2e612192.png)

**Comment by smartding** [comment] 2021-06-28 13:15
> I have the same problem in [neovim-qt](https://github.com/equalsraf/neovim-qt/) with the font FiraCode, but not in the plugin [nvim-tree.lua](https://github.com/kyazdani42/nvim-tree.lua) for some reason. I'm not sure what's up with that .

nvim-tree.lua doesn't have this issue because of this PR: https://github.com/kyazdani42/nvim-tree.lua/pull/162

**Comment by Melkster** [comment] 2021-06-28 19:22
@smartding  That PR makes one tiny change, so hopefully it's as easy to fix for telescope.nvim?

**Comment by smartding** [comment] 2021-06-29 02:41
> @smartding That PR makes one tiny change, so hopefully it's as easy to fix for telescope.nvim?

The root cause of this issue, according to https://github.com/nvim-telescope/telescope.nvim/issues/358#issuecomment-750828754, lies in libxft. I don't know how to fix that.

The tiny change I made in nvim-tree-lua only hides the issue.

**Comment by Conni2461** [comment] 2022-01-14 17:45
just saying but telescope has a padding: https://github.com/nvim-telescope/telescope.nvim/blob/master/lua/telescope/utils.lua#L455

This is not a telescope bug but can be caused by your gui, terminal emulator or font. Closing

**Closed by Conni2461** 2022-01-14 17:45 UTC
Labels: bug, duplicate

**Comment by fenze** [comment] 2022-08-23 19:37
@gregorias See: https://st.suckless.org/patches/glyph_wide_support/
