### ISSUE TITLE
Error when using git_files

### ISSUE THREAD

**Issue by AgentCosmic** [nvim-telescope/telescope.nvim#1432] opened 2021-11-09 05:55 UTC
### Description

I get an error when using git_files in some projects. Some projects work, some don't.

`E5108: Error executing lua ...me\plugged\telescope.nvim\lua\telescope\actions\init.lua:249: Vim:Error executing lua callback: ...vim\nvim\home\plugged\telescope.nvim\lua\telescope\_.lua:51: attempt to index field 'handle' (a nil value)`

### Neovim version

NVIM v0.5.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-633

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info

### Operating system and version

Windows 10

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 

## Checking external dependencies
  - OK: rg: found ripgrep 0.10.0 (rev 8a7db1a918)
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

:Telescope git_files
No file is shown
Press <esc> to exit
Error is shown, UI is not closed

### Expected behavior

Files should show, no error to happen.

### Actual behavior

E5108: Error executing lua ...me\plugged\telescope.nvim\lua\telescope\actions\init.lua:249: Vim:Error executing lua callback: ...vim\nvim\home\plugged\telescope.nvim\lua\telescope\_.lua:51: attempt to index field 'handle' (a nil value)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment] 2021-11-13 12:54
So only `git_files` is broken?

Does `:messages` show more information?

**Comment by AgentCosmic** [comment] 2021-11-13 14:54
No, all I got was `E5108: Error executing lua ...me\plugged\telescope.nvim\lua\telescope\actions\init.lua:249: Vim:Error executing lua callback: ...vim\nvim\home\plugged\telescope.nvim\lua\telescope_.lua:51: attempt to index field 'handle' (a nil value)` after closing the git window.

**Comment by AgentCosmic** [comment] 2021-11-19 03:01
I found out what causes it. When the directory name has a period e.g. `project.name` will break, but `project-name` is ok.

**Comment by Conni2461** [comment] 2021-11-26 11:31
This might be an windows issue because i cant reproduce this on linux. `telescope.nvim` has a `.` in the name and it works like a charm.

We also probably need better error handling in `_.lua`.

**Comment by Conni2461** [comment] 2021-11-26 11:34
So other git commands also dont work in directories that have a dot in the name? For example `git_commits`

**Comment by AgentCosmic** [comment] 2021-11-26 12:48
Yep, other git commands are failing except `git_status` and `git_branch`.

**Comment by l-kershaw** [comment] 2021-11-26 13:20
I am on Windows and can't reproduce this error with the `telescope.nvim` folder

**Comment by Conni2461** [comment] 2021-11-26 14:07
Can you run this PR https://github.com/nvim-telescope/telescope.nvim/pull/1498
It should give us more error messages. I think the second return value of `uv.spawn` will tell us whats wrong, but i can be wrong

**Comment by Conni2461** [comment] 2021-12-03 14:13
Did you have time to run it with the PR? And does it gives us more debugging information?

**Comment by AgentCosmic** [comment] 2021-12-03 14:57
Hi sorry, was busy last week. How do I run that PR? I'm using vim-plug.

**Comment by Conni2461** [comment] 2021-12-03 15:14
cd into telescope.nvim directory. And checkout the PR like this: `git fetch origin pull/1498/head:pr-1498` and then you can do `git checkout pr-1498`

There are better ways to do this with github cli. `gh pr checkout 1498` inside telescope.nvim dir. Not sure about this tho

**Comment by AgentCosmic** [comment] 2021-12-03 15:18
Still doesn't work, but this time it doesn't throw and error.
Here's a dump of `:messages`
```
[telescope]       <metatable> = <table 2>
[telescope]     }
[telescope]   },
[telescope]   stdin = {
[telescope]     close = <function 15>,
[telescope]     eof_rx = <function 16>,
[telescope]     eof_tx = <function 17>,
[telescope]     read_start = <function 18>,
[telescope]     start = <function 19>,
[telescope]     <metatable> = <table 1>
[telescope]   },
[telescope]   stdout = {
[telescope]     eof_rx = <function 20>,
[telescope]     eof_tx = <function 21>,
[telescope]     handle = <userdata 1>,
[telescope]     <metatable> = <4>{
[telescope]       __call = <function 6>,
[telescope]       __index = <table 4>,
[telescope]       __tostring = <function 7>,
[telescope]       iter = <function 22>,
[telescope]       new = <function 23>,
[telescope]       read = <function 24>,
[telescope]       super = <table 2>,
[telescope]       <metatable> = <table 2>
[telescope]     }
[telescope]   },
[telescope]   uv_opts = {
[telescope]     args = { "ls-files", "--exclude-standard", "--cached", "--others" },
[telescope]     cwd = "",
[telescope]     stdio = {
[telescope]       [2] = <userdata 1>
[telescope]     }
[telescope]   },
[telescope]   <metatable> = <5>{
[telescope]     __index = <table 5>,
[telescope]     _for_each_pipe = <function 25>,
[telescope]     close = <function 26>,
[telescope]     new = <function 27>
[telescope]   }
[telescope] }
[telescope] stack traceback:
[telescope] ^I...vim\nvim\home\plugged\telescope.nvim\lua\telescope\_.lua:69: in function 'spawn'
[telescope] ^I...cope.nvim\lua\telescope\finders\async_oneshot_finder.lua:46: in function 'finder'
[telescope] ^I...im\home\plugged\telescope.nvim\lua\telescope\pickers.lua:437: in function <...im\home\plugged\telescope.nvim\lua\telescope\pickers.lua:436>
[telescope] ^I[C]: in function 'pcall'
[telescope] ^I...im\home\plugged\telescope.nvim\lua\telescope\pickers.lua:436: in function <...im\home\plugged\telescope.nvim\lua\telescope\pickers.lua:384>
[telescope] [WARN  23:16:48] ...im\home\plugged\telescope.nvim\lua\telescope\pickers.lua:441: Finder failed with msg:  ...vim\nvim\home\plugged\telescope.nvim\lua\telescope\_.lua:69: Failed to spawn process: {
[telescope]   command = "git",
[telescope]   pid = "ENOENT: no such file or directory",
[telescope]   stderr = {
[telescope]     close = <function 1>,
[telescope]     eof_rx = <function 2>,
[telescope]     eof_tx = <function 3>,
[telescope]     read_start = <function 4>,
[telescope]     start = <function 5>,
[telescope]     <metatable> = <1>{
[telescope]       __call = <function 6>,
[telescope]       __index = <table 1>,
[telescope]       __tostring = <function 7>,
[telescope]       new = <function 8>,
[telescope]       super = <2>{
[telescope]         __call = <function 6>,
[telescope]         __index = <table 2>,
[telescope]         __tostring = <function 7>,
[telescope]         close = <function 9>,
[telescope]         new = <function 10>,
[telescope]         super = <3>{
[telescope]           __call = <function 6>,
[telescope]           __index = <table 3>,
[telescope]           __tostring = <function 7>,
[telescope]           extend = <function 11>,
[telescope]           implement = <function 12>,
[telescope]           is = <function 13>,
[telescope]           new = <function 14>
[telescope]         },
[telescope]         <metatable> = <table 3>
[telescope]       },
[telescope]       <metatable> = <table 2>
[telescope]     }
[telescope]   },
[telescope]   stdin = {
[telescope]     close = <function 15>,
[telescope]     eof_rx = <function 16>,
[telescope]     eof_tx = <function 17>,
[telescope]     read_start = <function 18>,
[telescope]     start = <function 19>,
[telescope]     <metatable> = <table 1>
[telescope]   },
[telescope]   stdout = {
[telescope]     eof_rx = <function 20>,
[telescope]     eof_tx = <function 21>,
[telescope]     handle = <userdata 1>,
[telescope]     <metatable> = <4>{
[telescope]       __call = <function 6>,
[telescope]       __index = <table 4>,
[telescope]       __tostring = <function 7>,
[telescope]       iter = <function 22>,
[telescope]       new = <function 23>,
[telescope]       read = <function 24>,
[telescope]       super = <table 2>,
[telescope]       <metatable> = <table 2>
[telescope]     }
[telescope]   },
[telescope]   uv_opts = {
[telescope]     args = { "ls-files", "--exclude-standard", "--cached", "--others" },
[telescope]     cwd = "",
[telescope]     stdio = {
[telescope]       [2] = <userdata 1>
[telescope]     }
[telescope]   },
[telescope]   <metatable> = <5>{
[telescope]     __index = <table 5>,
[telescope]     _for_each_pipe = <function 25>,
[telescope]     close = <function 26>,
[telescope]     new = <function 27>
[telescope]   }
[telescope] }
[telescope] stack traceback:
[telescope] ^I...vim\nvim\home\plugged\telescope.nvim\lua\telescope\_.lua:69: in function 'spawn'
[telescope] ^I...cope.nvim\lua\telescope\finders\async_oneshot_finder.lua:46: in function 'finder'
[telescope] ^I...im\home\plugged\telescope.nvim\lua\telescope\pickers.lua:437: in function <...im\home\plugged\telescope.nvim\lua\telescope\pickers.lua:436>
[telescope] ^I[C]: in function 'pcall'
[telescope] ^I...im\home\plugged\telescope.nvim\lua\telescope\pickers.lua:436: in function <...im\home\plugged\telescope.nvim\lua\telescope\pickers.lua:384>
[telescope] [WARN  23:16:48] ...im\home\plugged\telescope.nvim\lua\telescope\pickers.lua:441: Finder failed with msg:  ...vim\nvim\home\plugged\telescope.nvim\lua\telescope\_.lua:69: Failed to spawn process: {
[telescope]   command = "git",
[telescope]   pid = "ENOENT: no such file or directory",
[telescope]   stderr = {
[telescope]     close = <function 1>,
[telescope]     eof_rx = <function 2>,
[telescope]     eof_tx = <function 3>,
[telescope]     read_start = <function 4>,
[telescope]     start = <function 5>,
[telescope]     <metatable> = <1>{
[telescope]       __call = <function 6>,
[telescope]       __index = <table 1>,
[telescope]       __tostring = <function 7>,
[telescope]       new = <function 8>,
[telescope]       super = <2>{
[telescope]         __call = <function 6>,
[telescope]         __index = <table 2>,
[telescope]         __tostring = <function 7>,
[telescope]         close = <function 9>,
[telescope]         new = <function 10>,
[telescope]         super = <3>{
[telescope]           __call = <function 6>,
[telescope]           __index = <table 3>,
[telescope]           __tostring = <function 7>,
[telescope]           extend = <function 11>,
[telescope]           implement = <function 12>,
[telescope]           is = <function 13>,
[telescope]           new = <function 14>
[telescope]         },
[telescope]         <metatable> = <table 3>
[telescope]       },
[telescope]       <metatable> = <table 2>
[telescope]     }
[telescope]   },
[telescope]   stdin = {
[telescope]     close = <function 15>,
[telescope]     eof_rx = <function 16>,
[telescope]     eof_tx = <function 17>,
[telescope]     read_start = <function 18>,
[telescope]     start = <function 19>,
[telescope]     <metatable> = <table 1>
[telescope]   },
[telescope]   stdout = {
[telescope]     eof_rx = <function 20>,
[telescope]     eof_tx = <function 21>,
[telescope]     handle = <userdata 1>,
[telescope]     <metatable> = <4>{
[telescope]       __call = <function 6>,
[telescope]       __index = <table 4>,
[telescope]       __tostring = <function 7>,
[telescope]       iter = <function 22>,
[telescope]       new = <function 23>,
[telescope]       read = <function 24>,
[telescope]       super = <table 2>,
[telescope]       <metatable> = <table 2>
[telescope]     }
[telescope]   },
[telescope]   uv_opts = {
[telescope]     args = { "ls-files", "--exclude-standard", "--cached", "--others" },
[telescope]     cwd = "",
[telescope]     stdio = {
[telescope]       [2] = <userdata 1>
[telescope]     }
[telescope]   },
[telescope]   <metatable> = <5>{
[telescope]     __index = <table 5>,
[telescope]     _for_each_pipe = <function 25>,
[telescope]     close = <function 26>,
[telescope]     new = <function 27>
[telescope]   }
[telescope] }
[telescope] stack traceback:
[telescope] ^I...vim\nvim\home\plugged\telescope.nvim\lua\telescope\_.lua:69: in function 'spawn'
[telescope] ^I...cope.nvim\lua\telescope\finders\async_oneshot_finder.lua:46: in function 'finder'
[telescope] ^I...im\home\plugged\telescope.nvim\lua\telescope\pickers.lua:437: in function <...im\home\plugged\telescope.nvim\lua\telescope\pickers.lua:436>
[telescope] ^I[C]: in function 'pcall'
[telescope] ^I...im\home\plugged\telescope.nvim\lua\telescope\pickers.lua:436: in function <...im\home\plugged\telescope.nvim\lua\telescope\pickers.lua:384>
```

**Comment by Conni2461** [comment] 2021-12-03 15:28
It shouldnt be fixed. It should only give me more debugging messages and it does.

libuv says no such file or directory, which probably references to cwd being an empty string. Which is weird. Give me a little bit of time :)

**Comment by Conni2461** [comment] 2021-12-03 15:42
Are you comfortable with applying a diff

**Comment by AgentCosmic** [comment] 2021-12-04 01:54
Yeah, just tell me what I need to do.

**Comment by Conni2461** [comment] 2021-12-04 08:30
I figured you can just pull the PR again :grimacing:

**Comment by AgentCosmic** [comment] 2021-12-04 10:04
```


E5108: Error executing lua ...me\plugged\telescope.nvim/lua/telescope/actions/init.lua:251: Vim(lua):E5108: Error executing lua ...vim\nvim\home\plugged\telescope.nvim/lua/telescope/_.lua:51: attempt to index field 'handle' (a nil value)
stack traceback:
	...vim\nvim\home\plugged\telescope.nvim/lua/telescope/_.lua:51: in function 'close'
	...cope.nvim/lua/telescope/finders/async_oneshot_finder.lua:28: in function 'close'
	...im\home\plugged\telescope.nvim/lua/telescope/pickers.lua:1300: in function 'on_close_prompt'
	[string ":lua"]:1: in main chunk
	[C]: in function 'nvim_win_close'
	...me\plugged\telescope.nvim/lua/telescope/actions/init.lua:251: in function 'run_replace_or_original'
	...home\plugged\telescope.nvim/lua/telescope/actions/mt.lua:30: in function '_close'
	...me\plugged\telescope.nvim/lua/telescope/actions/init.lua:257: in function 'run_replace_or_original'
	...home\plugged\telescope.nvim/lua/telescope/actions/mt.lua:30: in function 'key_func'
	...m\home\plugged\telescope.nvim/lua/telescope/mappings.lua:235: in function 'execute_keymap'
	[string ":lua"]:1: in main chunk
stack traceback:
	[C]: in function 'nvim_win_close'
	...me\plugged\telescope.nvim/lua/telescope/actions/init.lua:251: in function 'run_replace_or_original'
	...home\plugged\telescope.nvim/lua/telescope/actions/mt.lua:30: in function '_close'
	...me\plugged\telescope.nvim/lua/telescope/actions/init.lua:257: in function 'run_replace_or_original'
	...home\plugged\telescope.nvim/lua/telescope/actions/mt.lua:30: in function 'key_func'
	...m\home\plugged\telescope.nvim/lua/telescope/mappings.lua:235: in function 'execute_keymap'
	[string ":lua"]:1: in main chunk
E5108: Error executing lua ...me\plugged\telescope.nvim/lua/telescope/actions/init.lua:251: Vim:Error executing lua callback: ...vim\nvim\home\plugged\telescope.nvim/lua/telescope/_.lua:51: attempt to index field 'handle' (a nil value)
stack traceback:
	...vim\nvim\home\plugged\telescope.nvim/lua/telescope/_.lua:51: in function 'close'
	...cope.nvim/lua/telescope/finders/async_oneshot_finder.lua:28: in function 'close'
	...im\home\plugged\telescope.nvim/lua/telescope/pickers.lua:1324: in function '_detach'
	...im\home\plugged\telescope.nvim/lua/telescope/pickers.lua:468: in function <...im\home\plugged\telescope.nvim/lua/telescope/pickers.lua:467>
	[C]: in function 'nvim_win_close'
	...me\plugged\telescope.nvim/lua/telescope/actions/init.lua:251: in function 'run_replace_or_original'
	...home\plugged\telescope.nvim/lua/telescope/actions/mt.lua:30: in function '_close'
	...me\plugged\telescope.nvim/lua/telescope/actions/init.lua:257: in function 'run_replace_or_original'
	...home\plugged\telescope.nvim/lua/telescope/actions/mt.lua:30: in function 'key_func'
	...m\home\plugged\telescope.nvim/lua/telescope/mappings.lua:235: in function 'execute_keymap'
	[string ":lua"]:1: in main chunk
stack traceback:
	[C]: in function 'nvim_win_close'
	...me\plugged\telescope.nvim/lua/telescope/actions/init.lua:251: in function 'run_replace_or_original'
	...home\plugged\telescope.nvim/lua/telescope/actions/mt.lua:30: in function '_close'
	...me\plugged\telescope.nvim/lua/telescope/actions/init.lua:257: in function 'run_replace_or_original'
	...home\plugged\telescope.nvim/lua/telescope/actions/mt.lua:30: in function 'key_func'
	...m\home\plugged\telescope.nvim/lua/telescope/mappings.lua:235: in function 'execute_keymap'
	[string ":lua"]:1: in main chunk
```

**Comment by Conni2461** [comment] 2021-12-04 10:22
You should also get something like this before telescope opens. 
![image](https://user-images.githubusercontent.com/15233006/144705895-21f76d7f-6602-4880-b5c3-778b86140c85.png)
I wanna know what of the setup is causing `cwd` being an empty string. An easy fix would be. If `cwd = ""`, set it to nil :laughing: 

I just pushed this fix so you can pull that PR again and it might work. But if you get the logs mentioned above i am still interested in them because i am still looking for the root of the problems.

Thanks for helping me debug this :)

**Comment by AgentCosmic** [comment] 2021-12-04 15:40
Glad to help out.

Still got an error. Note, I had to censor the actual project path because it's a company project.

Before open:
```
{}
D:\Studio\Projects\Clients\company\project.name
{ "D:/Studio/Projects/Clients/company/project.name" } 0
```

Error:
```
E5108: Error executing lua ...me\plugged\telescope.nvim/lua/telescope/actions/init.lua:251: Vim(lua):E5108: Error executing lua ...vim\nvim\home\plugged\telescope.nvim/lua/telescope/_.lua:51: attempt to index field 'handle' (a nil value)
stack traceback:
	...vim\nvim\home\plugged\telescope.nvim/lua/telescope/_.lua:51: in function 'close'
	...cope.nvim/lua/telescope/finders/async_oneshot_finder.lua:28: in function 'close'
	...im\home\plugged\telescope.nvim/lua/telescope/pickers.lua:1300: in function 'on_close_prompt'
	[string ":lua"]:1: in main chunk
	[C]: in function 'nvim_win_close'
	...me\plugged\telescope.nvim/lua/telescope/actions/init.lua:251: in function 'run_replace_or_original'
	...home\plugged\telescope.nvim/lua/telescope/actions/mt.lua:30: in function '_close'
	...me\plugged\telescope.nvim/lua/telescope/actions/init.lua:257: in function 'run_replace_or_original'
	...home\plugged\telescope.nvim/lua/telescope/actions/mt.lua:30: in function 'key_func'
	...m\home\plugged\telescope.nvim/lua/telescope/mappings.lua:235: in function 'execute_keymap'
	[string ":lua"]:1: in main chunk
stack traceback:
	[C]: in function 'nvim_win_close'
	...me\plugged\telescope.nvim/lua/telescope/actions/init.lua:251: in function 'run_replace_or_original'
	...home\plugged\telescope.nvim/lua/telescope/actions/mt.lua:30: in function '_close'
	...me\plugged\telescope.nvim/lua/telescope/actions/init.lua:257: in function 'run_replace_or_original'
	...home\plugged\telescope.nvim/lua/telescope/actions/mt.lua:30: in function 'key_func'
	...m\home\plugged\telescope.nvim/lua/telescope/mappings.lua:235: in function 'execute_keymap'
	[string ":lua"]:1: in main chunk
```

**Comment by Conni2461** [comment] 2021-12-04 18:38
I have a wild guess on whats going on. So i pushed a fix to that branch. Does it work ?

**Comment by faruzzy** [comment] 2021-12-04 22:13
Still getting an error:
```
E5108: Error executing lua ...g/plugged/telescope.nvim/lua/telescope/builtin/files.lua:494: attempt to call field 'is_enabled' (a nil value)
stack traceback:
        ...g/plugged/telescope.nvim/lua/telescope/builtin/files.lua:494: in function 'v'
        ...g/plugged/telescope.nvim/lua/telescope/builtin/files.lua:618: in function 'v'
        ...ig/plugged/telescope.nvim/lua/telescope/builtin/init.lua:496: in function <...ig/plugged/telescope.nvim/lua/telescope/builtin/init.lua:467>
        ....config/plugged/telescope.nvim/lua/telescope/command.lua:179: in function 'run_command'
        ....config/plugged/telescope.nvim/lua/telescope/command.lua:241: in function 'load_command'
        [string ":lua"]:1: in main chunk
```

**Comment by AgentCosmic** [comment] 2021-12-05 02:02
Yes, it actually worked for me!

**Comment by Conni2461** [comment] 2021-12-05 07:21
@faruzzy This issue is unrelated. Please dont hijacked other peoples issues. Next time open a new issue and fill out the template. This time i let it slip and fixed it but thats not the norm. You can pull master and it should work again.

@AgentCosmic You also can switch back to master. Thanks for testing. I'll merge the PR in a second. Glad it works now :)

**Closed** 2021-12-05 07:29 UTC
Labels: bug
