### ISSUE TITLE
Legacy previewers are causing Telescope to leave the buffer in insert mode when the window is closed

### ISSUE THREAD

**Issue by augustocdias** [nvim-telescope/telescope.nvim#1595] opened 2021-12-14 10:44 UTC
### Description

As I discovered in #1573 

When I'm using the legacy previewers, whenever I close the telescope window (if the telescope window is in insert mode) it will keep the insert mode in the current open buffer instead of always going back to normal.

### Neovim version

```markdown
NVIM v0.7.0-dev+717-gf37c5f180
```

### Operating system and version

macOS 12.0.1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - OK: fd: found fd 8.3.0

## ===== Installed extensions =====

## Telescope Extension: `dap`
  - INFO: No healthcheck provided

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `lsp_handlers`
  - INFO: No healthcheck provided

## Telescope Extension: `session-lens`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. nvim -nu `minimal.lua` 
2. Open any telescope window such as `:Telescope find_files`
3. Press `C-c` to close the window

### Expected behavior

I expect the buffer to be in normal mode after the steps and not in insert mode

### Actual behavior

The current buffer stays in insert mode

### Minimal config

```Lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
    require('packer').startup({
        {
            'wbthomason/packer.nvim',
            {
                'nvim-telescope/telescope.nvim',
                requires = {
                    'nvim-lua/plenary.nvim',
                    { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
                },
            },
            -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
        },
        config = {
            package_root = package_root,
            compile_path = install_path .. '/plugin/packer_compiled.lua',
            display = { non_interactive = true },
        },
    })
end
_G.load_config = function()
    require('telescope').setup({
        defaults = {
            file_previewer = require('telescope.previewers').cat.new,
            grep_previewer = require('telescope.previewers').vimgrep.new,
            qflist_previewer = require('telescope.previewers').qflist.new,
        },
    })

    require('telescope').load_extension('fzf')
    -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
    print('Installing Telescope and dependencies.')
    vim.fn.system({ 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path })
end
load_plugins()
require('packer').sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])
```

**Comment by fdschmidt93** [comment] 2021-12-14 10:55
My hunch is one of these things with toggle preview where closing telescope was changed a bit interacts here, as you've mentioned on reddit it's been like that since a couple of weeks roughly coinciding with that. If you are curious, maybe try before and after https://github.com/nvim-telescope/telescope.nvim/pull/1480. But only wild guess.

Generally speaking, as per https://github.com/nvim-telescope/telescope.nvim#previewers these previewers are deprecated. Any reason you are using these over vim buffer previewers? We maybe should remove them to recipes for telescope 1.0 release.

**Comment by augustocdias** [comment] 2021-12-14 14:01
@fdschmidt93 I'm using them because they work more reliably for me... I get several timeouts from the normal one (on big projects) and the worst of wall is that it doesn't support all languages. So syntax highlighting is much better with the deprecated ones.

I am using buffers right now because I rather have no highlighting and/or timeouts than this issue with the insert mode.

**Comment by fdschmidt93** [comment] 2021-12-14 14:07
> I get several timeouts from the normal one (on big projects) and the worst of wall is that it doesn't support all languages.

By big projects you mean very large files with either very large amount of lines or long lines (latter is a scenario in which nvim-treesitter I guess has issues).

> the worst of wall is that it doesn't support all languages.

https://github.com/nvim-treesitter/nvim-treesitter#supported-languages is very expansive. What languages are you working with that are unsupported? They may require plenary PRs such that there filetype is adequately recognized.

You can also deactivate treesitter or just use it opt-in for specific filetypes, see `:h telescope.defaults.preview`, which probably seems to be the best solution. Should be comparable with any regex-based syntax highlighting solution.

**Comment by augustocdias** [comment] 2021-12-14 14:41
The highlighting is not a dealbreaker for me as it is very rare that I stumble across a file type not supported by treesitter. 

The timeout though can be annoying. I haven't experienced it since I re-enabled the default previewers, so probably it was improved. I've tried only when I installed the first time and it was very frequent, that's why I opted then for the deprecated ones.

Anyway. If you're going to drop it, you can just close this issue since it doesn't make sense to invest time to fix something you're gonna delete in the near future.

**Comment by fdschmidt93** [comment] 2021-12-14 16:26
> The timeout though can be annoying.

I fully understand. That's why I want to make sure you have the best experience with the canonical previewers. 

I have not done any benchmarking but I wouldn't expect vim regex syntax highlighting to trail bat etc significantly. Otherwise said, any hiccup in the previewers should likely be able to be fixed with fine grained configuration as referred to above. That's why I keep asking for more context; after all, tree-sitter hopefully becomes the de facto standard for neovim eventually :)

I'll close this for the time being, any other member should feel free to open this in case we want to in fact further support these previewers.

**Closed by fdschmidt93** 2021-12-14 16:26 UTC
Labels: bug

**Comment by bluz71** [comment] 2022-03-14 06:45
I have a custom git status implementation (based on #605) which uses [git-delta](https://github.com/dandavison/delta) under the covers.

I far prefer the visual flair of git-delta previewing vs the default Telescope implementation (which looks more like bog standard git status).

Anyway, ever since [7695d224](https://github.com/nvim-telescope/telescope.nvim/commit/7695d224c81e4ceeb3100d759c296814183ccfae), for #1480, my custom git status command is leaving me insert mode after I select a file. Basically this exact issue as described in the first post.

Is there any solution for this issue? Being left in insert mode is a major pain.

For reference my custom Telescope git status is:

```lua
M.git_status = function(opts)
  opts = opts or {}
  opts.previewer = previewers.new_termopen_previewer({
    get_command = function(entry)
      if entry.status == "D " then
        return { "git", "show", "HEAD:" .. entry.value }
      elseif entry.status == "??" then
        return { "bat", "--style=plain", entry.value }
      end
      return {
        "git", "-c", "core.pager=delta", "-c", "delta.pager=less -R", "diff", entry.value,
      }
    end,
  })

  -- Use icons that resemble the `git status` command line.
  opts.git_icons = {
    added = "A",
    changed = "M",
    copied = "C",
    deleted = "-",
    renamed = "R",
    unmerged = "U",
    untracked = "?",
  }

  builtin.git_status(opts)
end
```

Is there anyway I can stop being left in insert mode (like before #1480)?

**Comment by augustocdias** [comment] 2022-06-24 06:58
hi
I don't know if this is related to my previous issue, after closing a picker with Telescope in insert mode it is leaving the focused buffer in insert instead of normal mode... (I'm pretty much using Telescope defaults right now)
I tried creating a minimal config to reproduce the issue, but it doesn't happen... Is there a way to debug or find why this is happening?
Perhaps you could point me to where it should be restoring the mode to normal so I can try to figure out why in my setup it is not happening

**Comment by opalmay** [comment] 2022-06-24 14:21
> hi I don't know if this is related to my previous issue, after closing a picker with Telescope in insert mode it is leaving the focused buffer in insert instead of normal mode... (I'm pretty much using Telescope defaults right now) I tried creating a minimal config to reproduce the issue, but it doesn't happen... Is there a way to debug or find why this is happening? Perhaps you could point me to where it should be restoring the mode to normal so I can try to figure out why in my setup it is not happening

I have the same thing after upgrading from Neovim 0.7 to master - and after playing around with my config I've found that it's related to nvim-cmp and I can reproduce this with any mapping in its setup configuration. When commenting out that section the Telescope issue resolves.

**Comment by augustocdias** [comment] 2022-06-24 14:30
> > hi I don't know if this is related to my previous issue, after closing a picker with Telescope in insert mode it is leaving the focused buffer in insert instead of normal mode... (I'm pretty much using Telescope defaults right now) I tried creating a minimal config to reproduce the issue, but it doesn't happen... Is there a way to debug or find why this is happening? Perhaps you could point me to where it should be restoring the mode to normal so I can try to figure out why in my setup it is not happening
> 
> 
> 
> I have the same thing after upgrading from Neovim 0.7 to master - and after playing around with my config I've found that it's related to nvim-cmp and I can reproduce this with any mapping in its setup configuration. When commenting out that section the Telescope issue resolves.

I'll try that (again) later. I've tried disabling and enabling many plugins in my config and it still happened with cmp not setup

**Comment by augustocdias** [comment] 2022-06-27 07:53
@opalmay on mine it is not cmp... I tried disabling it and I'm having the same issue. 

I'm also on neovim master... I haven't tried with stable to see if it was the issue yet.

**Comment by augustocdias** [comment] 2022-06-29 07:19
It seems to have been fixed in the latest commits

**Comment by Conni2461** [comment] 2022-06-30 12:04
Its funny because we haven't changed that in months. I think i fixed that issue in april. Feel free to open a new issue if it happens again

**Comment by opalmay** [comment] 2022-07-04 19:47
> It seems to have been fixed in the latest commits

Same here
