### ISSUE TITLE
Telescope issue + Plenary issue

### ISSUE THREAD

**Issue by bryant-the-coder** [nvim-telescope/telescope.nvim#1816] opened 2022-04-03 12:14 UTC
### Description

When you type the letter `t` / `x`, errors shows up

### Neovim version

```markdown
NVIM v0.7.0-dev+1385-g6786b6afa
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az320-889
```

### Operating system and version

Windows 10

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0 (rev af6b6c543b)
  - OK: fd: found fd 8.3.2

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `harpoon`
  - INFO: No healthcheck provided

## Telescope Extension: `themes`
  - INFO: No healthcheck provided
```

### Steps to reproduce

1. `nvim`
2. `:Telescope find_files`
3. Type the letter `t` / `x`
4. Error shows up

### Expected behavior

This should works smoothly and perfectly. 

### Actual behavior

![image](https://user-images.githubusercontent.com/92417638/161427219-426ca3c5-9d9e-42cd-a733-e01659d885c5.png)
This error occurs after a few commits in plenary

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by bryant-the-coder** [comment] 2022-04-03 12:18
I can confirm after testing a few commits from plenary.lua. the commit that doesnt gives this erorr is `0d660152000a40d52158c155625865da2aa7aa1b`

**Comment by Conni2461** [comment] 2022-04-03 12:49
I can't reproduce your issue. I currently pushed another fix to plenary thought because modeline detection was borked after recent changes https://github.com/nvim-lua/plenary.nvim/commit/cbaeb9fffc14e7e5687715987a94b4f410084560

Can you share the output of `lua print(require("plenary.filetype").detect_from_modeline("doc/telescope.txt"))` if you are in telescope root

**Comment by bryant-the-coder** [comment] 2022-04-03 13:23
telescope root as in the telescope config? or the place where packer install stuff?

**Comment by bryant-the-coder** [comment] 2022-04-03 13:32
> 

only `help`

**Comment by Conni2461** [comment] 2022-04-03 16:59
I dont get in which invalid argument we run into.

Could you apply this patch and reproduce the issue. It should print the filepath it on which it tries to detect the filetype and errors. You can view old messages with `:mes`

```diff
diff --git a/lua/telescope/previewers/buffer_previewer.lua b/lua/telescope/previewers/buffer_previewer.lua
index 0ba9322..9f21912 100644
--- a/lua/telescope/previewers/buffer_previewer.lua
+++ b/lua/telescope/previewers/buffer_previewer.lua
@@ -160,6 +160,7 @@ previewers.file_maker = function(filepath, bufnr, opts)
   if opts.use_ft_detect == nil then
     opts.use_ft_detect = true
   end
+  print(filepath)
   opts.ft = opts.use_ft_detect and pfiletype.detect(filepath)
   if opts.bufname ~= filepath then
     if not vim.in_fast_event() then
```

**Comment by bryant-the-coder** [comment] 2022-04-03 21:31
![image](https://user-images.githubusercontent.com/92417638/161449437-244ec724-6a7f-405b-93bf-42c77955ddfc.png)
i have added into buffer_previewer.lua

this happens only in my config file. I dont really know what is triggering this issue :P

**Comment by biffhuxtable** [comment] 2022-04-06 17:25
> Another bug report was opened here: [nvim-lua/plenary.nvim#344](https://github.com/nvim-lua/plenary.nvim/issues/344)
> 
> I had an idea. Could you try [nvim-lua/plenary.nvim#345](https://github.com/nvim-lua/plenary.nvim/pull/345)

I was having the same issue and this seems to have fixed it.

**Comment by Conni2461** [comment] 2022-04-07 06:01
fixed by https://github.com/nvim-lua/plenary.nvim/commit/470d0e84ae275a367892e277df770233ec477f46

**Closed by Conni2461** 2022-04-07 06:01 UTC
Labels: bug
