### ISSUE TITLE
Use lua + treesitter for preview & syntax hl

### ISSUE THREAD

**Issue by koopa1338** [nvim-telescope/telescope.nvim#206] opened 2020-10-29 22:05 UTC
Bat is a fast and solid solution for now, but I think it would be an enhancement to use neovim itself for the preview of files. As treesitter is already a dependency, it feels right to use it for syntax highlighting in previews:
- no need for a bat theme
- consistent syntax highlighting overall
- reduce the dependency of external tool, that is not installed per default on most machines
    - also less friction if something breaks in bat (very unlikely though)

I've played with the preview function myself a little and the most critical thing to make this work is performance. 

Bat is amazingly fast and I couldn't get a version to work that is on par with the bat preview (must admit, that I don't totally understand how the previewers work and I would not call me a lua expert) but I think a discussion about this idea might be worth nontheless.

**Comment by tjdevries** [comment] 2020-11-02 22:27
Yeah -- if we could add an option / way of viewing a file in nvim that did literally NOTHING but load tree sitter for the filetype, then we could do this.

The problem is there are too many other autocmds and things that happen when you load a buffer.

Perhaps @bfredl or @vigoux have some ideas about how we could do something like this. I would really like it  as well.

**Comment by bfredl** [comment] 2020-11-02 22:35
You should be able to `bufload()` without filetype and then only load the highlighter.

**Comment by lanox** [comment] 2020-11-17 05:52
This would be amazing,  Bat, seems to not work so well on mac and I never seem to get it to work correctly, I think I spoke to you on stream @tjdevries

**Comment by Conni2461** [comment] 2020-11-17 07:38
Hey guys, the new `tags` builtin uses a vim buffer for previewing. So treesitter works in the preview for me.
Would be great if you could test it and report back, maybe i find time to port the other previewers aswell.

**Comment by vigoux** [comment] 2020-11-17 07:49
What is this `tags` feature you are talking about ?

**Comment by Conni2461** [comment] 2020-11-17 07:51
Same as in fzf. Reads tag file (created with `ctags -R`).

**Comment by elianiva** [comment] 2020-11-28 01:50
Just tested the `tags` feature and treesitter works great! No flicker / lag, tested it on neovim source code. Would love to see this get implemented for other features like `find_files`

**Comment by Conni2461** [comment] 2020-12-05 16:15
Hey everyone who is waiting for this.

I have a working PR #298 for this. Currently you have to turn it on by option and I think it will stay that way for a while. So even after it was merged.
```lua
require('telescope').setup {
  defaults = {
    vim_buffers_everywhere = true, -- Will most likely be renamed to something more useful
  }
}
```

It works pretty well and it might even be a bit faster than `bat`. Highlighting is treesitter if a parser exists or regex if not.
It would be very helpful if some people could try it out and provide some feedback either in the PR thread or telescope gitter. Thanks

**Comment by lanox** [comment] 2020-12-07 00:05
This is what I have in my telescope.lua file but I am not getting any syntaxh hl

```
require('telescope').setup {
  defaults = {
    layout_strategy = "horizontal",
    preview_cutoff = 120,
    sorting_strategy = "descending",
    prompt_position = "bottom",
    vim_buffers_everywhere = true,
    file_sorter = require('telescope.sorters').get_fzy_sorter
  }
}
```

![Screen Shot 2020-12-07 at 11 03 27 am](https://user-images.githubusercontent.com/7599183/101297200-dcb64e00-387b-11eb-9bd2-24d0946bc75c.png)

I also have this weird issue where I lose the colour of icons when I navigate up or down as you can see in the image.
Thanks

**Comment by Conni2461** [comment] 2020-12-07 08:11
@lanox 
Your screenshot clearly indicated that you are using less with that `filepath (END)`. You currently have to checkout the mentioned PR in order to test it. It has not been merged yet.
1. `git fetch origin pull/298/head:pr-298`
2. `git checkout pr-298`

> I also have this weird issue where I lose the colour of icons when I navigate up or down

This bug is tracked here https://github.com/nvim-telescope/telescope.nvim/issues/233

**Comment by lanox** [comment] 2020-12-07 10:04
Well that is quite embarrassing.

**Comment by yujinyuz** [comment] 2020-12-09 09:34
@Conni2461 wow I didn't know that the builtin `tags` use treesitter.

I'll try this out when I get the time. Is it almost done?

**Closed** 2020-12-09 15:58 UTC
