### ISSUE TITLE
builtin.git_commits fails for paths with spaces (windows 10)

### ISSUE THREAD

**Issue by JSchrtke** [nvim-telescope/telescope.nvim#533] opened 2021-02-15 15:37 UTC
### Description
When invoking the builtin.git_commits function within a directory containing spaces in it's path, the following error is returned:

    E5108: Error executing lua ...vim\plugged\telescope.nvim\lua\telescope\builtin\git.lua:145: C:\Users\js\Desktop\path with spaces\telescope.nvim is not a git directory

**Expected Behavior**
No errors, git commits are displayed

**Actual Behavior**
An error is returned

    E5108: Error executing lua ...vim\plugged\telescope.nvim\lua\telescope\builtin\git.lua:145: C:\Users\js\Desktop\path with spaces\telescope.nvim is not a git directory

### Details

<details><summary>Reproduce</summary>

1. `mkdir "path with spaces"`
2. `cd "path\ with\ spaces"`
3. clone some git repo
    `git clone https://github.com/nvim-telescope/telescope.nvim.git`
4. `nvim`
NOTE: I used your configuration here, just as my actual init.vim insteadt of some test.vim, since the provided template doesn't work on windows.
5. `:lua require('telescope.builtin').git_commits`
This causes the error to be returned
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.5.0-dev+1083-g1aec5ba85
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD
/Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MS
GPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -IC:/projects/nvim-deps/usr/inc
lude -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-333

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```
- Operating system:
`Windows 10 Pro
Version 2004
Build 19041.804`

- Telescope commit: 1c5e42a

</details>

<details><summary>Configuration</summary>
<p>

```viml
call plug#begin('~/.vim/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '├ö├Â├ç', '├ö├Â├®', '├ö├Â├ç', '├ö├Â├®', '├ö├▓┬í', '├ö├▓┬½', '├ö├▓┬╗', '├ö├▓Ôûæ'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by elianiva** [comment] 2021-02-15 18:02
This also happens on Linux (and possibly Mac as well) because we didn't escape the CWD. Adding `vim.fn.fnamescape` fixed it but I'm not sure if it's the best solution.

```diff
diff --git a/lua/telescope/builtin/git.lua b/lua/telescope/builtin/git.lua
index a9dbfab..905c514 100644
--- a/lua/telescope/builtin/git.lua
+++ b/lua/telescope/builtin/git.lua
@@ -135,7 +135,7 @@ local set_opts_cwd = function(opts)
   if opts.cwd then
     opts.cwd = vim.fn.expand(opts.cwd)
   else
-    opts.cwd = vim.loop.cwd()
+    opts.cwd = vim.fn.fnameescape(vim.loop.cwd())
   end
```

**Comment by JSchrtke** [comment] 2021-02-15 18:11
> Adding vim.fn.fnamescape fixed it but I'm not sure if it's the best solution.

Cool, thanks, I'll use that as a fix in the meantime

**Comment by Conni2461** [comment] 2021-02-15 18:15
@anott03 do you wanna handle this in your PR? We maybe have more instances where this might happen.

**Comment by anott03** [comment] 2021-02-15 18:44
@Conni2461 I probably can do that, but I don't think `plenary.path` escapes whitespace right now.

**Comment by Conni2461** [comment] 2021-02-15 18:47
Good point: feel free to submit another PR :laughing: with a fix for it and some test :)

**Comment by anott03** [comment] 2021-02-15 18:48
👍 I'll work on adding escaping to plenary right now, and then make the necessary changes to my PR here once that's done.

**Comment by anott03** [comment] 2021-02-15 18:56
Aside from using `fnameescape`  are there better ways to escape the path (for example I don't see anything in `vim.loop`)?

**Comment by elianiva** [comment] 2021-02-15 18:59
maybe we should just replace the special chars manually? That's the best solution I could think of to avoid `vim.fn`

**Comment by anott03** [comment] 2021-02-15 19:02
We only need to escape spaces and the the separator correct? Also can someone remind me what the windows escape character is :)

**Comment by JSchrtke** [comment] 2021-02-15 19:06
In Windows cmd, you can either use `^` before a space, or put the whole thing in double quotes. PowerShell only accepts double quotes.

**Comment by elianiva** [comment] 2021-02-15 19:06
also, we need to escape `$` (and yes, this is a weird name for a file) because it conflicts with the variable keyword in bash/zsh/etc

**Comment by anott03** [comment] 2021-02-15 19:11
Ok that shouldn't be difficult to do manually, I can just use `gsub`. For windows do I make it insert double quotes? That doesn't feel quite right (sorry I haven't done much with windows).

**Comment by JSchrtke** [comment] 2021-02-15 19:17
Because Windows is silly, it depends. AFAIK, wrapping the entire path in double quotes should do the trick for either shell on windows. 
However, depending on the shell, either cmd or powershell, the escape chars are either `^` for cmd, or ``` (yes, the backtick, I don't know how to escape that in markdown) for powershell.

**Comment by Conni2461** [comment] 2021-02-15 19:35
We can't do `" "` because we will end up using `cwd` for `uv.spawn`. I think `\ ` might actually work. But we need to check.

I was working on a windows pipeline that is pretty close to being done. I will try to finish that tomorrow. That will make things a little bit easier for plenary and telescope.

https://github.com/Conni2461/telescope.nvim/actions/runs/567943880 it currently just can't find the `PlenaryBustedDirectory` command so should be fixable :laughing:

**Comment by anott03** [comment] 2021-02-15 23:20
This is what I've come up with so far... it of course becomes much simpler if we can do the same substitutions on windows as well, then we shouldn't need the factory function at all.

```lua
local _escape = (function()
  if jit then
    if string.lower(jit.os) == 'linux' or string.lower(jit.os) == 'osx' then
      return function(path)
        local escaped_path = path
        escaped_path = string.gsub(escaped_path, " ", "\\ ")
        escaped_path = string.gsub(escaped_path, "%$", "\\$")
        return escaped_path
      end
    else
      return function(path)
        local escaped_path = path
        -- windows substitutions here
        return escaped_path
      end
    end
  else
    return function(path)
      local escaped_path = path
      escaped_path = string.gsub(escaped_path, " ", "\\ ")
      escaped_path = string.gsub(escaped_path, "%$", "\\$")
      return escaped_path
    end
  end
end)()

function Path:escape()
  return _escape(self.filename)
end
```

**Comment by elianiva** [comment] 2021-02-16 00:37
you could use table in gsub to replace multiple matches at once so it'll look cleaner

**Comment by Conni2461** [comment] 2021-02-16 08:31
You don't need `jit` here :)
```lua
if path.sep == '\\' then
  -- windows
else
  -- unix
end
```
I would still do a generator function so :+1: for that. You can also updated `is_absolute` to a generator function, i forgot that :rofl:

**Comment by anott03** [comment] 2021-02-20 17:56
I'm not going to do `is_absolute` in the PR I'm working on now - I'll leave that for another time :) This one is going to be just  the `escape` function and maybe a few other related changes.

**Comment by Conni2461** [comment] 2021-12-10 15:52
I can no longer reproduce this, so i am closing this issue. Feel free to reopen if you can reproduce :)

**Closed by Conni2461** 2021-12-10 15:52 UTC
Labels: bug

**Comment by JSchrtke** [comment] 2021-12-11 12:45
Nope, all good so far. Thanks!
