### ISSUE TITLE
errors when using current buffer fuzzy find

### ISSUE THREAD

**Issue by Mechap** [nvim-telescope/telescope.nvim#795] opened 2021-04-23 22:18 UTC
I'm getting errors when I want to  open the current buffer fuzzy find.
![image](https://user-images.githubusercontent.com/54742369/115934967-7af52a00-a492-11eb-840d-01e1c4e49c9d.png)

**Comment by EthanJWright** [comment] 2021-04-24 03:11
Same error here, I'm on Ubuntu 20.04, 0.5 Neovim, and using Kitty.

**Comment by thenewvu** [comment] 2021-04-24 06:26
Not the same error, but I got another error when opening the current buffer fuzzy find:

![Screen Shot 2021-04-24 at 13 23 38](https://user-images.githubusercontent.com/6092585/115949623-8f700b80-a500-11eb-9fec-a75d5f8f0cc9.png)

I believe this commit causes the error: https://github.com/nvim-telescope/telescope.nvim/commit/0b2c801978e9cfc9b6351fc9f037ff2ba93805bd

**Comment by dhruvmanila** [comment] 2021-04-24 12:38
I got the same error as @thenewvu got. 
```
E5108: Error executing lua ...ker/start/telescope.nvim/lua/telescope/builtin/files.lua:387: attempt to index local 'query' (a nil value)
```

It's because telescope uses `filetype` to get the treesitter query and the function expects the language name. In my case I was opening the current buffer fuzzy find for a bash file and the filetype for that is `sh` but the language name in treesitter is `bash` so we get a `nil` value and thus the error.

**Comment by marcelbeumer** [comment] 2021-04-25 09:10
Can confirm what @dhruvmanila describes. Have the same issue with a `typescriptreact` file

**Comment by Conni2461** [comment] 2021-04-26 11:44
There is a `ft_to_lang` in `nvim-treesitter.parsers`. Someone can add that (don't forget the pcall).

But i am not sure if people report different issues here. would be good if op could have filled out the bug template (next time)

**Comment by Mechap** [comment] 2021-04-28 09:02
I updated neovim and everything works so far now

**Comment by Conni2461** [comment] 2021-04-28 18:07
Does anyone here still have issues? Otherwise i will close this issue.

**Comment by EthanJWright** [comment] 2021-04-28 18:11
I'm still getting the error:

```
Error executing vim.schedule lua callback: ...gged/telescope.nvim/lua/telescope/pickers/highlights.lua:32: Expected lua string                                                                                                                                                                                 
Error executing vim.schedule lua callback: ...gged/telescope.nvim/lua/telescope/pickers/highlights.lua:32: Expected lua string
```

When calling `:Telescope current_buffer_fuzzy_find` on a python file -- I can open up a bug ticket with the proper template if you like.

**Comment by Conni2461** [comment] 2021-04-28 18:13
Are you using `treesitter` for python? And your `nvim --version` output would be good

**Comment by EthanJWright** [comment] 2021-04-28 18:31
Ah yep I missed that the fix was a neovim update, I just did a plugin update -- all is working on the latest nightly release! Apologies

**Closed** 2021-04-28 18:52 UTC
Labels: Missing bug template, bug

**Comment by tombh** [comment] 2021-08-22 14:58
This exact error has recently started happening to me in `.sh` files. I could try to make a minimal config to reproduce it if necessary.

`NVIM v0.6.0-dev+166-g8331cd13c`

**Comment by dhruvmanila** [comment] 2021-08-22 17:15
> I could try to make a minimal config to reproduce it if necessary.

That would be quite helpful. You can open a new issue with the necessary details. If possible, you can perform a `git bisect` to find out which commit created it.

**Comment by tombh** [comment] 2021-09-14 02:53
I assume an update must have fixed it, but I don't see the error anymore

**Comment by dhruvmanila** [comment] 2021-09-14 07:48
Yeah, look at the last mentioned issue on the thread.

**Comment by tombh** [comment] 2021-09-14 13:00
Oh yes! Thank you so much ♥️
