### ISSUE TITLE
with git_status doesn't works reverse_directories 

### ISSUE THREAD

**Issue by Wordluc** [nvim-telescope/telescope.nvim#3230] opened 2024-07-29 16:51 UTC
### Description

				path_display = {
					filename_first = {
						reverse_directories = true
					}
				},
![image](https://github.com/user-attachments/assets/18519e2d-a68a-4b7f-a8d2-a88674d18311)

### Neovim version

```markdown
NVIM v0.11.0-dev-381+gfb6c059dc
Build type: RelWithDebInfo
LuaJIT 2.1.1720049189
```

### Operating system and version

Windows 11

### Telescope version / branch / rev

master

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 14.1.0 (rev e50df40a19)
- WARNING fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

===== Installed extensions ===== ~
```

### Steps to reproduce

set reverse_directories  and then use vim.keymap.set('n', '<leader>fg', builtin.git_status, {})

### Expected behavior
path from: filename to C:

![image](https://github.com/user-attachments/assets/3594dba6-c57a-4cf1-90f3-486ebedd4736)

### Actual behavior
Shows path in incorrect order, from C:   to filename

![image](https://github.com/user-attachments/assets/8deb9dbb-e3af-40af-b7b4-233e55e0cc6a)

### Minimal config

```Lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs { "config", "data", "state", "cache" } do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.uv.fs_stat(lazypath) then
  vim.fn.system {
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  }
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
    },
    config = function()
      -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
      require("telescope").setup {}
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

**Comment by jamestrew** [comment] 2024-08-13 02:35
I'm going to close this as it's a duplicate of https://github.com/nvim-telescope/telescope.nvim/issues/3181

**Closed by jamestrew** 2024-08-13 02:35 UTC
Labels: bug, Windows
