### ISSUE TITLE
Live grep shows every file twice

### ISSUE THREAD

**Issue by Morantxu** [nvim-telescope/telescope.nvim#553] opened 2021-02-25 09:05 UTC
### Description

When I search for a word in live grep, every file is show twice in the results.

**Expected Behavior**

Normally, it should only show it once

**Actual Behavior**

Every result is shown twice

### Details

<details><summary>Reproduce</summary>

1. nvim -nu test.vim
2. live_grep
3. Results are still shown twice
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+1109-g6b7cc45c4
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -W
conversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_H
AS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovi
m/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az90-547

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

- Operating system: Arch Linux x86_64, 5.10.16-arch1-1 
- Telescope commit: d3a9c78

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua << EOF

require('telescope').setup{
  defaults = {
    vimgrep_arguments = {
      'rg',
      '--color=never',
      '--no-heading',
      '--with-filename',
      '--line-number',
      '--column',
      '--smart-case'
    },
    prompt_position = "bottom",
    prompt_prefix = ">",
    selection_strategy = "reset",
    sorting_strategy = "descending",
    layout_strategy = "horizontal",
    layout_defaults = {},
    file_ignore_patterns = {},
    shorten_path = true,
    winblend = 0,
    width = 0.75,
    preview_cutoff = 120,
    results_height = 1,
    results_width = 0.8,
    border = {},
    borderchars = { '─', '│', '─', '│', '╭', '╮', '╯', '╰'},
    color_devicons = true,
    use_less = true,
  }
}
EOF
```

**Comment by elianiva** [comment] 2021-02-26 12:34
could you provide a screenshot or a screencast? I couldn't reproduce it and not entirely sure what you mean by `every file is shown twice`, isn't it normal though? You could have multiple results from a single file so it's possible to show up multiple times.

**Comment by saurabh-kushwah** [comment] 2021-03-07 07:21
Check this screenshot https://imgur.com/OwwynIF  Duplicate Elements for treesitter.

**Comment by Morantxu** [comment] 2021-03-07 23:05
This is an example :
![image](https://user-images.githubusercontent.com/71721545/110258257-fb72d080-7fa1-11eb-8372-fdecfa0cb3dd.png)

**Comment by Conni2461** [comment] 2021-03-08 09:02
It seems like you have duplicated files in `tar` directory, so ripgrep will catch them, obviously :laughing: 
You can put this `tar` directory in `.gitignore` (ripgrep will not show ignored files) or you can telescope to ignore this directory:

```lua
require('telescope').setup {
  defaults = {
    file_ignore_patterns = { 'tar/' },
  }
}
```

**Comment by saurabh-kushwah** [comment] 2021-03-29 04:11
The find and grep works correctly but the duplicate enteries are found for treesitter. 
![Screenshot from 2021-03-29 09-32-44](https://user-images.githubusercontent.com/72739196/112786006-ee15a700-9072-11eb-943e-61820cc18b69.png)

**Comment by elianiva** [comment] 2021-03-29 08:33
> The find and grep works correctly but the duplicate enteries are found for treesitter.

That is, ..weird. I don't have this issue :/ 

![image](https://user-images.githubusercontent.com/51877647/112809205-f76b3780-90a3-11eb-86c6-fd7a4207678d.png)

**Comment by saurabh-kushwah** [comment] 2021-03-29 08:51
My Treesitter config 
I tried with default but still same result

```lua
require'nvim-treesitter.configs'.setup {
  ensure_installed = { "go" , "java", "javascript", "lua" },
  highlight = {
    enable = true,
  },
}

```

**Comment by saurabh-kushwah** [comment] 2021-04-01 05:17
There were some changes in treesitter plugin so I did a clean install and it worked.

https://github.com/nvim-treesitter/nvim-treesitter/issues/994

**Comment by Conni2461** [comment] 2021-04-03 13:07
I think i can close this issue. We are only displaying the results of `rg`, so if you have files duplicated in your project root these will be shown twice

**Closed by Conni2461** 2021-04-03 13:07 UTC
Labels: bug
