### ISSUE TITLE
Empty entry in `git_bcommits`

### ISSUE THREAD

**Issue by fjchen7** [nvim-telescope/telescope.nvim#2350] opened 2023-01-28 16:04 UTC
### Description

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/10106636/215276163-2a6c1546-c319-4a58-9417-92dbfb066ef7.png">

The `...` is empty entry.

### Neovim version

```markdown
NVIM v0.9.0-dev-781+gda671b21c-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by fjchen@whatsthis.local
```

### Operating system and version

macOS 12.1

### Telescope version / branch / rev

master / dce1156

### checkhealth telescope

```markdown
==============================================================================
telescope: require("telescope.health").check()

Checking for required plugins ~
- OK plenary installed.
- OK nvim-treesitter installed.

Checking external dependencies ~
- OK rg: found ripgrep 13.0.0
- OK fd: found fd 8.6.0

===== Installed extensions ===== ~

Telescope Extension: `frecency` ~
- OK sql.nvim installed.
- OK nvim-web-devicons installed.

Telescope Extension: `fzf` ~
- OK lib working as expected
- OK file_sorter correctly configured
- OK generic_sorter correctly configured

Telescope Extension: `possession` ~
- No healthcheck provided

Telescope Extension: `project` ~
- No healthcheck provided

Telescope Extension: `yank_history` ~
- No healthcheck provided
```

### Steps to reproduce

execute `Telescope git_bcommits`

### Actual behavior

Entry `...` won't appear.

### Minimal config

```Lua

{  -- lazy.nvim
  "nvim-telescope/telescope.nvim",
  opts = {}
}
```

**Comment by kkharji** [comment] 2023-01-28 16:10
Thanks for reporting @fjchen7,

caused by #2288, too many complaints so far (e.g. @petobens @SebTalbot).  

@CyanJoeng are you welling to introduce a fix? if not a revert commit will be auto merged.

**Closed** 2023-01-31 07:24 UTC
Labels: bug
