### ISSUE TITLE
PageUp and PageDown bindings

### ISSUE THREAD

**Issue by wookayin** [nvim-telescope/telescope.nvim#1430] opened 2021-11-09 01:04 UTC
**Is your feature request related to a problem? Please describe.**

Please add PageUp / PageDown actions that would scroll the result window (not the preview window).

**Describe the solution you'd like**

I think the above sentence is self-descriptive. That would be useful to page and scroll through big results (e.g., grep or rg). PageUp/PageDown (similar to Ctrl-U/Ctrl-D/Ctrl-B/Ctrl-F in vim) should work by default, or through a customizable keybindings.

Note that, fzf supports this by default.

**Comment by fdschmidt93** [comment] 2021-11-09 08:38
Please carefully read our documentation. See the [default mappings](https://github.com/nvim-telescope/telescope.nvim#default-mappings), the first two in the list of which implement your desired feature.

The setup structure [here](https://github.com/nvim-telescope/telescope.nvim#telescope-setup-structure) indicates how to change mappings. For more, see `:h telescope.defaults.mappings` best accessed via `:Telescope help_tags` ;)

**Comment by Conni2461** [comment] 2021-11-09 09:23
Thats not what was asked here. Its about scrolling a "page" of results. Not about moving to the next/prev value

**Comment by l-kershaw** [comment] 2021-11-09 11:00
I think this is a dupe of #1326.
There is a custom setup mentioned there that implements this sort of thing.

Since this wasn't a mapping that I thought (at the time) that many people would use, I didn't think it was worth adding an action for it.
But since this has been requested twice now, maybe we should add it?
@Conni2461 @fdschmidt93 thoughts?

**Comment by fdschmidt93** [comment] 2021-11-09 11:17
Agreed, we should probably have these then as built in actions if they work well. We can then also follow `fzf` and have these mapped to `"<PageUp>"` and `"<PageDown>" which work seamlessly out-of-the-box, which just tested with:

```lua
telescope.setup {
...
    mappings = {
      i = {
        ["<PageUp>"] = actions.move_selection_next,
        ["<PageDown>"] = actions.move_selection_previous,
...
}
```

**Comment by l-kershaw** [comment] 2021-11-09 11:42
Okay, I'll write up a PR for this tonight 👍

**Comment by wookayin** [comment] 2021-11-09 17:33
I appreciate all the maintainers for your comments and implementing the feature. Let me leave some comment/feedback in the PR #1436.

**Closed** 2021-11-13 11:15 UTC
Labels: enhancement

**Comment by wookayin** [comment] 2021-11-14 19:10
Thank you so much for implementing the feature in #1436, the feature somehow works, the behavior is quite strange and different from typical <PgUp>, <PgDown>. For example, <PgDown> should not scroll over the end of result like you said "looks like it is alternating between the top and the middle of the results window."  could this be improved?

**Comment by AndreiCalazans** [comment] 2022-06-18 21:30
> Thank you so much for implementing the feature in #1436, the feature somehow works, the behavior is quite strange and different from typical , . For example, should not scroll over the end of result like you said "looks like it is alternating between the top and the middle of the results window." could this be improved? Also it is different from FZF (but would be more similar to what vim's `<C-u><C-d>`), as fzf first heads down to the last item of the current page when pressing `PgDn` (or to the topmost item when `PgUp`) and then scroll to the next/previous page after next keypress. Users could add their own behavior instead though.


Not sure if there is a better way to replicate Vim's `<C-u><C-d` movements but here is how I did it:

```lua
local telescope = require('telescope')
local actions = require('telescope.actions')
local layout = require('telescope.actions.layout')
local moveUp = 
	actions.move_selection_previous
	+ actions.move_selection_previous
	+ actions.move_selection_previous
	+ actions.move_selection_previous

local moveDown = 
	actions.move_selection_next
	+ actions.move_selection_next
	+ actions.move_selection_next
	+ actions.move_selection_next


telescope.setup{
	defaults = {
		mappings = {
			i = {
				["<C-o>"] = actions.send_selected_to_qflist + actions.open_qflist,
				["<C-p>"] = layout.toggle_preview,
				["<C-j>"] = actions.move_selection_next,
				["<C-k>"] = actions.move_selection_previous,
				["<C-u>"] = moveUp,
				["<C-d>"] = moveDown,
				["<C-a>"] = actions.toggle_all,
			 },
			n = {
				["<C-o>"] = actions.send_selected_to_qflist + actions.open_qflist,
				["<C-p>"] = layout.toggle_preview,
				["<C-j>"] = actions.move_selection_next,
				["<C-k>"] = actions.move_selection_previous,
				["<C-u>"] = moveUp,
				["<C-d>"] = moveDown,
				["<C-a>"] = actions.toggle_all,
			 }
		}
	}
}

```
