### ISSUE TITLE
Search bar reverses characters

### ISSUE THREAD

**Issue by cmoscofian** [nvim-telescope/telescope.nvim#1620] opened 2021-12-22 14:55 UTC
### Description

On any builtin picker, whenever I switch from `normal mode` to `insert mode` using `I`. It reverses the characters as I type them. 
So as I type `telescope` it shows it as `epocslete`.

![telescope](https://user-images.githubusercontent.com/59028844/147111065-3d04971a-912c-4209-a458-86c3bffc0dea.gif)

### Neovim version

```markdown
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
```

### Operating system and version

macOS 11.6.1

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====
```

### Steps to reproduce

1. Enter neovim `nvim`
2. Open any telescope picker: `:Telescope find_files<cr>` or `:Telescope git_files<cr>`
3. Type anything and go into normal mode `<esc>`
4. Move back into insert mode using `I` then type anything.

### Expected behavior

Append characters to the right as I type then when in insert mode.

### Actual behavior

It is adding characters to the left of the cursor as I type them.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment] 2021-12-22 16:21
This is a funny bug :sweat_smile: So I can reproduce this with the `0.6` appimage but not on latest neovim-`master`. I suspect it was fixed with one of the prompt buffer PRs that got rather recently merged.

Not sure whether we can do anything from within telescope here I'm afraid.

**Comment by cmoscofian** [comment] 2021-12-22 17:30
Makes sense. I'm just going to bump neovim then.
As far as I could tell it was fixed here: https://github.com/neovim/neovim/pull/16421. So build it from any later commit must fix it.

**Comment by Conni2461** [comment] 2022-01-08 21:49
Closing because the upstream bug is already fixed.

**Closed** 2022-01-08 21:49 UTC
Labels: bug, upstream
