### ISSUE TITLE
Failed to run healthcheck for "telescope" plugin. Exception:  module 'vim.health' not found:

### ISSUE THREAD

**Issue by zavodnyuk** [nvim-telescope/telescope.nvim#2578] opened 2023-06-18 09:54 UTC
### Description

Checkhealth seems to fail on new config

### Neovim version

```markdown
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
```

### Operating system and version

Ubuntu 20.04.6 LTS

### Telescope version / branch / rev

telescop 0.1.2

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
  - ERROR: Failed to run healthcheck for "telescope" plugin. Exception:
    function health#check[21]..health#telescope#check, line 1
    Vim(lua):E5108: Error executing lua vim/_init_packages.lua:0: module 'vim.health' not found:
    no field package.preload['vim.health']
    no file './vim/health.lua'
    no file '/__w/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/vim/health.lua'
    no file '/usr/local/share/lua/5.1/vim/health.lua'
    no file '/usr/local/share/lua/5.1/vim/health/init.lua'
    no file '/__w/neovim/neovim/.deps/usr/share/lua/5.1/vim/health.lua'
    no file '/__w/neovim/neovim/.deps/usr/share/lua/5.1/vim/health/init.lua'
    no file '/home/max/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/vim/health.lua'
    no file '/home/max/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/vim/health/init.lua'
    no file '/home/max/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/vim/health.lua'
    no file '/home/max/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/vim/health/init.lua'
    no file './vim/health.so'
    no file '/usr/local/lib/lua/5.1/vim/health.so'
    no file '/__w/neovim/neovim/.deps/usr/lib/lua/5.1/vim/health.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
    no file '/home/max/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/vim/health.so'
    no file './vim.so'
    no file '/usr/local/lib/lua/5.1/vim.so'
    no file '/__w/neovim/neovim/.deps/usr/lib/lua/5.1/vim.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
    no file '/home/max/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/vim.so'
    stack traceback:
    [C]: in function 'require'
    vim/_init_packages.lua: in function '__index'
    ...ack/packer/start/telescope.nvim/lua/telescope/health.lua:1: in main chunk
    [C]: in function 'require'
    [string ":lua"]:1: in main chunk
```

### Steps to reproduce

run nvim
checkhealth

### Actual behavior

I see ERROR when run checkhealth

### Minimal config

```Lua
`init.lua`

require("max")


`/lua/max/init.lua`
```lua
require("max.packer-plugins")
```

`packer-plugins.lua`

```lua
vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function(use)
	-- Packer can manage itself
	use 'wbthomason/packer.nvim'
	use {
		'nvim-telescope/telescope.nvim', tag = '0.1.2',
		-- or                            , branch = '0.1.x',
		requires = { {'nvim-lua/plenary.nvim'} }
	}
end)
```
```

**Comment by jamestrew** [comment] 2023-06-18 21:04
I'm not able to reproduce this.
From what I can gather, it looks like your neovim installation thinks that `vim.health` doesn't exist.
What happens if you do something like `:lua vim.print(vim.health)`?

**Comment by ronthl** [comment] 2023-06-21 14:02
I got this error when `:checkhealth telescope`
<img width="886" alt="Screenshot 2023-06-21 at 20 58 46-min" src="https://github.com/nvim-telescope/telescope.nvim/assets/105633986/1c2eed7c-6718-4d06-b8b5-8c22197f60fc">

And I cannot use `require('telescope').setup {}`, it shows the same error.

I'm using:
* NVIM v0.9.1
* Telescope: v0.1.2

And this is my nvim config: https://github.com/ronthl/dotfiles/tree/simplify-nvim/.config/nvim

**Comment by zavodnyuk** [comment] 2023-06-21 16:55
I've managed to fix this. Actually problem was in wrong nvim installation. When I upgraded nvim manually, I copied latest runtime folder to the wrong path, so binaries was correct and version was 0.9.1, but runtime files were used from previous version. So reinstalling nvim with proper copying to the correct party solved the issue.

**Comment by jamestrew** [comment] 2023-06-21 21:24
@ronthl looks like an telescope installation issue. we can keep discussing here but i'm going to close the issue.

**Closed by jamestrew** 2023-06-21 21:24 UTC
Labels: bug

**Comment by ronthl** [comment] 2023-06-22 01:32
Hi @zavodnyuk - I install nvim v0.9.1 from the source without upgraded. So I believe the path is correct. Thanks for your information 👍 

Hi @jamestrew - Ya. It could be. I install it from `lazy.nvim`, could you tell me what I can do for further investigation? 😄
