### ISSUE TITLE
`buffers` does not always respect `initial_mode`

### ISSUE THREAD

**Issue by ValdemarGr** [nvim-telescope/telescope.nvim#1198] opened 2021-09-02 10:13 UTC
### Description

After updating to the newest version of telescope (79c2ded6a8a4a1941f72d372532eebbb076c555c) I have had problems with the buffer module. Given the right circumstances, the `buffers` search module disregards `initial_mode` and  just begins in normal mode. Rolling back to 767e42f2e9595592ded51c69a0324a5dd811792d fixes the problem.

### Neovim version

NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5

### Operating system and version

5.12.13-arch1-2

### Steps to reproduce

The bug occurs (for me) when the terminal emulator buffer is the first buffer in the list of buffers.
![image](https://user-images.githubusercontent.com/22582195/131825598-2af91294-ced0-4e6d-b8e8-5e589de5c42d.png)

### Expected behavior

`buffers` respects `initial_mode`.

### Actual behavior

`buffers` begins in normal mode.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by fdschmidt93** [comment] 2021-09-02 10:42
Cannot reproduce, am I doing something wrong?


https://user-images.githubusercontent.com/39233597/131829792-f2c1fff8-0166-48db-954a-b2be4d309b8f.mp4


Are you starting `builtin.buffers` from terminal mode?

**Comment by ValdemarGr** [comment] 2021-09-02 11:24
> Cannot reproduce, am I doing something wrong? E: I also get the same results in `minimal_init.lua`.
> buffer-test.mp4
> 
> Just some guessing questions:
> 
>     * Are you starting `builtin.buffers` from terminal mode? (E: I can confirm there is something not working as intended here, should be insert mode but is in normal mode for me)
> 
>     * What lua/viml command do you use to start `builtin.buffers` with the `initial_mode`?

1: it doesn't matter where I am located when I invoke `buffers` the only prerequisite is that the terminal is the first entry (for that bug to occur).
2: `lua require('telescope.builtin').buffers()`

**Comment by fdschmidt93** [comment] 2021-09-02 11:29
I see you're experiencing this issue but I'm afraid I cannot reproduce this :( Do you have any idea what triggers `No alternate file` for you? My guess is that has something to do with it.

https://user-images.githubusercontent.com/39233597/131836041-6ec7a113-6180-455a-994b-4e503285e636.mp4

**Comment by fdschmidt93** [comment] 2021-09-02 11:54
Apologies, doing the best I can to repro this but I can't. I hope another member will test this as well and hopefully we can pinpoint the issue then.

**Comment by Conni2461** [comment] 2021-09-02 19:55
I cant reproduce with the minimal rc provided. I give you the benefit of the doubt that you actually tested it with minimal rc even thought the videos shows a different picture.

Can you confirm a hinch? Is this the first commit that introduces this issues? https://github.com/nvim-telescope/telescope.nvim/commit/79dc995f820150d5de880c08e814af327ff7e965

Your last working commit is kinda old, so its not helpful. So basically i am asking you to do a `git bisect` so we can find the commit that introduces this issue.

**Comment by ValdemarGr** [comment] 2021-09-03 15:43
I will get back to this later today, where I will provide a (hopefully) reproducible environment and repo along with a more precise commit such as 79dc995f820150d5de880c08e814af327ff7e965. Thank you.

**Comment by ValdemarGr** [comment] 2021-09-03 19:57
I created a reproducible example here: https://github.com/ValdemarGr/telescope-repro

You are definitely right that https://github.com/nvim-telescope/telescope.nvim/commit/79dc995f820150d5de880c08e814af327ff7e965 broke something. The commit after (https://github.com/nvim-telescope/telescope.nvim/commit/f45c170f2853c1c1492d3f30a950a99d30706ea2) removed the error message (see last clip).

Working on https://github.com/nvim-telescope/telescope.nvim/commit/03c2b8f6bb8027ecdf10acc6d803886c80f99037:

https://user-images.githubusercontent.com/22582195/132059150-8a6e2647-990d-4cad-b500-6fea586b86e8.mp4

Not working on https://github.com/nvim-telescope/telescope.nvim/commit/79dc995f820150d5de880c08e814af327ff7e965:

https://user-images.githubusercontent.com/22582195/132059362-a0fcbada-876f-4853-88c9-226d5ece3936.mp4

**Comment by fdschmidt93** [comment] 2021-09-06 07:18
`notworking.mp4` shows an unfortunate bug that slipped in because we have differing defaults; i.e. nothing that relates to your original issue.

Could you please re-test from #1155 ?

**Comment by ValdemarGr** [comment] 2021-09-06 11:45
> The commit after (f45c170) removed the error message (see last clip) such that the terminal instance is silently consumed on preview.
I think I was unclear. https://github.com/nvim-telescope/telescope.nvim/pull/1155 fixed the visible error, such that the terminal instance is silently consumed instead.

**Comment by fdschmidt93** [comment] 2021-09-06 15:34
Ok, long story short: the terminal instances being eaten seems to be nvim working as intended. I can reproduce this with docker image and `nvimbreaking` (having fixed the right commit to "f45c170f2853c1c1492d3f30a950a99d30706ea2").

The reason it happens in your docker image in `nvimbreaking` is because https://github.com/neovim/neovim/pull/15410 has only been very recently applied. Running `:set hidden` before  `:Telescope buffers` fixes this.

So why does `nvimworking` work? Because we used to load the contents of the buffers into temporary buffers. Now, for for `:Telescope buffers` (exclusively), we show the actual buffers, since we cannot otherwise show special buffers (like terminals) with true highlighting. 

See also: https://github.com/neovim/neovim/issues/11542

Now we only need a reproducible case for initial mode not being respect ;) And as I mentioned, starting `:Telescope buffers` from terminal mode is a bug. Anything else?

**Comment by ValdemarGr** [comment] 2021-09-07 12:29
I'll have time to look at this again in the weekend. Thank you for the thorough research :)

**Comment by cseickel** [comment] 2021-09-11 21:15
I just added the ability to switch between pickers and this has caused the issue intermittently. Every now and then I end up in normal mode instead of insert.

Here is my config:
`require('telescope').setup{                                                                                                                                                  
  defaults = {                                                                                                                                                               
    vimgrep_arguments = {                                                                                                                                                    
      'rg',                                                                                                                                                                  
      '--color=never',                                                                                                                                                       
      '--no-heading',                                                                                                                                                        
      '--with-filename',                                                                                                                                                     
      '--line-number',                                                                                                                                                       
      '--column',                                                                                                                                                            
      '--smart-case'                                                                                                                                                         
    },                                                                                                                                                                       
    mappings = {                                                                                                                                                             
      i = {                                                                                                                                                                  
            ["<Esc>"] = require('telescope.actions').close,                                                                                                                  
            ["<C-b>"] = function()                                                                                                                                           
                vim.cmd("close!")                                                                                                                                            
                require('telescope.builtin').file_browser({initial_mode = 'insert'})                                                                                         
            end,                                                                                                                                                             
            ["<C-d>"] = function ()                                                                                                                                          
                vim.cmd("close!")                                                                                                                                            
                require('telescope').extensions.zoxide.list({initial_mode = 'insert'})                                                                                       
            end,                                                                                                                                                             
            ["<C-f>"] = function()                                                                                                                                           
                vim.cmd("close!")                                                                                                                                            
                require('telescope.builtin').current_buffer_fuzzy_find({initial_mode = 'insert'})                                                                            
            end,                                                                                                                                                             
            ["<C-g>"] = function()                                                                                                                                           
                vim.cmd("close!")                                                                                                                                            
                require('telescope.builtin').live_grep({initial_mode = 'insert'})                                                                                            
            end,                                                                                                                                                             
            ["<C-o>"] = function()                                                                                                                                           
                vim.cmd("close!")                                                                                                                                            
                require('telescope.builtin').find_files({initial_mode = 'insert'})                                                                                           
            end,                                                                                                                                                             
            ["<C-r>"] = function()                                                                                                                                           
                vim.cmd("close!")                                                                                                                                            
                require('telescope.builtin').oldfiles({initial_mode = 'insert'})                                                                                             
            end,                                                                                                                                                             
        }                                                                                                                                                                    
    },                                                                                                                                                                       
    prompt_prefix = "🔍 ",                                                                                                                                                   
    selection_caret = " ",                                                                                                                                                  
    entry_prefix = "  ",                                                                                                                                                     
    initial_mode = "insert",                                                                                                                                                 
    selection_strategy = "reset",                                                                                                                                            
    sorting_strategy = "ascending",                                                                                                                                          
    layout_strategy = "horizontal",                                                                                                                                          
    layout_config = {                                                                                                                                                        
      prompt_position = "top",                                                                                                                                               
      horizontal = {                                                                                                                                                         
        width = { padding = 10 },                                                                                                                                            
        height = { padding = 0.1 },                                                                                                                                          
        preview_width = 0.5,                                                                                                                                                 
      },                                                                                                                                                                     
      vertical = {                                                                                                                                                           
        width = { padding = 0.05 },                                                                                                                                          
        height = { padding = 1 },                                                                                                                                            
        preview_height = 0.5,                                                                                                                                                
      }                                                                                                                                                                      
    },                                                                                                                                                                       
  }                                                                                                                                                                          
}                                                                                                                                                                            
require('telescope').load_extension('fzy_native')                                                                                                                            
require'telescope'.load_extension('zoxide')                                                                                                                                  
require("telescope._extensions.zoxide.config").setup({                                                                                                                       
  mappings = {                                                                                                                                                               
    default = {                                                                                                                                                              
      after_action = function(selection)                                                                                                      
        require('telescope.builtin').find_files({initial_mode = 'insert'})                                                                                                   
      end                                                                                                                                                                    
    }                                                                                                                                                                        
  }                                                                                                                                                                          
})   
`
What really causes the problem reliably is the zoxide after_action at the end of that config. After I switch to a new directory with zoxide, it then opens the file picker from that new directory. That may be more of a zoxide extension issue, but it definitely happens from switching pickers using my insert mode mappings as well.

**Comment by fdschmidt93** [comment] 2021-09-11 21:24
Issue template please. Did you read this thread carefully? From what I understand of what you wrote, there is not necessarily an immediate connection to OP apart from an comparable end result.

**Comment by cseickel** [comment] 2021-09-11 22:44
Sorry, I was thinking this was a more generic problem that applied to initial_mode for all buffer types. Now I can't seem to recreate the issue outside of the one zoxide situation.

Please disregard, and thank you for maintaining this awesome project!

**Comment by ValdemarGr** [comment] 2021-09-12 23:25
Upgrading to 0.6.0 (`v0.6.0-dev+250-g521817ee7`, HEAD at the time) fixed these issues for me.

Furthermore, the new way of handling previews seems to cause `autocmd`s to run, is this also intentional?

Thank you.

**Comment by fdschmidt93** [comment] 2021-09-13 06:03
> Furthermore, the new way of handling previews seems to cause autocmds to run, is this also intentional?

This probably needs another repro. The `plenary.popup` windows are opened with `noautocmd`, but there probably are a bunch of ways `autocmd`s can still be triggered unintentionally, especially since we now show the actual buffers.

Ok if we close this one and open a new issue for that for tidyness?

**Closed** 2021-09-13 10:02 UTC
Labels: bug
