### ISSUE TITLE
Telescope Setup -- find_command

### ISSUE THREAD

**Issue by mthomps4** [nvim-telescope/telescope.nvim#2299] opened 2023-01-04 14:37 UTC
### Description

The below works from both the command line and keybindings, but does not seem to work when placing within the `telescope.setup({pickers` block 

**Works:**
```vim
:Telescope find_files find_command=rg,--ignore,--hidden,--files,-u,--glob,!**/.git/*,--glob,!**/node_modules/*
```
```lua
vim.keymap.set('n', '<leader>ff', ":Telescope find_files find_command=rg,--ignore,--hidden,--files,-u,--glob,!**/.git/*,--glob,!**/node_modules/*,--glob,!**/.next/*<CR>")
```

**Not working**
```
    pickers = {
      find_files = {
        find_command = {"rg", "--files", "--hidden", "--ignore", "-u", "--glob=!**/.git/*", "--glob=!**/node_modules/*"},    
      }
    },
```

### Neovim version

```markdown
NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura
```

### Operating system and version

macOS 13.0.1

### Telescope version / branch / rev

telescope branch: 0.1.x 

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - OK: lib working as expected
  - OK: file_sorter correctly configured
  - OK: generic_sorter correctly configured
```

### Steps to reproduce

Keybindings reverted back to below via docs: 
```
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
```

add to setup 
```
    pickers = {
      find_files = {
        find_command = {"rg", "--files", "--hidden", "--ignore", "-u", "--glob=!**/.git/*", "--glob=!**/node_modules/*"},    
      }
    },
```

- open a project in nvim 
- <leader>ff
- Search for hidden file or ignored file. 

### Expected behavior

Hidden and Ignored files are found. 
Example: 
- <leader>ff 
- search .env.loc
- see .env.local file 

![image](https://user-images.githubusercontent.com/17518011/210577985-9fc0ca50-263d-45da-9904-2c7e37bcee04.png)

### Actual behavior

With setup > long string keybind 

- <leader>ff 
- search .env.loc
- no files found 

![image](https://user-images.githubusercontent.com/17518011/210578334-830236f7-928e-45c5-8f4a-dee22da16c2c.png)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup({
    pickers = {
      find_files = {
        find_command = {"rg", "--files", "--hidden", "--ignore", "-u", "--glob=!**/.git/*", "--glob=!**/node_modules/*", "--glob=!**/.next/*"},    
      }
    }
})
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by Conni2461** [comment] 2023-01-06 12:57
it works with the minimal rc for me. Could you reproduce this issue with running the minimal rc? `nvim -nu min.lua`

**Comment by Conni2461** [comment] 2023-01-06 13:01
found the issue, i forgot to backport a fix to 0.1.x that was already merged into master. I am going to do that now

**Comment by Conni2461** [comment] 2023-01-06 13:40
The fix (and a bunch of more fixes) are now all backported. Can you confirm that it works? Then we can close this issue

**Comment by mthomps4** [comment] 2023-01-07 01:08
@Conni2461 Thank you so much for the quick reply. 
Making sure I'm not overlooking something, but seem to still be hitting the same issue. 

- resaved plugin-config -- saw changes from `11 hours ago` 
- Keybinding is now `vim.keymap.set('n', '<leader>ff', builtin.find_files, {})`
- telescope config: 
```lua 
    pickers = {
      find_files = {
        find_command = {"rg", "--files", "--hidden", "--ignore", "-u", "--glob=!**/.git/*", "--glob=!**/node_modules/*"},    
      }
    },
```

**Comment by mthomps4** [comment] 2023-01-09 04:08
Tried a few more things -- more of the same. 
Deleted the plugin download cache from packer. 
Reinstalled 
Tried both tag and branch 
Added `fd` 
I see the fixes that were merged -- but it's still only working for me if I do the long hand below. 

```
vim.keymap.set('n', '<leader>ff', ":Telescope find_files find_command=rg,--ignore,--hidden,--files,-u,--glob,!**/.git/*,--glob,!**/node_modules/*,--glob,!**/.next/*<CR>")
```

Left with ☝🏼 for now.

**Comment by jneidel** [comment] 2023-04-16 18:02
I couldn't make it work with --glob or --iglob, but declaring the stuff I want to ignore in `file_ignore_patterns` works as expected: 

```
telescope.setup {
    defaults = {
      file_ignore_patterns = {
        "node_modules/",
        "vendor/",
        ".git/"
    }
  }
}

```

**Comment by jamestrew** [comment] 2024-01-23 02:35
pretty the glob flag and the glob pattern should be in their own separate strings.
something like
`"--glob=!**/.git/*"` -> `"--glob", "!**/.git/*"`

I've been using this for a while.

I'm going to close this as I don't think this is a bug and at worst it looks like there's some workarounds.

**Closed by jamestrew** 2024-01-23 02:35 UTC
Labels: bug
