### ISSUE TITLE
Add the "smart" path display option to `lsp_references` and others.

### ISSUE THREAD

**Issue by lewisdiamond** [nvim-telescope/telescope.nvim#2519] opened 2023-05-22 16:13 UTC
Currently, `lsp_references` displays the entire path and file regardless of the length. Having long file names and paths results in truncated file name or no file name at all. Adding the "smart" file_display option to lsp commands would allow to change that behavior.

**Comment by jamestrew** [comment] 2023-05-22 21:44
I'm pretty sure this works already no?
`:Telescope lsp_references path_display={"smart"}`

**Comment by c3n21** [comment] 2023-05-31 09:04
Perhaps could be more useful if it could be possible to hide the second column when it shows up the result

![image](https://github.com/nvim-telescope/telescope.nvim/assets/37077738/4214071d-5d90-4d57-bae9-b9e8c1410d52)

The line preview isn't so much useful if you can have the complete preview, removing that could save so much space.

**Comment by jamestrew** [comment] 2023-06-13 02:28
> The line preview isn't so much useful if you can have the complete preview, removing that could save so much space

I'll consider this as a duplicate of https://github.com/nvim-telescope/telescope.nvim/issues/2507
Something I'm interested in doing but we don't really have a clean way of implementing something like this across multiple pickers.

**Closed by jamestrew** 2023-06-13 02:28 UTC
Labels: enhancement
