### ISSUE TITLE
Setting sorting to ascending with the previewer causes selection caret to disappear

### ISSUE THREAD

**Issue by medwatt** [nvim-telescope/telescope.nvim#840] opened 2021-05-13 08:39 UTC
### Description
Setting `sorting-strategy` to `ascending` with the previewer showing causes selection caret to disappear. If the `sorting-strategy` is set to `descending`, the selection caret does not disappear, and works as expected.

### To Reproduce

1. Set `sorting-strategy` to `ascending`

2. Execute `Telescope find_files` in a folder that has a lot of files and subfolders.

3. Make sure the the previewer is showing.

4. Search for something; the selection caret disappears.

### Video

In the first half of the video, I execute `Telescope find_files` in a folder that doesn't have subfolders. The selection caret does not disappear. The selection caret seems to disappear when there are a lot of files and subfolders and the previewer is showing.

![ss](https://i.imgur.com/BampFvx.gif)

**Comment by Conni2461** [comment] 2021-05-16 18:51
Probably a regression from #709 
And probably also related to https://github.com/nvim-telescope/telescope.nvim/issues/777

**Comment by Conni2461** [comment] 2021-05-16 18:52
But tbh i can't reproduce. The cursor always reappears after a second. And i don't see a difference between `ascending` and `descending`

**Comment by medwatt** [comment] 2021-05-17 20:15
@Conni2461, did you try to open `telescope find_files` in a folder with subfolders while also having the previewer enabled?

**Comment by rcarriga** [comment] 2021-05-30 18:51
Can confirm I'm having the same issue with just the sorting_strategy set 
```lua
  telescope.setup {
    defaults = {sorting_strategy = "ascending"}
  }
```
I don't get it everywhere, it doesn't happen in my home directory but does happen in the telescope repository. Not sure what other info I can provide not already given

**Comment by jedrzejboczar** [comment] 2021-06-23 20:14
I also experience the same issue with `sorting_strategy = 'ascending'`. I tried to find in the code what might be different for ascending/descending and found the following part:
https://github.com/nvim-telescope/telescope.nvim/blob/6ac5ee0854fe02d651cadf2fc97a2463ff92f322/lua/telescope/pickers.lua#L898-L902
I changed it to:
```lua
    if insert then
      if self.sorting_strategy == 'descending' then
        vim.api.nvim_buf_set_lines(self.results_bufnr, 0, 1, false, {})
      else
        vim.api.nvim_buf_set_lines(self.results_bufnr, self.max_results - 1, self.max_results, false, {})
      end
    end
```
and now it seems to be working correctly. However I am not really sure if this is a correct solution, I know very little about the code and am just guessing. Could someone who knows it better take a look if this is ok?

**Comment by JRasmusBm** [comment] 2021-07-12 07:00
@jedrzejboczar This fix works for me, I don't know the code either but I'm submitting it as a PR since I think it's good enough :smile: Thank you for your fix!

**Comment by lalitmee** [comment] 2021-08-04 21:10
I am also facing the same issue and yeah I have installed the `Fastfold` plugin.

**Comment by bujesse** [comment] 2021-08-31 12:33
I was able to fix this issue and keep `Konfekt/FastFold` installed by adding this to my config: 
`let g:fastfold_skip_filetypes = ['TelescopeResults']`

`TelescopeResults` was added in #1019

**Comment by Conni2461** [comment] 2022-01-14 18:46
results have a filetype (TelescopeResults) for quite some time and plugins can be disabled for this buffer. Closing

**Closed by Conni2461** 2022-01-14 18:46 UTC
Labels: bug
