### ISSUE TITLE
`-type` option of ripgrep is not working well for live_grep

### ISSUE THREAD

**Issue by uki1014** [nvim-telescope/telescope.nvim#1832] opened 2022-04-09 12:11 UTC
### Description

`--type` option of ripgrep is working fine for `find_files`.

`vim.api.nvim_set_keymap('n', ';h', ":Telescope find_files find_command=rg,--ignore-case,--hidden,--files,--type=ruby<CR>", { noremap = true, silent = false })`

but for live_grep, the `-type` option is not reflected correctly in the results of telescope's grep.
`vim.api.nvim_set_keymap('n', ';hr', ":Telescope live_grep find_command=rg,--ignore-case,--hidden,--files,--type=ruby<CR>", { noremap = true, silent = false })`

my telescope config

```lua
vim.api.nvim_set_keymap('n', ';h', ":Telescope find_files find_command=rg,--ignore-case,--hidden,--files,--type=ruby<CR>", { noremap = true, silent = false })
vim.api.nvim_set_keymap('n', ';hr', ":Telescope live_grep find_command=rg,--ignore-case,--hidden,--files,--type=ruby<CR>", { noremap = true, silent = false })

local actions = require('telescope.actions')
  -- Global remapping
  ------------------------------
  require('telescope').setup{
    defaults = {
    ┊ initial_mode = "insert",
    ┊ mappings = {
    ┊ ┊ n = {
    ┊ ┊ ┊ ['q'] = actions.close
    ┊ ┊ },
    ┊ },
    }
  }
```

### Neovim version

```markdown
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az87-780

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

### Operating system and version

Linux 20.04.2-Ubuntu x86_64 GNU/Linux

### checkhealth telescope

```markdown
telescope: require("telescope.health").check()
  ========================================================================
  ## Checking for required plugins
    - OK: plenary installed.
    - WARNING: nvim-treesitter not found.

  ## Checking external dependencies
    - OK: rg: found ripgrep 13.0.0
    - OK: fd: found fd 7.4.0

  ## ===== Installed extensions =====

  ## Telescope Extension: `fzf`
    - INFO: No healthcheck provided
```

### Steps to reproduce

1. Create tmp.rb and tmp.txt in the project
2. `echo 'tmp ruby' >> tmp.rb && echo 'tmp txt' >> tmp.txt`
3. The result of executing `Telescope find_files find_command=rg,--ignore-case,--hidden,--files,--type=ruby` is not contain tmp.txt.
4. The result of executing `Telescope live_grep find_command=rg,--ignore-case,--hidden,--files,--type=ruby` **is contain** tmp.txt.

### Expected behavior

The `-type` option is also enabled in live_grep.

### Actual behavior

![スクリーンショット 2022-04-09 21 10 23](https://user-images.githubusercontent.com/48374767/162573605-a7d1364f-2296-4c7f-9345-d43e2bcf5046.png)

### Minimal config

```Lua
vim.api.nvim_set_keymap('n', ';h', ":Telescope find_files find_command=rg,--ignore-case,--hidden,--files,--type=ruby<CR>", { noremap = true, silent = false })
vim.api.nvim_set_keymap('n', ';hr', ":Telescope live_grep find_command=rg,--ignore-case,--hidden,--files,--type=ruby<CR>", { noremap = true, silent = false })

local actions = require('telescope.actions')
  -- Global remapping
  ------------------------------
  require('telescope').setup{
    defaults = {
    ┊ initial_mode = "insert",
    ┊ mappings = {
    ┊ ┊ n = {
    ┊ ┊ ┊ ['q'] = actions.close
    ┊ ┊ },
    ┊ },
    }
  }
```

**Comment by Conni2461** [comment] 2022-04-09 13:10
`live_grep` does not use `find_command` that is something specific to `builtin.find_files`. You can define your global grep command, see `telescope.defaults.vimgrep_arguments` or use additional args. See `:help builtin.live_grep`

Example:
`:lua require("telescope.builtin").live_grep({ additional_args = function() return { "--type=ruby" } end })`

I might merge https://github.com/nvim-telescope/telescope.nvim/pull/1695 to streamline this into `Telescope live_grep type_filter=ruby`

Not a bug closing.

**Closed by Conni2461** 2022-04-09 13:10 UTC
Labels: bug

**Comment by uki1014** [comment] 2022-04-09 13:33
Thank you for your response.
