### ISSUE TITLE
E5108: Error executing lua: ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:762: BufEnter Autokommandos für "*": Vim(append):Error executing lua callback: ...m/lazy/navigator.lua/lua/navigator/lspclient/clients.lua:641: attempt to call field 'get_clients' (a nil value)

### ISSUE THREAD

**Issue by cupakob** [nvim-telescope/telescope.nvim#3129] opened 2024-05-21 07:21 UTC
### Description

When I try to open more than one file, I get following error message:

```
E5108: Error executing lua: ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:762: BufEnter Autokommandos für "*": Vim(append):Error executing lua callback: ...m/lazy/navigator.lua/lua/navigator/lspclient/clients.lua:641: attempt to call field 'get_clients' (a nil value)
stack traceback:
        ...m/lazy/navigator.lua/lua/navigator/lspclient/clients.lua:641: in function 'on_filetype'
        ...a/.local/share/nvim/lazy/navigator.lua/lua/navigator.lua:353: in function <...a/.local/share/nvim/lazy/navigator.lua/lua/navigator.lua:352>
        [C]: in function 'nvim_win_close'
        ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:762: in function 'close_windows'
        ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:1508: in function 'on_close_prompt'
        ...e/nvim/lazy/telescope.nvim/lua/telescope/actions/set.lua:134: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:253: in function <...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:252>
stack traceback:
        [C]: in function 'nvim_win_close'
        ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:762: in function 'close_windows'
        ...share/nvim/lazy/telescope.nvim/lua/telescope/pickers.lua:1508: in function 'on_close_prompt'
        ...e/nvim/lazy/telescope.nvim/lua/telescope/actions/set.lua:134: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'run_replace_or_original'
        ...re/nvim/lazy/telescope.nvim/lua/telescope/actions/mt.lua:65: in function 'key_func'
        ...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:253: in function <...hare/nvim/lazy/telescope.nvim/lua/telescope/mappings.lua:252>
```

If I try to open a file via `:e <any_file>` I get similar error:

```                                                                                                                                                   
Fehler beim Ausführen von "BufReadPost Autokommandos für "*.mod"..FileType Autokommandos für "*"":
Error executing lua callback: ...m/lazy/navigator.lua/lua/navigator/lspclient/clients.lua:585: attempt to call field 'get_clients' (a nil value)
stack traceback:
        ...m/lazy/navigator.lua/lua/navigator/lspclient/clients.lua:585: in function 'setup'
        ...m/lazy/navigator.lua/lua/navigator/lspclient/clients.lua:663: in function 'on_filetype'
        ...a/.local/share/nvim/lazy/navigator.lua/lua/navigator.lua:353: in function <...a/.local/share/nvim/lazy/navigator.lua/lua/navigator.lua:352>
Fehler beim Ausführen von "BufEnter Autokommandos für "*"":
Error executing lua callback: ...m/lazy/navigator.lua/lua/navigator/lspclient/clients.lua:641: attempt to call field 'get_clients' (a nil value)
stack traceback:
        ...m/lazy/navigator.lua/lua/navigator/lspclient/clients.lua:641: in function 'on_filetype'
        ...a/.local/share/nvim/lazy/navigator.lua/lua/navigator.lua:353: in function <...a/.local/share/nvim/lazy/navigator.lua/lua/navigator.lua:352>
```

Or when I run `nvim <file>` I get again a similar error:
```
Fehler beim Ausführen von "BufReadPost Autokommandos für "*"":
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:24: Error executing lua: /usr/share/nvim/runtime/filetype.lua:25: BufReadPost Autokommandos für "*"..FileType Autokommandos für "*": Vim(append):Error executing lua callback: ...m/lazy/navigator.lua/lua/navigator/lspclient/clients.lua:585: attempt to call field 'get_clients' (a nil value)
stack traceback:
        ...m/lazy/navigator.lua/lua/navigator/lspclient/clients.lua:585: in function 'setup'
        ...m/lazy/navigator.lua/lua/navigator/lspclient/clients.lua:663: in function 'on_filetype'
        ...a/.local/share/nvim/lazy/navigator.lua/lua/navigator.lua:353: in function <...a/.local/share/nvim/lazy/navigator.lua/lua/navigator.lua:352>
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:25: in function </usr/share/nvim/runtime/filetype.lua:24>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:24: in function </usr/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_cmd'
        /usr/share/nvim/runtime/filetype.lua:25: in function </usr/share/nvim/runtime/filetype.lua:24>
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:24: in function </usr/share/nvim/runtime/filetype.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /usr/share/nvim/runtime/filetype.lua:24: in function </usr/share/nvim/runtime/filetype.lua:10>
Fehler beim Ausführen von "BufEnter Autokommandos für "*"":
Error executing lua callback: ...m/lazy/navigator.lua/lua/navigator/lspclient/clients.lua:641: attempt to call field 'get_clients' (a nil value)
stack traceback:
        ...m/lazy/navigator.lua/lua/navigator/lspclient/clients.lua:641: in function 'on_filetype'
        ...a/.local/share/nvim/lazy/navigator.lua/lua/navigator.lua:353: in function <...a/.local/share/nvim/lazy/navigator.lua/lua/navigator.lua:352>
```

### Neovim version

```markdown
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1713773202
```

### Operating system and version

Linux Manjaro 24.0.0

### Telescope version / branch / rev

version 0.1.7

### checkhealth telescope

```markdown
0                                                                                
 1 ────────────────────────────────────────────────────────────────────────────── 
 2 telescope: require("telescope.health").check()                                 
 3                                                                                
 4 Checking for required plugins                                                  
 5 - OK plenary installed.                                                        
 6 - OK nvim-treesitter installed.                                                
 7                                                                                
 8 Checking external dependencies                                                 
 9 - OK rg: found ripgrep 14.1.0                                                  
10 - OK fd: found fd 10.0.0                                                       
11                                                                                
12 ===== Installed extensions =====                                               
13                                                                                
14 Telescope Extension: `file_browser`                                            
15 - No healthcheck provided                                                      
16                                                                                
17 Telescope Extension: `fzf`                                                     
18 - OK lib working as expected                                                   
19 - OK file_sorter correctly configured                                          
20 - OK generic_sorter correctly configured                                       
21
```

### Steps to reproduce

1. open nvim
2. open file browser
3. select file and open it
4. open file browser again
5. select another file to open
6. open the second file

### Expected behavior

The second file is opened successfully

### Actual behavior

The second file is not opened

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by jamestrew** [comment] 2024-05-21 13:13
Looks like an issue with navigator.lua reading the error.

Please try to reproduce this with the minimal config.

**Comment by Conni2461** [comment] 2024-05-22 21:39
closing as invalid report, this has nothing todo with telescope and no minimal reproduce was provided

**Closed by Conni2461** 2024-05-22 21:39 UTC
Labels: bug

**Comment by philomates** [comment] 2024-06-04 09:15
I'm also getting this error. When I remove https://github.com/nvim-telescope/telescope.nvim/blame/dfa230be84a044e7f546a6c2b0a403c739732b86/lua/telescope/pickers.lua#L138 the error stops but the selected file doesn't open. Unsure what changed in my setup to prompt this error though

**Comment by philomates** [comment] 2024-06-04 09:25
okay, looks like I had a typo in a custom config I had for `:WinLeave` for `TelescopePrompt` filetypes. When I corrected it everything works fine. Apologies for the noise

**Comment by juk3-min** [comment] 2025-05-06 08:44
> I'm getting this error with kickstart nvim. No typos.

I searched my config for "BufEnter". There seemed to be an issue with     'mfussenegger/nvim-lint'. Disabling some filetypes (markdown in my case) fixed the issue. 
`lint.linters_by_ft['markdown'] = nil`
In other words, this seems not be a nvim-telescope issue like @Conni2461 explained, but another plugin which f's up entering the buffer.

**Comment by max-woolf** [comment] 2025-05-06 19:08
I've opened the issue in kickstart.nvim since it's about the configuration: https://github.com/nvim-lua/kickstart.nvim/issues/1510
