### ISSUE TITLE
E5108: attempt to call field 'create' (a nil value)

### ISSUE THREAD

**Issue by gikeymarcia** [nvim-telescope/telescope.nvim#1106] opened 2021-08-11 19:56 UTC
### Description

Telescope throws an `E5108` error when I attempt to run any of it's commands. Ran a `:PlugUpdate` this morning and have had this issue since.

**Expected Behavior**

I should be able to use `find_files`, `live_grep`, etc.

**Actual Behavior**

Error code:

```
E5108: Error executing lua 
/tmp/plugged/telescope.nvim/lua/telescope/pickers.lua:302: 
attempt to call field 'create' (a nil value)
```

### Details

<details><summary>Reproduce</summary>

1. `nvim -Nu test.vim`
2. Run any `:Telescope` command (all following produce the same error)
    - `:Telescope live_grep`
    - `:Telescope buffers`
    - `:Telescope colorscheme`
3. `E5108`

</details>

<details><summary>Environment</summary>

- nvim --version output:

```
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az242-526

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
NVIM v0.5.0
```

- Operating system: Ubuntu 21.04 fully up-to-date
- Telescope commit: `d4a52de`

</details>

<details><summary>Configuration</summary>
<p>

```viml
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync | close
lua require('telescope').setup()
```

**Comment by clason** [comment] 2021-08-11 20:12
Duplicate of #1105

**Closed** 2021-08-11 20:12 UTC
Labels: bug
