### ISSUE TITLE
Endless garbled nonsense appears when opening telescope

### ISSUE THREAD

**Issue by raiguard** [nvim-telescope/telescope.nvim#362] opened 2020-12-24 03:07 UTC
### Description
When I open a telescope finder/picker, my terminal gets spammed with nonsense.

**Expected Behavior**
Telescope would open and I would be able to use it.

**Actual Behavior**
Telescope opens, then immediately begins to barf out endless messages of varying content.

### Details

<details><summary>Reproduce</summary>

1. Install telescope with no optional dependencies.
2. Run `:Telescope find_files` and observe bug.
</details>

<details><summary>Environment</summary>

- nvim version: v0.5.0-828-g0a95549d6
- Operating system: Windows 10 v2004 (b19041.685)
- Telescope commit: 049602a
- Terminal: Alacritty
</details>

<details><summary>Configuration</summary>
No configuration whatsoever! I tested this with an empty init.vim save for loading telescope and its dependencies.
</details>

### Video

https://user-images.githubusercontent.com/3515394/103056218-93dbe600-4559-11eb-856c-962e76a32afb.mp4

**Comment by Conni2461** [comment] 2020-12-24 09:39
Hmm last time i was testing a feature it worked :)
I will investigate this next week after Christmas. But note i know nothing about windows, i have to setup a new VM first 😆.

Note to myself: We should also setup a CI for windows. Does github actions support windows?!

**Comment by Conni2461** [comment] 2020-12-26 13:46
Okay can't reproduce. Can you please share more information about your env. Like what shell? I tried `cmd.exe`. And run `nvim -nu min.vim` with that rc.
```viml
set nocompatible hidden laststatus=2

if !filereadable('~/nvim/plug.vim')
  silent !curl --insecure -fLo ~/nvim/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source ~/nvim/plug.vim
call plug#begin('~/nvim/plugged')
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()
```

**Comment by raiguard** [comment] 2020-12-26 21:33
I am using Alacritty with Git Bash.

I had to change the file paths in the vimrc you provided in order to point to the correct location (`~/AppData/Local/nvim/autoload/plug.vim`), but otherwise it remains unchanged. The problem still occured with that configuration.

When I ran `nvim -nu min.vim`, it printed `E282: Cannot read from "min.vim"` to the vim console. Then I was unable to use Telescope.

In case it matters, my vimrc and `plug.vim` are symlinked from a git repository. I assume this is a common practice though.

**Comment by Conni2461** [comment] 2020-12-26 21:41
Hmm its really hard to say if its a setup issue or a telescope problem. Thats why minimal rc.
I have no windows experience. Haven't used it in like 3 years, so i just started `cmd.exe` no different terminal emulator but i believe that should not be an issue. The same applies for fullscreen of a different resolution.

> When I ran nvim -nu min.vim, it printed E282: Cannot read from "min.vim" to the vim console. Then I was unable to use Telescope.

You need to have `min.vim`, which contains my snippet, in the directory you are running nvim.

**Comment by raiguard** [comment] 2020-12-26 21:47
> When I ran nvim -nu min.vim, it printed E282: Cannot read from "min.vim" to the vim console. Then I was unable to use Telescope.

Ah, my apologies. I just replaced my actual vimrc with yours to do the test. Putting it in a separate file and running like that does not change the result.

Running telescope in Alacritty at its default resolution also works, but telescope lags to insanity when you type (it hangs for several seconds before things start to happen).

Running it in `cmd.exe` works at any screen resolution, but I experience the aforementioned horrendous lag.

**Comment by Conni2461** [comment] 2020-12-26 21:49
> Running it in cmd.exe works at any screen resolution, but I experience the aforementioned horrendous lag.

It lagged for me too. I thought that was just the VM. I will try out alacritty.
Also could you try what i mentioned in my second edit previous post.

**Comment by raiguard** [comment] 2020-12-26 21:54
Running telescope without the previewer does seem to fix the issue, but the lag remains.

**Comment by raiguard** [comment] 2020-12-26 21:57
Here it is in `cmd.exe`:

https://user-images.githubusercontent.com/3515394/103159759-94a78e80-478a-11eb-9142-d0e1f37538ce.mp4

**Comment by Conni2461** [comment] 2020-12-26 21:59
Okay i can reproduce the crash. Default sorter is slow. Give me a sec and i will show you how to make a decent setup for 130k files :)

**Comment by Conni2461** [comment] 2020-12-26 22:08
```lua
require('telescope').setup {
  defaults = {
    file_previewer = previewers.vim_buffer_cat.new,
    grep_previewer = previewers.vim_buffer_vimgrep.new,
    qflist_previewer = previewers.vim_buffer_qflist.new,
  }
}
```

That will give you "experimental" previewers without `cat`/`less`/`bat` which should fix your crash. It will display the file inside a vim buffer and either tree sitter or regex will do highlighting. We are moving to deprecate the old buffers anyway because they are more buggy than the "experimental" once and there is another PR by me (i basically wrote them with some help from tj. shameless plug) which make `vim_grep` and `qflist` async as well.

```lua
    file_sorter =  require'telescope.sorters'.get_fzy_sorter,
    generic_sorter =  require'telescope.sorters'.get_fzy_sorter,
```

Will use a lua fork fzy sorter.
Or you check out [this](https://github.com/nvim-telescope/telescope-fzy-native.nvim) which is a compiled fzy sorter so even more speed :)

**Comment by raiguard** [comment] 2020-12-26 22:17
Thank you, that is working much better! I was going to complain about the speed some more, but then I realized that I was using telescope in my root development folder, which is over 60 GB and has 350k files. Using it in an actual project is completely fine! I am unable to get it to crash now.

There is one last thing though, while I have your attention: how do I get rid of the `^M` at the end of every line in the preview?

![image](https://user-images.githubusercontent.com/3515394/103160017-6a0b0500-478d-11eb-8aef-42918133b847.png)

**Comment by Conni2461** [comment] 2020-12-26 22:27
That's thanks to different newline characters: https://stackoverflow.com/a/5843561
What we do is read the file async with `luv.fs_` and put the content in the buffer so i kinda have to modify the content and get rid of it in each line which can lead to a slowdown. But, another shameless plug, https://github.com/nvim-telescope/telescope.nvim/pull/354 will implement a way to overwrite the file reader and we plan to create a extension which will allow us to do more stuff. For example i can provide a function which will get rid of the `^M`. But that might take a week or so. :)

**Comment by raiguard** [comment] 2020-12-26 22:33
That's alright, I can live with them for a while. Thank you again!

**Comment by Conni2461** [comment] 2020-12-29 21:50
There are new developments. I am still not done with the extension but right now you can put something like this in your config to get rid of the `^M`.
```lua
local previewers = require('telescope.previewers')
local putils = require('telescope.previewers.utils')
local path = require('telescope.path')
local pfiletype = require('plenary.filetype')

local new_maker = function(filepath, bufnr, bufname, use_ft_detect, callback)
  if use_ft_detect == nil then use_ft_detect = true end
  local ft = use_ft_detect and pfiletype.detect(filepath)

  if bufname ~= filepath then
    path.read_file_async(filepath, vim.schedule_wrap(function(data)
      data = data:gsub([[\r]], '')
      vim.api.nvim_buf_set_lines(bufnr, 0, -1, false, vim.split(data, "\n"))

      if callback then callback(bufnr) end
    end))
  else
    if callback then callback(bufnr) end
  end

  putils.highlighter(bufnr, ft)
end

require('telescope').setup {
  defaults = {
    buffer_previewer_maker = new_maker,
  }
}
```

Does that work for you? I haven't tested it

**Comment by raiguard** [comment] 2020-12-29 21:54
Unfortunately, that does not appear to work.

**Comment by Conni2461** [comment] 2020-12-29 22:05
Updated the code snippet. That should work now :) I tested it. Make sure you have current telescope head

**Comment by raiguard** [comment] 2020-12-29 22:13
Strange, the updated snippet doesn't work for me either.

**Comment by Conni2461** [comment] 2020-12-29 22:15
I have a PR. Give me a second. Then you can try that one and if that one works i will merge and it will just work for you 😆

**Comment by raiguard** [comment] 2020-12-29 22:16
You're too kind! Thank you. :)

**Comment by Conni2461** [comment] 2020-12-29 22:18
https://github.com/nvim-telescope/telescope.nvim/pull/371 :) I should have thought about that earlier. I was just too caught up with the new interface 😆

**Comment by Conni2461** [comment] 2020-12-30 21:39
@raiguard Did you find time testing that PR? I won't merge if you don't confirm that this actually fixes the issue

**Comment by raiguard** [comment] 2021-01-01 08:32
My apologies, I'll make some time to test it soon.

**Comment by Conni2461** [comment] 2021-01-11 20:15
I will close that. The buffer_previewers work on windows now and will become default soon.

**Closed by Conni2461** 2021-01-11 20:15 UTC
Labels: Term Previewer, Windows, bug
