### ISSUE TITLE
Segmentation fault upon file selection

### ISSUE THREAD

**Issue by andweeb** [nvim-telescope/telescope.nvim#1391] opened 2021-10-29 17:34 UTC
### Description

The latest change in 3b9ac8e seems to cause a segfault whenever an item in the picker is selected.

### Neovim version

NVIM v0.5.0-dev+1421-ga72dfec85

### Operating system and version

macOS 11.6

### checkhealth telescope

```markdown
health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 12.1.1 (rev 7cb211378a)
  - OK: fd: found fd 8.2.1

## ===== Installed extensions =====
```

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. `:Telescope find_files`
3. Select a file
4. Segmentation fault

### Expected behavior

I expect nvim not to crash.

### Actual behavior

Nvim crashes anytime I select any item in the picker.

Here's a screencap of the issue with the latest change when using `find_files`, and it working when I revert the commit via vim-plug.

https://user-images.githubusercontent.com/10726590/139477485-fa326344-50a0-4dc8-8c81-e5618a1c1246.mov

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'
local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {
        'nvim-telescope/telescope.nvim',
        requires = {
          'nvim-lua/plenary.nvim',
          { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' },
        },
      },
      -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
      display = { non_interactive = true },
    },
  }
end
_G.load_config = function()
  require('telescope').setup()
  require('telescope').load_extension('fzf')
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
end
if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Telescope and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end
load_plugins()
require('packer').sync()
vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by andweeb** [comment] 2021-10-29 18:06
Is the intention to drop support for v5.0? It might be a good idea to update the README to reference the correct version:
> Neovim ~(v0.5)~ (v0.5.1) or newer is required for telescope.nvim to work.

**Comment by Conni2461** [comment] 2021-10-29 18:12
If this bug only happens pre 0.5.1 then yes. I was not aware of this segfault in this release. So if its confirmed that its fixed in 0.5.1 i will just drop support for 0.5.0. Otherwise i revert.

But your version `NVIM v0.5.0-dev+1421-ga72dfec85` is a dev version that is older than the 0.5.0 release. This is unsupported for quite some time. Its from 06/16/2021.  0.5.0 release was 07/02/2021

**Comment by andweeb** [comment] 2021-10-29 18:21
Ohh gotcha, actually it doesn't seem dropping support will be necessary. You're right, it looks like it's due to me using an outdated dev version of v0.5.

I've tested on both the release version of 0.5 and 0.5.1 and see no issues!

**Comment by creativecreature** [comment] 2021-10-30 11:46
I have this issue on version `v0.5.0`, so it is not just the dev version.

**Comment by reisnobre** [comment] 2021-10-30 14:18
Upgrading also fixed the issue for me

**Comment by bnsngltn** [comment] 2021-10-30 15:07
> 

`v0.5.0` is working on my old setup (rarely updated). But this error occurs on my new machine. Updating to `v0.5.1` fixed it for me.

**Comment by sminez** [comment] 2021-10-31 13:42
I was seeing this when hitting escape to exit out of `:Telescope current_buffer_fuzzy_find theme=ivy` using `0.5.0` on OSX. Updating neovim to `0.5.1` seems to have fixed it but it was consistently segfaulting every time on `0.5.0`

**Comment by Asocia** [comment] 2021-10-31 14:43
I was using `v0.5.0` and updating to `v0.5.1` fixed the issue for me.

**Comment by smackesey** [comment] 2021-10-31 14:46
I am using `v0.6.0-dev+dev-nvimserver-universal-8-ge6059cf63` via [VimR](https://github.com/qvacua/vimr) and I have this or a similar issue-- don't know if it's segfault, but vim freezes when I select an item or exit from the menu. Confirmed that the issue is introduced in 3b9ac8e.

**Comment by Conni2461** [comment] 2021-10-31 15:57
If i see this correctly. VimR has the 0.5.0 release pinned.

I am sorry for all the inconvenience. I will start testing with the minimum required neovim version, for upcoming PRs that i merge.

The minimum required version will be 0.5.0 for now but i dont guarantee that for the future.

I will revert the PR and we will try implement this feature without using a api function that potentially segfaults.

Again sorry for the inconvenience and thanks for your patience :)

**Comment by smackesey** [comment] 2021-10-31 16:02
@Conni2461 thanks. Maybe I'm wrong about the version-- the number I provided is what pops up when running `:version` inside VimR, but I can see the release page says its 0.5.0 under latest snapshot, which I'm using), so I'm not quite sure.

**Closed** 2021-10-31 16:02 UTC
Labels: bug

**Comment by Conni2461** [comment] 2021-10-31 16:09
The commit hash you provided points to the last commit in the repo: https://github.com/qvacua/neovim/commits/e6059cf63cec0de46adb304c7d75bf9bf78946dd which is right after the 0.5.0 release, so its basically 0.5.0

**Comment by Conni2461** [comment] 2021-11-04 06:18
We went back and discussed this over again.

We will bump to 0.5.1. If you cant use this version for some reason you should pin this commit : https://github.com/nvim-telescope/telescope.nvim/commit/587a10d1494d8ffa1229246228f0655db2f0a48a
